#!/usr/bin/env python3
"""batch_songs_series.py — first-drop content for the new Songs / Series lanes.

Hand-curated topics (quirky teaser + personalized explore instruction per the
Curio quality bar) into songs.json / series.json. Idempotent: skips ids that
already exist, dedupes by name.

Entry format: (name, year, creator, [tags...], duration_min, tier, teaser, instruction)
- songs:  byline = artist,  verb Listen, tags [genre, genre, origin]
- series: byline = creator, verb Watch,  tags [genre, genre, origin, franchise?]

Usage: python3 scripts/batch_songs_series.py && python3 scripts/validate_topics.py
"""

import json
import re
import unicodedata
from pathlib import Path

ASSETS = Path("app/src/main/assets/topics")

SONGS = [
    ("Bohemian Rhapsody", 1975, "Queen", ["Rock", "Progressive", "British"], 6, 1,
     "Freddie Mercury wrote most of it on the piano in his flat and the label refused to release a six-minute song with no chorus — it became one of the best-selling singles ever. The 'Galileo' backing vocals took three weeks to layer.",
     "Listen with headphones and count the distinct sections — it's opera, ballad and hard rock in one track. Then listen for the multitracked 'Galileo' pile-up that takes the song to its peak."),
    ("Smells Like Teen Spirit", 1991, "Nirvana", ["Grunge", "Alternative", "American"], 5, 1,
     "Kurt Cobain wrote the riff after mishearing a friend's slogan about a deodorant, and the band was sure it would flop — the music video's bored-mascot chaos made MTV viewers think the crowd was real.",
     "Listen for the verse dynamics — it's the quiet-loud formula that ended an era of hair metal. Then watch the music video and notice the mascot's eyes: the apathy is the point."),
    ("Billie Jean", 1982, "Michael Jackson", ["Pop", "R&B", "American"], 5, 1,
     "The bassline was built from a drum machine demo Quincy Jones wanted to cut, and the 'Not my lover' lyric was about a real fan's claim. The video broke MTV's color barrier in 1983.",
     "Listen for the bassline first — it's the whole song's engine, and Jackson's vocal enters over it like a second instrument. Then count the empty beats in the intro: the tension is the hook."),
    ("Imagine", 1971, "John Lennon", ["Pop", "Ballad", "British"], 3, 1,
     "Lennon wrote it at his piano in Tittenhurst Park with Yoko watching, and the white room in the video is that actual house. It's the most-performed protest song of the 20th century without a single angry note.",
     "Listen to the spare arrangement — just piano, voice and a string sweep that enters late. The radicalism is in how quiet it is; the 'no possessions' line lands because nothing is shouted."),
    ("Like a Rolling Stone", 1965, "Bob Dylan", ["Folk Rock", "Rock", "American"], 6, 1,
     "Dylan nearly shelved the six-minute draft as a novel fragment, and a session drummer's organ figure became the most famous riff in rock. It's the song that made pop lyrics literary.",
     "Listen for the organ — it enters like a second voice answering every line. The song's question ('how does it feel?') is asked to the listener, not the subject."),
    ("Stairway to Heaven", 1971, "Led Zeppelin", ["Rock", "Progressive", "British"], 8, 1,
     "The band kept it off singles for years so the album would sell, and the famous 'guitar store' ban was born from butchered covers. The recorder solo was played on a Mellotron, not real flutes.",
     "Listen through headphones and track the volume arc — it's a quiet-to-loud journey in one song. The 'ooh-ooh' before the solo is the song's center of gravity."),
    ("Yesterday", 1965, "The Beatles", ["Pop", "Ballad", "British"], 2, 1,
     "Paul McCartney dreamed the melody and wrote the working title 'Scrambled Eggs' before settling on lyrics — it's the most-covered song ever, with over 2,200 recorded versions.",
     "Listen for the string quartet — it was the first Beatles song to use classical instruments. The melody is so natural it feels inevitable; try to hear it without the violins and it loses half its sadness."),
    ("Hallelujah", 1984, "Leonard Cohen", ["Folk", "Ballad", "Canadian"], 7, 1,
     "Cohen wrote dozens of verses over five years — the song's famous 'secret chord' is a David reference, and it flopped on release before Jeff Buckley's 1994 cover made it immortal.",
     "Listen to the Buckley version after the Cohen original and hear how the same words change meaning with a different voice. The song is about broken love disguised as scripture."),
    ("Respect", 1967, "Aretha Franklin", ["Soul", "R&B", "American"], 3, 1,
     "Written by Otis Redding as a man's plea, Aretha flipped the pronouns and demanded it — her version became a civil-rights and feminist anthem, and the 'R-E-S-P-E-C-T' spelling was her idea.",
     "Listen for the spelling section — it's the song's thesis in letters. Then notice how the backing singers answer every line: the call-and-response is the argument."),
    ("Purple Haze", 1967, "Jimi Hendrix", ["Rock", "Psychedelic", "American"], 3, 1,
     "Hendrix said the lyric came from a dream about walking under the sea — the famous opening riff is a tritone, the 'devil's interval' banned in medieval church music.",
     "Listen to the opening riff and hear the tritone — it's deliberately unsettling. Then notice how the solo bends the same interval back into melody."),
    ("What a Wonderful World", 1967, "Louis Armstrong", ["Jazz", "Ballad", "American"], 2, 1,
     "Satchmo recorded it at 66, and the label shelved it for a year — it only charted in the US after being used in a film. The song was written as an antidote to Vietnam-era cynicism.",
     "Listen to Armstrong's voice — recorded after his throat problems, it's the sound of a man who knows the world isn't wonderful and sings anyway. The trumpet at the end is his own instrument replying."),
    ("Thriller", 1982, "Michael Jackson", ["Pop", "Funk", "American"], 6, 1,
     "The 14-minute video cost more than most films of the era and the song's famous Vincent Price rap was recorded in two takes — the werewolf howl is a real wolf recording.",
     "Listen for the Vincent Price rap at the end — it's horror as pop. The song's bassline is the horror; the video just makes it visible."),
    ("Every Breath You Take", 1983, "The Police", ["Rock", "New Wave", "British"], 4, 1,
     "Sting wrote it in Jamaica after a divorce, and was horrified to realize people thought it romantic — it's a song about surveillance, not love, and it's one of the most-played songs ever.",
     "Listen to the lyrics as a threat, not a promise — the stalker's logic is the song. The bass is the heartbeat; the song never resolves the tension."),
    ("My Heart Will Go On", 1997, "Celine Dion", ["Pop", "Ballad", "Canadian"], 5, 1,
     "James Horner wrote the theme secretly because the director hated songs in his films — Celine recorded it in one take, and the 'Titanic' flute is actually a synthesized penny whistle.",
     "Listen for the synthesized whistle — it's not a real instrument. The song's melody was built from a demo Horner kept hidden; the director only heard it after the film was cut."),
    ("Shape of You", 2017, "Ed Sheeran", ["Pop", "Dance", "British"], 4, 1,
     "Sheeran wrote it about his girlfriend in 10 minutes, and the marimba riff was sampled from a demo he made with a toy. It became the most-streamed song on Spotify's history.",
     "Listen for the marimba — it's the song's memory hook, and the verse's rhythmic switch ('the club isn't the best place') is the same riff in disguise. The song is a loop wearing a narrative."),
    ("Blinding Lights", 2019, "The Weeknd", ["Synthwave", "Pop", "Canadian"], 3, 1,
     "The Weeknd wanted a song that sounded like 'Take On Me' and 'It's All Coming Back to Me Now' — the 1980s synthwave production made it the most-streamed song in Spotify history.",
     "Listen for the drum machine and the synth arpeggio — they're pure 1980s. The song's loneliness is hidden under the dance beat; the 'I can't see clearly' line is literal in the video."),
    ("Old Town Road", 2019, "Lil Nas X", ["Country Rap", "Trap", "American"], 2, 1,
     "Made with a $30 beat from a teenager on YouTube, the song was removed from the country charts and Billy Ray Cyrus joined a remix — it spent 19 weeks at #1, a record.",
     "Listen for the banjo over the trap beat — the genre clash is the point. The song's viral life is its real story; the remix with Cyrus is the chapter that made it history."),
    ("Royals", 2013, "Lorde", ["Art Pop", "Minimal", "New Zealander"], 3, 1,
     "Lorde wrote the hook after seeing a photo of a Royals baseball cap, and the label nearly cut the track — the minimal production was the 16-year-old's rebellion against opulent pop.",
     "Listen for what's NOT there — the song has almost no bass and no chorus explosion. The minimalism is the message: luxury is the absence of need."),
    ("Rolling in the Deep", 2010, "Adele", ["Soul", "Pop", "British"], 4, 1,
     "Adele wrote it in 10 minutes after a breakup, and the stomping percussion was recorded by stamping on a floor — the 'gonna make you love me' threat is the whole song.",
     "Listen for the stomp — it's a foot on a wooden floor, and it IS the beat. The song's anger is in the restraint; the key change at the end is a door slamming."),
    ("Uptown Funk", 2014, "Mark Ronson", ["Funk", "Pop", "American"], 4, 1,
     "Bruno Mars and Ronson wrote it after a week of funk references — the bassline was built from Chic's 'Good Times' and the horns were recorded live in a Nashville studio.",
     "Listen for the bassline — it's a direct descendant of 1970s funk. The song's genius is that it sounds improvised but every fill is placed; count the horn stabs."),
    ("Wonderwall", 1995, "Oasis", ["Britpop", "Rock", "British"], 4, 1,
     "Noel Gallagher wrote it about a friend, not a lover, and the song's five-chord pattern became the acoustic-guitar standard of a generation — it's one of the most-covered songs of the 1990s.",
     "Listen for the 'maybe' that starts the chorus — it's the song's engine. The song is a promise that never lands; the narrator doesn't know if the wall will break either."),
    ("Lose Yourself", 2002, "Eminem", ["Hip Hop", "Rap", "American"], 5, 1,
     "Eminem wrote the hook in the studio bathroom during the filming of 8 Mile — the song's 'one shot' theme is literally about the take he was about to film.",
     "Listen to the opening — the record scratch and the first verse are a single breath. The song's anxiety is the point: the palm-sweat moment is the song."),
    ("Sicko Mode", 2018, "Travis Scott", ["Hip Hop", "Trap", "American"], 5, 1,
     "The song is three beats stitched together with no chorus — it was literally made in the studio with producer switch-ups mid-session, and the beat changes are the hook.",
     "Listen for the beat switches — there are three, and each one resets the song's momentum. The song's structure is its subject: chaos as composition."),
    ("Gangnam Style", 2012, "PSY", ["K-Pop", "Electronic", "Korean"], 4, 1,
     "The first YouTube video to pass a billion views — PSY's 'horse dance' was based on his own actual bad dancing, and the lyrics mock Seoul's wealthy Gangnam district.",
     "Watch the video and notice the satire — the 'rich' scenes are all absurd. The song's joke is that the dancer is neither rich nor cool; the dance is the punchline."),
    ("Dynamite", 2020, "BTS", ["K-Pop", "Pop", "Korean"], 3, 1,
     "The first all-Korean-group song to debut at #1 on the Hot 100 — the disco-pop track was released during lockdown and its music video's retro styling is a direct 1970s homage.",
     "Listen for the disco strings and the handclaps — the 1970s references are precise. The song's joy is political: a Korean group singing 'light it up like dynamite' in English was a statement."),
    ("Gangsta's Paradise", 1995, "Coolio", ["Hip Hop", "Rap", "American"], 4, 1,
     "The song samples Stevie Wonder's 'Pastime Paradise' and was written for a film about gang life — it became one of the best-selling rap singles ever, and Coolio wrote the chorus as a moral warning.",
     "Listen for the Stevie Wonder sample — the choir underneath is his original. The song's power is the contrast between the serene sample and the violent verses."),
    ("Africa", 1982, "Toto", ["Rock", "Pop", "American"], 5, 1,
     "The band wrote it as a joke about Westerners romanticizing Africa, and the song's famous backing vocals took hours to record — it became a meme decades later, loved for being sincere.",
     "Listen for the kalimba (thumb piano) — it's the song's signature sound, played by the keyboardist who'd never touched one before. The song's earnestness is why the meme works."),
    ("I Will Always Love You", 1973, "Dolly Parton", ["Country", "Ballad", "American"], 3, 1,
     "Dolly wrote it as a farewell to her mentor Porter Wagoner and refused to sell the publishing — Whitney's 1992 cover made it one of the best-selling singles ever, and Dolly kept her rights.",
     "Listen to Dolly's original first — it's a country ballad, not a power anthem. Then hear Whitney's a cappella opening: the song was always about the space between two people."),
    ("Jolene", 1973, "Dolly Parton", ["Country", "Pop", "American"], 3, 1,
     "The song's melody was inspired by a real girl who flirted with her husband, and the name came from a young fan — Dolly wrote it in one afternoon and the 'pleading' vocal is a country masterclass.",
     "Listen to the desperation in the first verse — the narrator doesn't ask, she begs. The song's genius is that Jolene is never described as evil; she's just beautiful, and that's enough."),
    ("Take On Me", 1985, "a-ha", ["Synthpop", "New Wave", "Norwegian"], 4, 1,
     "The song charted in three different decades and its rotoscope animation video was a technical breakthrough — the band re-recorded it four times over three years before it hit.",
     "Listen for the synth riff — it's one of the most recognizable in pop. The video's sketch-to-real transition is the song made visual: the pencil world is the synth world."),
    ("Sweet Dreams (Are Made of This)", 1983, "Eurythmics", ["Synthpop", "New Wave", "British"], 4, 1,
     "The song was built on a $20 drum machine loop and Annie Lennox's iconic video look was a last-minute decision — the band was broke and the label nearly cut them.",
     "Listen for the drum machine — it's the whole song's skeleton, and the bassline enters like a third voice. The video's gender-play is the song's real subject: identity as costume."),
    ("Video Games", 2011, "Lana Del Rey", ["Dream Pop", "Ballad", "American"], 4, 1,
     "Made on a laptop in a bedroom and uploaded to YouTube, the song's lo-fi production launched a million imitators — the vintage-film aesthetic was also homemade.",
     "Listen for the film-sound effects under the vocals — the song was literally scored like a movie. The 'heaven is a place on earth' sample is the ghost in the machine."),
    ("Somebody That I Used to Know", 2011, "Gotye", ["Indie Pop", "Art Pop", "Australian"], 4, 1,
     "The song's duet structure was inspired by a breakup, and the 'body paint' music video is one continuous shot — the artist spent years away from music after its success.",
     "Listen for the two voices — they never sing together, which IS the song. The 'now you're just somebody' line is the thesis; the video's paint makes it literal."),
    ("Hey Ya!", 2003, "OutKast", ["Funk", "Hip Hop", "American"], 4, 1,
     "André 3000 wrote a breakup song disguised as a party anthem — the band's 'shake it like a Polaroid' line is a real instruction, and the song's sadness is hidden under pure joy.",
     "Listen for the key change at the end — it's the song's confession. The funk is the mask; the lyrics are a relationship falling apart in a club."),
    ("Happy", 2013, "Pharrell Williams", ["Pop", "Soul", "American"], 4, 1,
     "The song was written for a film and rejected, then released as a single — the 24-hour music video was shot in 24 locations with real people dancing, and the claps were recorded in the studio.",
     "Listen for the claps — they're the song's heartbeat, recorded by Pharrell's own hands. The song's simplicity is the craft; there's no bridge, just joy."),
    ("Can't Stop the Feeling!", 2016, "Justin Timberlake", ["Pop", "Disco", "American"], 4, 1,
     "Written for a Trolls movie, the song's disco revival made it the biggest-selling single of 2016 — the 'happy' is engineered, which is exactly the point.",
     "Listen for the falsetto 'nothing can stop me' — it's the song's peak, and it arrives without a build. The song is pure chemical joy; the disco strings are the prescription."),
    ("Toxic", 2003, "Britney Spears", ["Dance Pop", "Electropop", "American"], 3, 1,
     "The song's strings were sampled from a Bollywood film and the 'toxic' lyric was Britney's own idea — it's considered one of the greatest pop songs ever by critics.",
     "Listen for the Bollywood strings — they're the song's secret weapon. The song's danger is in the beat; the lyrics are the warning label."),
    ("Umbrella", 2007, "Rihanna", ["Pop", "R&B", "Barbadian"], 4, 1,
     "The song was written for Britney Spears, who turned it down — Rihanna's version became her breakthrough, and the 'ella ella' hook was almost cut for being too silly.",
     "Listen for the 'ella ella' hook — it's the song's memory engine, and the beat's heartbeat is the rain. The song's promise ('under my umbrella') is the whole story."),
    ("Single Ladies (Put a Ring on It)", 2008, "Beyoncé", ["Pop", "R&B", "American"], 3, 1,
     "Beyoncé recorded it in a single day and the choreography was inspired by a 1960s dance troupe — the black-and-white video was shot in one take per angle.",
     "Watch the video and count the three dancers — the precision is the performance. The song's demand is its power: the ring is the argument."),
    ("Havana", 2017, "Camila Cabello", ["Pop", "Latin", "American"], 3, 1,
     "The song's 'Havana, ooh na-na' hook was improvised in the studio, and the video's old-movie aesthetic hides a twist — the song's Cuba longing is real, but the ending is a joke.",
     "Listen for the trumpet — it's the song's soul, played by a real session musician. The song is a love letter to a city the singer barely knew; that's the ache."),
    ("Despacito", 2017, "Luis Fonsi", ["Latin Pop", "Reggaeton", "Puerto Rican"], 4, 1,
     "The Justin Bieber remix made the Spanish-language original the most-streamed song in history — the song's 'despacito' (slowly) is both a tempo and a request.",
     "Listen to the original, not the remix — the Spanish phrasing is the song's architecture. The 'despacito' hook is the whole song in one word."),
    ("Waka Waka (This Time for Africa)", 2010, "Shakira", ["Pop", "World", "Colombian"], 3, 1,
     "Written for the 2010 World Cup, the song's chorus samples a 1980s Cameroonian hit — the dance moves in the video are real African dances.",
     "Listen for the sampled Cameroonian guitar — the song is a translation. The 'Waka Waka' hook is a real Tsonga phrase meaning 'do it do it'."),
    ("Firework", 2010, "Katy Perry", ["Pop", "Dance", "American"], 4, 1,
     "Perry wrote it after reading Jack Kerouac's On the Road — the song's 'firework' metaphor was inspired by a real comment from a fan who felt invisible.",
     "Listen for the key change before the final chorus — it's the song's ignition. The song's pep talk is engineered, but the engineering is the craft."),
    ("Born This Way", 2011, "Lady Gaga", ["Pop", "Dance", "American"], 4, 1,
     "Gaga wrote it as a direct answer to the bullying she survived in school — the song's 'born this way' became a queer anthem and the music video is a birth-to-rebirth allegory.",
     "Listen for the spoken opening — it's a sermon, not a verse. The song's radicalism is that it refuses to argue: the self is the fact."),
    ("All Too Well", 2012, "Taylor Swift", ["Country Pop", "Ballad", "American"], 5, 1,
     "The 10-minute version's release in 2021 broke records — the song's 'scarf' lyric is famously autobiographical, and the song's real subject is the memory of a memory.",
     "Listen for the scarf — it's the song's emotional anchor, and it never comes back. The song's genius is that the narrator can't stop telling the story she's telling."),
    ("Circles", 2019, "Post Malone", ["Pop Rap", "Alternative", "American"], 4, 1,
     "The song's chord progression literally circles — the title is the structure — and the chorus's falsetto was recorded in one take.",
     "Listen for the circle — the progression returns to the start, and the song never resolves. The song's trap is that you can't leave a loop you're in."),
    ("Snooze", 2022, "SZA", ["R&B", "Soul", "American"], 3, 1,
     "SZA wrote it about being so in love she can't sleep — the song's 'snooze' is both the state and the excuse, and the album it came from won Album of the Year.",
     "Listen for the falsetto 'I'll touch you in the morning' — the promise is the song's core. The production's warmth is the love; the lyrics are the anxiety."),
    ("Kill Bill", 2022, "SZA", ["R&B", "Alt R&B", "American"], 3, 1,
     "The song's revenge fantasy samples a 1980s R&B hit and the video's bridal-gore aesthetic made it a viral moment — the humor is the point, the violence is the joke.",
     "Listen for the sampled Diana Ross hook — the sweetness is the contrast. The song's confession ('I might kill my ex') is funny precisely because it's sung so gently."),
]

SERIES = [
    ("Breaking Bad", 2008, "Vince Gilligan", ["Crime", "Drama", "American"], 55, 1,
     "The entire show was planned as a 'Mr. Chips to Scarface' arc and the pilot's RV was so hot inside that the cast almost fainted — the green goo in the finale was made from actual candy.",
     "Watch episode 1 of season 1 and notice the foreshadowing in the opening flash-forward. Then track Walter's moral line — the show is about the moment he crosses it, not the meth."),
    ("The Wire", 2002, "David Simon", ["Crime", "Drama", "American"], 60, 1,
     "A former crime reporter staffed the writers' room with real cops and journalists — each season examines a different institution, and the show's title means the wiretap, not a cable.",
     "Watch the first season as an institution study, not a cop show — the drug trade is the economy, and the police are another gang. The show rewards patience; the payoffs are seasons away."),
    ("Game of Thrones", 2011, "David Benioff", ["Fantasy", "Drama", "Epic", "American"], 55, 1,
     "The pilot was so bad it was almost abandoned — the show's later seasons ran out of source material and the final season's rushed ending remains the most argued-about in TV history.",
     "Watch episode 1 and ignore the politics — follow the Stark family's faces instead. The show's real subject is power's cost; every 'win' is a loss somewhere."),
    ("The Sopranos", 1999, "David Chase", ["Crime", "Drama", "American"], 55, 1,
     "The show invented the modern prestige drama and its finale's cut-to-black is still debated — Tony's therapy sessions were the show's real 'business meetings'.",
     "Watch the pilot's therapy scenes — the show's thesis is that a mob boss is also a middle-aged man in crisis. The cut-to-black ending is a Rorschach test; form your own answer first."),
    ("Mad Men", 2007, "Matthew Weiner", ["Drama", "Period", "American"], 47, 1,
     "The show's period detail is obsessive — every product placement is era-accurate, and the actor who plays Don Draper was a soap star before the role changed TV.",
     "Watch the first season and notice what's NOT said — the show's drama is in the pauses. The pitch meetings are the action scenes; the copy is the plot."),
    ("Stranger Things", 2016, "The Duffer Brothers", ["Sci-Fi", "Horror", "Nostalgia", "American"], 50, 1,
     "The show was originally pitched as a movie and the Duffer Brothers' pitch deck was so good Netflix bought it instantly — the kids' Dungeons & Dragons game foreshadows every season's monster.",
     "Watch episode 1 and map the D&D references — each monster is a game creature the kids already know how to fight. The nostalgia is the frame; the kids are the heart."),
    ("The Crown", 2016, "Peter Morgan", ["Drama", "Historical", "British"], 58, 1,
     "The show casts three different actresses as the Queen across decades — the real palace reportedly watches it, and the writers had to invent private conversations because no one knows them.",
     "Watch season 1's episode about the Great Smog — it's the show's thesis about duty vs. humanity. The costumes are museum-accurate; the drama is invented and honest about it."),
    ("Chernobyl", 2019, "Craig Mazin", ["Drama", "Historical", "Disaster", "American"], 55, 1,
     "The show's creators consulted real scientists and the 'not great, not terrible' line is a real quote from the actual control room — the radiation burns were makeup designed by a Chernobyl survivor's family.",
     "Watch the courtroom scene in the finale — the show's real villain is not the explosion but the lie. The 'cost of lies' speech is the thesis; everything before it is evidence."),
    ("The Office (US)", 2005, "Greg Daniels", ["Comedy", "Mockumentary", "American"], 22, 1,
     "The American remake was nearly canceled after season 1 — Steve Carell's Michael Scott was rewritten to be more human, and the show's documentary crew is never explained.",
     "Watch the pilot, then episode 2 — notice how Michael changes when the writers stop making him a buffoon. The show's real subject is office loneliness disguised as a comedy."),
    ("Friends", 1994, "David Crane", ["Comedy", "Sitcom", "American"], 22, 1,
     "The show's 'Friends' is really about six actors who couldn't afford the rent in New York — the apartment's purple walls were a set decision, and the show's theme song was a last-minute replacement.",
     "Watch the pilot and notice the coffee house — the 'hangout' structure is the show. The joke density is engineered; count the laugh track and you'll see the rhythm."),
    ("Sherlock", 2010, "Steven Moffat", ["Mystery", "Crime", "British"], 90, 1,
     "The modern Sherlock's 'mind palace' visuals were inspired by the actor's own technique for memorizing lines — the show's text-message overlays were a stylistic breakthrough.",
     "Watch the first episode and try to solve the case before Sherlock does — the clues are fair. The 'mind palace' is real mnemonic technique; the show made it visible."),
    ("Fleabag", 2016, "Phoebe Waller-Bridge", ["Comedy", "Drama", "British"], 27, 1,
     "Waller-Bridge based the show on her own one-woman stage act and famously refused to do a second season until the BBC begged — the 'fourth wall' camera is the show's secret co-star.",
     "Watch for the camera glances — the narrator's asides are the real conversation. The show's tragedy is hidden in its comedy; the 'kneel' scene is the thesis."),
    ("Dark", 2017, "Baran bo Odar", ["Sci-Fi", "Mystery", "German"], 55, 1,
     "The German time-travel series has a family tree the writers drew on a literal wall — every character is related to every other character, and the show's title is also its genre.",
     "Watch the first episode with the family tree open — the relationships are the plot. The show's German is a feature, not a barrier; the dubbing loses the time-jump voice clues."),
    ("Squid Game", 2021, "Hwang Dong-hyuk", ["Thriller", "Survival", "Korean"], 55, 1,
     "The script was rejected for a decade and the director was broke when it finally filmed — the show's 'Red Light Green Light' doll is a real Korean schoolbook character.",
     "Watch the first game and notice the children's-game irony — the horror is the innocence. The show's real subject is debt; the games are the economy made literal."),
    ("Money Heist", 2017, "Álex Pina", ["Crime", "Thriller", "Spanish"], 50, 1,
     "The show's Tokyo/Nairobi voiceover was a last-minute addition and the red jumpsuits were inspired by a real heist — the series was nearly canceled after its first season on Spanish TV.",
     "Watch the first heist episode and notice the masks — the anonymity is the strategy. The show's real heist is emotional: it makes you root for the robbers."),
    ("The Mandalorian", 2019, "Jon Favreau", ["Sci-Fi", "Western", "Star Wars", "American"], 40, 1,
     "The show's 'Baby Yoda' (Grogu) was kept secret from even the cast — the puppet was operated by a team of six, and the show's Western pacing made it a cultural phenomenon.",
     "Watch the first episode's 'The Child' reveal — the moment the puppet works is the show. The show is a Western; the Mandalorian's helmet is the code."),
    ("Arcane", 2021, "Christian Linke", ["Animation", "Fantasy", "American"], 45, 1,
     "The show's painterly animation style took six years and was rendered in a custom engine — every frame is a painting, and the show's sisters' conflict is its real plot.",
     "Watch episode 1 and notice the animation style — the brushstrokes are visible. The show's 'arcane' is science vs. magic; the sisters are both right, which is the tragedy."),
    ("Ted Lasso", 2020, "Bill Lawrence", ["Comedy", "Sports", "British"], 30, 1,
     "The show was based on a TV ad for NBC's Premier League coverage — the niceness is the premise, and the show's therapy-talk actually helped viewers during the pandemic.",
     "Watch the first season and notice how the show weaponizes kindness — Ted's optimism is a strategy, not a weakness. The show's real sport is mental health."),
    ("The Bear", 2022, "Christopher Storer", ["Drama", "Comedy", "American"], 35, 1,
     "The show's kitchen scenes are shot in real-time chaos with actual chefs on set — the famous 'seven fishes' episode was filmed in one continuous take.",
     "Watch the first episode and feel the kitchen stress — the chaos is the point. The show's real dish is grief; the restaurant is the family."),
    ("Succession", 2018, "Jesse Armstrong", ["Drama", "Comedy", "American"], 60, 1,
     "The show's dialogue was written to sound like actual billionaires arguing — the 'fuck off' catchphrase came from a real boardroom transcript, and the show refused to show the characters winning.",
     "Watch the first episode and notice the power dynamics in every sentence — the show's dialogue is chess. The 'succession' is the plot; the inheritance is the poison."),
    ("The Last of Us", 2023, "Craig Mazin", ["Drama", "Horror", "American"], 55, 1,
     "The show was made with the game's creators and the infected clickers are performed by a real contortionist — the show's fungal apocalypse is based on real cordyceps research.",
     "Watch the first episode's cold open — the 1968 interview is real science. The show's horror is the loss of connection; the infected are just the excuse."),
    ("Wednesday", 2022, "Alfred Gough", ["Comedy", "Supernatural", "Mystery", "American"], 45, 1,
     "Jenna Ortega learned cello for the show and her 'Thing' hand was operated by a real puppeteer — the show's dance scene went viral after Ortega choreographed it herself.",
     "Watch the school's mystery and notice the Addams Family references — the show is a detective story wearing a goth costume. The dance scene is the thesis: Wednesday's joy is defiance."),
    ("One Piece (live-action)", 2023, "Matt Owens", ["Adventure", "Fantasy", "Japanese"], 55, 1,
     "The live-action One Piece was made with the manga's creator Eiichiro Oda on set — he reportedly rejected scripts he didn't like, and the show's Devil Fruit effects are practical, not CGI.",
     "Watch episode 1 and notice the Straw Hat promise — the show's theme is found family. The 'I'm gonna be King of the Pirates' line is a promise, and the show's joy is in the believing."),
    ("Demon Slayer: Kimetsu no Yaiba", 2019, "Haruo Sotozaki", ["Anime", "Action", "Japanese"], 24, 1,
     "The anime's episode 19 became a global phenomenon — the water-bending animation was hand-drawn with 300+ frames per second of action, and the show's demons are based on real Japanese folklore.",
     "Watch episode 19 of season 1 — it's the episode that broke the internet. The animation is the show; the story is the sword."),
    ("Cowboy Bebop", 1998, "Shinichiro Watanabe", ["Anime", "Sci-Fi", "Noir", "Japanese"], 24, 1,
     "The show was made on a shoestring and became the gateway anime for a generation — each episode is named after a real jazz song, and the show's ending is famously devastating.",
     "Watch episode 5 ('Ballad of Fallen Angels') — it's the show's thesis in one episode. The jazz is the structure; the bounty hunters are the loneliness."),
    ("Neon Genesis Evangelion", 1995, "Hideaki Anno", ["Anime", "Mecha", "Psychological", "Japanese"], 24, 1,
     "The show was made as the director's own therapy — the ending was so controversial it was redone in film form, and the 'Instrumentality' concept came from a real psychology book.",
     "Watch episode 16 and feel the shift — the show's mecha battles are a distraction from its real subject. The 'hedgehog's dilemma' is the thesis: closeness hurts, isolation kills."),
    ("Fullmetal Alchemist: Brotherhood", 2009, "Yasuhiro Irie", ["Anime", "Adventure", "Fantasy", "Japanese"], 24, 1,
     "The show follows the manga faithfully after the first anime diverged — the 'equivalent exchange' law is the series' moral system, and the ending is considered perfect by fans.",
     "Watch episode 1 and notice the law — the show's alchemy is morality made physical. The series is about what you're willing to pay; every character pays."),
    ("The Expanse", 2015, "Mark Fergus", ["Sci-Fi", "Drama", "American"], 45, 1,
     "The show's physics are accurate — ships spin for gravity, no sound in space, and the 'flip and burn' maneuvers are real orbital mechanics. The authors wrote the books with a physicist.",
     "Watch the first episode's spacewalk — the physics is the show's signature. The Belters' dialect is a constructed language; listen for 'innit' and 'sa sa'."),
    ("Peaky Blinders", 2013, "Steven Knight", ["Crime", "Period", "British"], 60, 1,
     "The show's haircuts and razor-blade caps are based on real Birmingham gang history — the anachronistic music (Nick Cave, Radiohead) was a deliberate style choice.",
     "Watch the first episode and notice the anachronistic soundtrack — the show is punk dressed as period. The 'peaky blinders' are the hats; the family is the razor."),
    ("Bridgerton", 2020, "Chris Van Dusen", ["Romance", "Period", "American"], 60, 1,
     "The show's Regency setting with modern music and diverse casting made it Netflix's most-watched original — the string covers of pop songs are the show's signature.",
     "Listen for the string covers — the modern songs in Regency dress are the show's thesis. The gossip is the plot; the scandal is the economy."),
    ("True Detective", 2014, "Nic Pizzolatto", ["Crime", "Mystery", "American"], 60, 1,
     "Season 1's tracking shot was filmed in one continuous take with the actors walking six minutes straight — the show's occult framing was inspired by real Louisiana cult legends.",
     "Watch the season 1 finale's tracking shot — it's the show's signature. The 'time is a flat circle' speech is the thesis; the show's real crime is the past."),
    ("Mindhunter", 2017, "David Fincher", ["Crime", "Drama", "American"], 55, 1,
     "Fincher's show about the FBI's serial-killer profiling unit was made from real interviews — the show's interviews are performed by actors who studied the real killers' tapes.",
     "Watch the first interview — the profiling is the show. The 'interviews are the action' structure is Fincher's point: talk is the plot."),
    ("House M.D.", 2004, "David Shore", ["Drama", "Medical", "American"], 45, 1,
     "The show's 'House' was based on Sherlock Holmes — the morphine and the violin are direct references, and each episode's diagnosis is a mystery structure.",
     "Watch the first episode and notice the misdiagnosis — every episode is a locked-room mystery. House's 'everybody lies' is the thesis; the puzzle is the medicine."),
    ("The Office (UK)", 2001, "Ricky Gervais", ["Comedy", "Mockumentary", "British"], 30, 1,
     "The original Office invented the mockumentary sitcom and ran only 12 episodes plus a special — Gervais's David Brent was based on real bosses he'd known.",
     "Watch the first episode and notice the silence — the comedy is in the awkward pause. The UK version ends the show; the US version kept it going."),
    ("It's Always Sunny in Philadelphia", 2005, "Rob McElhenney", ["Comedy", "Dark Comedy", "American"], 22, 1,
     "The show was made on a $200 budget and is now the longest-running live-action sitcom in US history — the gang's 'trash person' morality is the joke.",
     "Watch the pilot and notice the budget — the show's genius is that it never got nice. The gang's selfishness is the premise; the comedy is the consequence."),
    ("Community", 2009, "Dan Harmon", ["Comedy", "Meta", "American"], 22, 1,
     "The show's creator used his own 'story circle' theory to write every episode — the paintball and D&D episodes are tributes to genre films, and the show predicted its own fandom.",
     "Watch the first paintball episode — it's a Western, a heist film and a sitcom at once. The show's meta-commentary is the point; the community college is the country."),
    ("Rick and Morty", 2013, "Dan Harmon", ["Animation", "Sci-Fi", "Comedy", "American"], 22, 1,
     "The show was based on a Back to the Future parody and its nihilism is the argument — the 'Szechuan sauce' episode started a real fast-food craze.",
     "Watch the first episode and notice the two-structure — Rick's adventure and Morty's adventure are the same story. The show's nihilism is the mask; the family is the heart."),
    ("Attack on Titan (anime)", 2013, "Tetsurō Araki", ["Anime", "Dark Fantasy", "Japanese"], 24, 1,
     "The anime's opening theme and 3D maneuvering gear animation were breakthroughs — the show's later reveals reframe the first episode entirely.",
     "Watch episode 1, then rewatch it after finishing the series — the basement reveal changes the whole frame. The show's real enemy is never the Titans."),
    ("The Witcher", 2019, "Lauren Schmidt Hissrich", ["Fantasy", "Action", "American"], 55, 1,
     "The show's timelines confused viewers until the finale revealed three separate time periods — the 'Law of Surprise' is a real Slavic folklore concept.",
     "Watch episode 1 and note the timeline — the show's nonlinear structure is intentional. The 'Law of Surprise' is the plot engine; destiny is the currency."),
    ("Severance", 2022, "Dan Erickson", ["Sci-Fi", "Thriller", "American"], 50, 1,
     "The show's office aesthetic was inspired by real corporate campuses and the 'innie/outie' split is a genuine philosophical question — the show's elevator transition is its signature shot.",
     "Watch the first episode's elevator scene — the split is the show. The 'work-life balance' is taken literally; the horror is the office."),
    ("Better Call Saul", 2015, "Vince Gilligan", ["Crime", "Drama", "American"], 50, 1,
     "The Breaking Bad prequel is considered by many to be better than the original — the show's slow-burn season 6 finale recontextualizes everything.",
     "Watch the first season and notice the legal detail — the show's 'lawyer stuff' is the drama. The transformation of Jimmy to Saul is the arc; the final black-and-white episode is the thesis."),
    ("Baby Reindeer", 2024, "Richard Gadd", ["Drama", "Thriller", "British"], 40, 1,
     "The show is a true story adapted from the creator's own one-man show — the real stalker's emails are quoted, and the show's 'truth' framing is its power.",
     "Watch the first episode and notice the 'true story' opening — the show's confession is the drama. The stalker is the mirror; the real subject is the narrator."),
    ("Fallout", 2024, "Graham Wagner", ["Sci-Fi", "Dark Comedy", "American"], 50, 1,
     "The show was made with the game's creators and the wasteland's practical sets are real — the show's tone (comedy + horror) is the game's signature.",
     "Watch the first episode and notice the tone shifts — the show's humor is the armor. The vault experiment is the plot; the wasteland is the character."),
    ("Avatar: The Last Airbender", 2005, "Michael Dante DiMartino", ["Animation", "Fantasy", "Adventure", "American"], 24, 1,
     "The show's bending styles were based on real martial arts — water is tai chi, earth is hung gar, fire is northern shaolin — and the show's villains were written to be sympathetic.",
     "Watch episode 1 and notice the bending styles — each element is a real martial art. The show's 'balance' theme is the thesis; the villains are the arguments."),
]

def _slug(text):
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "topic"


def _build(file_name, category_id, subtype, verb, rows):
    path = ASSETS / file_name
    existing = json.loads(path.read_text(encoding="utf-8")) if path.exists() else []
    existing_ids = {t["id"] for t in existing}
    seen_names = {t["name"] for t in existing}
    added = 0
    for (name, year, creator, tags, duration, tier, teaser, instruction) in rows:
        display = f"{name} ({year})" if year else name
        if display in seen_names:
            continue
        base = f"{subtype.lower()}-{_slug(name)}"
        tid = base
        n = 2
        while tid in existing_ids:
            tid = f"{base}-{n}"
            n += 1
        existing_ids.add(tid)
        seen_names.add(display)
        full_tags = list(tags)
        if year and not any(t.endswith("s") and t[:-1].isdigit() for t in full_tags):
            full_tags.append(f"{year // 10 * 10}s")
        existing.append({
            "id": tid,
            "categoryId": category_id,
            "subtype": subtype,
            "name": display,
            "teaser": teaser,
            "imageUrl": "",
            "byline": creator,
            "exploreAction": {
                "verb": verb,
                "targetName": f"{name} ({year})" if year else name,
                "durationMinutes": duration if duration else 45,
                "instruction": instruction,
            },
            "tags": full_tags,
            "tier": tier,
        })
        added += 1
    path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{file_name}: +{added} (total {len(existing)})")


def main():
    _build("songs.json", "SONGS", "Song", "Listen", SONGS)
    _build("series.json", "SERIES", "Series", "Watch", SERIES)


if __name__ == "__main__":
    main()
