#!/usr/bin/env python3
"""batch_comics_topup.py — second drop for the Anime / Manga / Manhwa lanes.

Same schema + quality bar as batch_anime_comics.py; idempotent (skips ids
and names that already exist in each file). Pulls each lane to ~60 topics.

Usage: python3 scripts/batch_comics_topup.py && python3 scripts/validate_topics.py
"""

import json
import re
import unicodedata
from pathlib import Path

ASSETS = Path("app/src/main/assets/topics")

ANIME = [
    ("Neon Genesis Evangelion", 1995, "Gainax", ["Mecha", "Psychological", "Drama"], 24 * 24, 1,
     "Hideaki Anno wrote the final episodes while clinically depressed and it shows — the last two episodes are almost entirely inner monologue over still frames, and fans have argued about the ending for three decades.",
     "Watch to episode 16 first — that's when the show stops being a monster-of-the-week mecha and becomes what it is. Pay attention to the sync test early on: the machine is a metaphor from the first episode."),
    ("Cowboy Bebop", 1998, "Sunrise", ["Space Western", "Noir", "Jazz"], 26 * 24, 1,
     "The entire soundtrack was composed BEFORE the animation — the show was cut to the music, not scored to the show. The opening theme 'Tank!' is a jazz standard played at a tempo no band can hold live.",
     "Watch the first episode with the sound up — the fight scenes are choreographed to the music. Notice how each episode's title references a real song; the jazz references are the subtext."),
    ("Steins;Gate", 2011, "White Fox", ["Sci-Fi", "Thriller", "Drama"], 24 * 24, 1,
     "The time-travel rules in Steins;Gate are internally consistent enough that fans have built actual databases of its world lines — and the 'El Psy Kongroo' catchphrase is a real cipher.",
     "Watch the first 12 episodes as setup — the show's first half is deliberately confusing so the second half lands. Track every D-mail sent: each one creates a world line you can trace."),
    ("Fullmetal Alchemist: Brotherhood", 2009, "Bones", ["Action", "Fantasy", "Drama"], 64 * 24, 1,
     "The 2009 remake follows the manga's true ending, which the 2003 anime invented — and the manga's author planned the 'truth' scene (the one with the doorway) from her first chapter.",
     "Watch the first episode and notice the flashback structure — the brothers' backstory is shown in fragments on purpose. The 'equivalent exchange' law is broken by the end; track when."),
    ("Mob Psycho 100", 2016, "Bones", ["Action", "Comedy", "Supernatural"], 12 * 24, 1,
     "ONE (One Punch Man's author) draws deliberately ugly art — the anime kept the stick-figure look and it became the point: Mob's psychic power visually breaks the frame when he loses control.",
     "Watch the '???%' moments and notice the art shift — when Mob's percentage hits 100, the animation style literally changes. The show's thesis is that emotional control is the real power."),
    ("One Punch Man", 2015, "Madhouse", ["Action", "Comedy", "Superhero"], 12 * 24, 1,
     "The webcomic started as a doodle site joke about a hero who wins instantly — the anime's budget blew up the joke into the best animated fight scenes of the decade.",
     "Watch the first season's final fight and notice the detail — the animation studio put an entire film's budget into one episode. The show's satire is that Saitama's boredom IS the joke."),
    ("Spy x Family", 2022, "Wit Studio", ["Comedy", "Action", "Family"], 12 * 24, 1,
     "The fake family premise was rejected by editors as too absurd — it became one of the best-selling manga of the decade, and the 'any mission' catchphrase is a real spy technique reference.",
     "Watch the first episode and notice the three lies — the spy, the assassin and the telepath all hide their true selves. The show's genius is that the lies become the truth."),
    ("Bocchi the Rock!", 2022, "CloverWorks", ["Comedy", "Music", "Slice of Life"], 12 * 24, 1,
     "The anime's animation budget went into a girl playing guitar alone in a closet — the show's visuals (including the famous 'paper cutout' panic moments) made it the most-discussed anime of its season.",
     "Watch the first episode's concert scene — Bocchi's guitar is the only thing that works. The show's animation style literally breaks when she panics; that's the point."),
    ("K-On!", 2009, "Kyoto Animation", ["Comedy", "Music", "Slice of Life"], 13 * 24, 1,
     "The tea-drinking club anime that spawned the 'cute girls doing cute things' genre — the show's real subject is that high school friendship is finite, and the ending is a quiet gut-punch.",
     "Watch the final episode's concert — the song is about the thing they're losing. The show's genius is that nothing dramatic happens; that's why it lands."),
    ("Anohana: The Flower We Saw That Day", 2011, "A-1 Pictures", ["Drama", "Supernatural", "Slice of Life"], 11 * 24, 1,
     "The entire show is one question: how does a friend group grieve together? The ghost of Meiko (the 'Menma' of the title) only appears to one of them, and the show never explains why.",
     "Watch the first episode and notice the flower symbolism — the blue flower in the title appears throughout. The show's ending is designed to make you cry; the 'secret base' song is the trigger."),
    ("Your Lie in April", 2014, "A-1 Pictures", ["Drama", "Music", "Romance"], 22 * 24, 1,
     "The piano pieces in the show are real classical performances — the animation team storyboarded each performance to the actual sheet music, and the 'lie' of the title is the show's structural secret.",
     "Watch the first performance and notice the color — when the girl plays, the world turns colorful. The show's music is the plot; the April of the title is a promise."),
    ("March Comes in Like a Lion", 2016, "Shaft", ["Drama", "Slice of Life", "Psychological"], 22 * 24, 1,
     "The shogi anime about depression — the show's visual metaphor is that the protagonist's loneliness is rendered as space, and the three sisters' family scenes are the only warm place in the frame.",
     "Watch the first episode and notice the emptiness — the protagonist's apartment is drawn as negative space. The show's thesis is that loneliness is a skill that can be unlearned; the shogi is secondary."),
    ("Ping Pong the Animation", 2014, "Tatsunoko", ["Sports", "Psychological", "Drama"], 11 * 24, 1,
     "Directed by Masaaki Yuasa, who drew the show in a deliberately rough style — the ping pong matches are animated like dance, and the show's thesis is that talent without heart loses.",
     "Watch the first match and notice the art shift — each player is drawn with their own visual language. The show's real subject is the fear of being average; the matches are therapy."),
    ("Monster", 2004, "Madhouse", ["Thriller", "Psychological", "Mystery"], 74 * 24, 1,
     "Naoki Urasawa's manga adaptation about a doctor who saves a boy who becomes a monster — the anime keeps the manga's German street detail, and the show's real question is whether evil is chosen.",
     "Watch the first episode's cold open — the hospital scene sets up the entire moral question. The show's genius is that the monster is never confirmed evil; you decide."),
    ("Paranoia Agent", 2004, "Madhouse", ["Psychological", "Thriller", "Surreal"], 13 * 24, 1,
     "Satoshi Kon's only TV series — the 'Shonen Bat' attacker is a metaphor for the pressure to perform, and the show's final episode reveals the attack is a mass delusion.",
     "Watch the first episode and notice the unreliable narrator — the show's perspective shifts are the plot. The 'bat boy' is never real; the show's genius is that the delusion IS the villain."),
    ("Serial Experiments Lain", 1998, "Triangle Staff", ["Cyberpunk", "Psychological", "Philosophical"], 13 * 24, 1,
     "Made before the internet was ubiquitous, the show predicted social media anxiety — Lain's 'wired' world is a proto-internet, and the show's famous line 'I'm Lain' is a meditation on identity.",
     "Watch the first episode and notice the reality shifts — Lain's world subtly changes each scene. The show's thesis is that the self is a fiction we choose to maintain; the interface is the point."),
    ("Psycho-Pass", 2012, "Production I.G", ["Cyberpunk", "Thriller", "Dystopian"], 22 * 24, 1,
     "Written by Gen Urobuchi (Madoka Magica), the show's 'Sybil System' — a government AI that judges criminal intent — was inspired by real predictive policing debates in Japan.",
     "Watch the first episode and notice the system's blind spot — the show introduces it as infallible and spends the season finding the crack. The 'crime coefficient' is the show's real villain."),
    ("Puella Magi Madoka Magica", 2011, "Shaft", ["Dark Fantasy", "Psychological", "Drama"], 12 * 24, 1,
     "The 'cute magical girl' show that deconstructed the genre — the third episode's ending is considered the most shocking twist in anime history, and the show's final episode was delayed by the 2011 earthquake.",
     "Watch the first two episodes expecting a kids' show — the third episode is the trap. The show's genius is that the magical girl contract is a metaphor for adult responsibility; the 'grief seed' is the cost."),
    ("Fate/Zero", 2011, "Ufotable", ["Action", "Dark Fantasy", "Drama"], 25 * 24, 1,
     "The prequel to Fate/stay night written by Gen Urobuchi — the Holy Grail War's real prize is a wish, and the show's thesis is that heroism and monstrosity are the same force.",
     "Watch the first episode's prologue and notice the framing — the war is introduced as a legend. The show's genius is that every master is a kind of monster; the 'ideal' hero is the scariest one."),
    ("Dr. Stone", 2019, "TMS", ["Sci-Fi", "Adventure", "Comedy"], 24 * 24, 1,
     "The stone-age science anime — every experiment in the show is real and reproducible, and the author actually consulted chemists and engineers. The 'science is the hero' framing is the point.",
     "Watch the first episode and notice the science accuracy — the stone world's re-invention of soap, gunpowder and glass follows real history. The show's thesis is that knowledge is the only permanent resource."),
    ("That Time I Got Reincarnated as a Slime", 2018, "8bit", ["Fantasy", "Isekai", "Comedy"], 24 * 24, 1,
     "The isekai that flipped the genre — the protagonist is a literal slime, and the show's real subject is nation-building, not fighting. The 'predator' skill is a video game mechanic made literal.",
     "Watch the first episode and notice the tone — this isekai has no love interest and no harem; it's a management sim. The show's genius is that the 'monster nation' arc is about diplomacy."),
    ("Re:Zero", 2016, "White Fox", ["Isekai", "Psychological", "Thriller"], 25 * 24, 1,
     "The isekai where the protagonist's power is dying and rewinding — the show's horror is that the 'cheat' is a curse, and the famous 'return by death' rule is a literal trauma loop.",
     "Watch the first arc and notice the time loop rules — each reset costs something. The show's genius is that the protagonist's suffering is the price of knowledge; the 'save point' is the horror."),
    ("Konosuba: God's Blessing on This Wonderful World!", 2016, "Studio Deen", ["Comedy", "Isekai", "Fantasy"], 10 * 24, 1,
     "The isekai parody that made the genre laugh at itself — the protagonist's party is a useless goddess, a masochistic crusader and a loli mage who only casts one spell, and the show's comedy is the plot.",
     "Watch the first episode and notice the character design — each party member is a joke about the genre. The show's genius is that the 'useless' party wins anyway, because competence is overrated."),
    ("Mushoku Tensei: Jobless Reincarnation", 2021, "Studio Bind", ["Isekai", "Drama", "Adventure"], 23 * 24, 1,
     "The isekai that treats reincarnation as a serious second chance — the show's animation budget was unprecedented for a TV anime, and the protagonist's growth arc is the actual plot.",
     "Watch the first episode and notice the worldbuilding detail — the magic system and the fantasy world are internally consistent. The show's genius is that the reincarnation is a therapy premise."),
    ("Hunter x Hunter (2011)", 2011, "Madhouse", ["Adventure", "Strategy", "Action"], 148 * 24, 1,
     "The 2011 remake fixed the original's filler — the Chimera Ant arc in this version is considered the pinnacle of shonen storytelling, and the nen system is the most analyzed power system in manga.",
     "Watch the Chimera Ant arc and notice the villain's humanity — the ants are more human than the hunters. The show's genius is that the power system rewards planning over power."),
    ("Gintama (TV)", 2006, "Sunrise", ["Comedy", "Action", "Historical"], 201 * 24, 1,
     "The samurai comedy about an Edo occupied by aliens — the show's jokes are so absurd that its serious arcs hit harder, and the 'Shogun Assassination' arc is considered the show's peak.",
     "Watch the first few episodes expecting absurdity — the show's structure is joke → joke → devastating arc. The genius is that the comedy is armor; the serious arcs are the wound."),
    ("Jujutsu Kaisen (TV)", 2020, "MAPPA", ["Action", "Supernatural", "Dark Fantasy"], 24 * 24, 1,
     "The anime adaptation that turned the manga into a phenomenon — the 'Shibuya Incident' arc's animation is considered the decade's best, and the show's power system (cursed energy) is explained with classroom logic.",
     "Watch the first episode's fight and notice the animation style — MAPPA's ink-work is the signature. The show's genius is that the villains are more interesting than the heroes; the 'curse' is society."),
    ("Demon Slayer (TV)", 2019, "Ufotable", ["Action", "Historical", "Dark Fantasy"], 26 * 24, 1,
     "Episode 19's fight animation broke the internet — the studio's 3D-watercolor compositing made it the most-discussed episode of the decade, and the show's kindness (mourning demons) is its secret.",
     "Watch episode 19 and notice the watercolor compositing — the fire and water effects are painted, not animated. The show's genius is that the demons are mourned as humans."),
    ("Chainsaw Man (TV)", 2022, "MAPPA", ["Action", "Dark Comedy", "Horror"], 12 * 24, 1,
     "The anime's production was so chaotic it spawned a documentary — MAPPA gave each episode a different director, and the show's filmic framing (it's edited like a movie) is the signature.",
     "Watch the first episode and notice the film references — the pacing is Tarantino, the horror is Cronenberg. The show's genius is that the chainsaw sounds are drawn, not written."),
    ("Vinland Saga (TV)", 2019, "Wit Studio", ["Historical", "Drama", "Action"], 24 * 24, 1,
     "The anime adaptation of the Viking manga about pacifism — the farm arc, where the warrior becomes a farmer, is the point of the whole story, and the show's violence exists to make the peace meaningful.",
     "Watch the first season's violence and understand why it's necessary — the show is setting up the pacifist arc. The genius is that the farm arc is the ending the violence earns."),
    ("The Promised Neverland (TV)", 2019, "CloverWorks", ["Thriller", "Mystery", "Horror"], 12 * 24, 1,
     "The first season is a perfect escape puzzle — every rule is seeded in the first episodes, and the 'children in an orphanage' premise hides the show's real horror.",
     "Watch the first episode and try to solve the escape yourself — the rules are fair. The show's genius is that the horror is the system, not the monsters."),
    ("Haikyuu!! (TV)", 2014, "Production I.G", ["Sports", "Coming of Age", "Volleyball"], 25 * 24, 1,
     "The volleyball anime with correct physics — the rallies are choreographed so you can follow the ball's trajectory, and the 'low height' protagonist is the show's thesis about limits.",
     "Watch the first match and track the ball — every pass is drawn with correct physics. The show's genius is that height is a metaphor; the 'short' protagonist is the point."),
    ("Attack on Titan (TV)", 2013, "Wit Studio", ["Dark Fantasy", "Action", "Dystopian"], 25 * 24, 1,
     "The anime's first season opening theme was so popular it charted in real music charts, and the show's 'walls' metaphor — freedom vs. safety — is the entire plot.",
     "Watch the first episode and notice the foreshadowing — the wall's height and the Titans' smiles are set up early. The show's genius is that the monsters are never just monsters."),
    ("Death Note (TV)", 2006, "Madhouse", ["Thriller", "Psychological", "Mystery"], 37 * 24, 1,
     "The anime adaptation that made the manga global — the 'L vs Light' mind games are the plot, and the show's famous potato chip scene is a masterclass in editing.",
     "Watch the first episode and notice the rule-setting — every Death Note rule exists to make the game fair. The show's genius is that Light stops being the hero earlier than you think."),
    ("Naruto (TV)", 2002, "Studio Pierrot", ["Action", "Shonen", "Ninja"], 220 * 24, 1,
     "The anime that globalized shonen — the 'Sasuke retrieval arc' at the end of part 1 is considered the show's peak, and the soundtrack's 'Sadness and Sorrow' is the most recognizable anime melody.",
     "Watch the Zabuza arc and notice the tone shift — the show stops being a kids' cartoon there. The genius is that the villains are all mirrors of the heroes."),
    ("Bleach (TV)", 2004, "Studio Pierrot", ["Action", "Supernatural", "Shonen"], 366 * 24, 1,
     "The anime's 'Soul Society arc' is considered one of the best shonen arcs ever — the show's sword designs (zanpakuto) each tell the owner's character, and the final arc's 2022 revival was a comeback story.",
     "Watch the Soul Society arc and notice the sword symbolism — each zanpakuto's name is the owner's character. The show's genius is that the fights are conversations."),
    ("Dragon Ball Z", 1989, "Toei Animation", ["Action", "Shonen", "Adventure"], 291 * 24, 1,
     "The anime that defined the action genre — the 'Frieza fight' lasted episodes because the manga was still running, and the show's power levels became a global meme.",
     "Watch the Frieza fight and notice the pacing — the anime stretched the manga's minutes into episodes. The genius is that the 'battle on Namek' is a countdown structure."),
    ("My Hero Academia (TV)", 2016, "Bones", ["Action", "Superhero", "Shonen"], 25 * 24, 1,
     "The anime adaptation of the superhero manga — the Sports Festival arc is the show's thesis on what makes a hero when powers are unfair, and the animation studio Bones gave the fights film budgets.",
     "Watch the Sports Festival arc and notice the strategy — Deku wins by understanding others' powers. The show's genius is that the 'quirkless' hero is the point."),
    ("Frieren: Beyond Journey's End (TV)", 2023, "Madhouse", ["Fantasy", "Drama", "Slice of Life"], 28 * 24, 1,
     "The anime adaptation of the post-adventure manga — the show's pacing is deliberate, and the 'time passes' editing (decades in a page) is the signature. The magic system runs on belief.",
     "Watch the first episode and notice the time-skips — the show's thesis is that memory is the real magic. The genius is that the adventure is already over; the journey is grief."),
]

MANGA = [
    ("Akira", 1982, "Katsuhiro Otomo", ["Cyberpunk", "Action", "Sci-Fi"], 0, 1,
     "Otomo's manga took 10 years to draw and required him to redraw the ending after the anime — the manga's 'Neo-Tokyo' is a warning about the atomic age, and the 'AKIRA' prophecy is the plot.",
     "Read the first volume and notice the motorcycle geometry — the slide is drawn frame-by-frame. The manga's genius is that the bike is the story's first character."),
    ("Ghost in the Shell", 1989, "Masamune Shirow", ["Cyberpunk", "Philosophical", "Sci-Fi"], 0, 1,
     "Shirow's manga is denser and more philosophical than the anime — the 'ghost' (soul) vs 'shell' (body) question is the plot, and the manga's sex scenes were censored in Western editions.",
     "Read the first volume and notice the philosophy — the 'ghost' question is the plot, not the action. The manga's genius is that the cyborg is the reader."),
    ("Gantz", 2000, "Hiroya Oku", ["Sci-Fi", "Action", "Gore"], 0, 1,
     "The manga that made shock-value mainstream — the 'Gantz' sphere forces dead people to fight aliens, and the manga's real subject is the value of a human life measured in points.",
     "Read the first volume and notice the rules — the Gantz ball's point system is the plot. The manga's genius is that the 'score' is the horror."),
    ("Tokyo Ghoul", 2011, "Sui Ishida", ["Dark Fantasy", "Horror", "Psychological"], 0, 1,
     "Ishida's debut manga about a half-ghoul — the 'CCG' (Ghoul Investigators) is a commentary on state violence, and the manga's art style shifts with the protagonist's identity crisis.",
     "Read the first volume and notice the identity question — Kaneki is neither human nor ghoul. The manga's genius is that the 'mask' is the character."),
    ("Parasyte", 1989, "Hitoshi Iwaaki", ["Horror", "Sci-Fi", "Psychological"], 0, 1,
     "The manga about an alien parasite that fails to take over its host's brain — the show's thesis is that humanity is the parasite, and the 'parasite in the right hand' is a literal metaphor.",
     "Read the first volume and notice the hand — the parasite in Migi's right hand is the co-protagonist. The manga's genius is that the alien is more human than the humans."),
    ("Pluto", 2003, "Naoki Urasawa", ["Mystery", "Sci-Fi", "Thriller"], 0, 1,
     "Urasawa's reimagining of Astro Boy's 'The Greatest Robot on Earth' — the manga asks what makes a robot a person, and the 'Pluto' of the title is a robot who can't cry.",
     "Read the first volume and notice the robot rights question — the murder mystery is a human rights story. The manga's genius is that the killer is the most human character."),
    ("20th Century Boys", 1999, "Naoki Urasawa", ["Mystery", "Thriller", "Sci-Fi"], 0, 1,
     "The 'Friend' cult conspiracy manga — the childhood memory of a symbol becomes the end of the world, and the manga's genius is that the villain is a childhood friend you can't remember.",
     "Read the first volume and notice the symbol — the 'Friend' mark is the plot. The manga's genius is that the mystery is about memory."),
    ("Billy Bat", 2008, "Naoki Urasawa", ["Mystery", "Thriller", "Alternate History"], 0, 1,
     "The manga about a comic book character who may be real — the 'Billy Bat' is a bat that appears throughout history, and the manga's genius is that the fictional character is the anchor.",
     "Read the first volume and notice the bat — the symbol appears in every era. The manga's genius is that the comic is the key."),
    ("Berserk (Vol 1)", 1989, "Kentaro Miura", ["Dark Fantasy", "Horror", "Tragedy"], 0, 1,
     "The manga's first volume is the 'Black Swordsman' arc — it's deliberately edgy and rough; the manga doesn't find its voice until the Golden Age arc, where the tragedy is earned.",
     "Read the first volume and notice the tone — it's a grindhouse fantasy that gets deeper. The manga's genius is that the Eclipse is the center; everything before is setup."),
    ("Vagabond (Vol 1)", 1998, "Takehiko Inoue", ["Historical", "Martial Arts", "Drama"], 0, 1,
     "Inoue paused the manga to study ink painting — the first volume's sword fights are already masterworks, and the 'way of the sword' is the plot.",
     "Read the first volume and notice the inkwork — the fights are drawn with brush strokes. The manga's genius is that the real battle is Musashi's inner one."),
    ("Kingdom (Vol 1)", 2006, "Yasuhisa Hara", ["Historical", "War", "Strategy"], 0, 1,
     "The unification-of-China epic — the battle formations are drawn from real Chinese war history, and the manga's thesis is that history is made by the forgotten.",
     "Read the first volume and notice the formations — the strategy is real. The manga's genius is that the slave protagonist is the 'forgotten' history."),
    ("Slam Dunk (Vol 1)", 1990, "Takehiko Inoue", ["Sports", "Coming of Age", "Basketball"], 0, 1,
     "The basketball manga that sparked a real basketball boom in Japan — the first volume is comedy about a delinquent who joins the team for a girl.",
     "Read the first volume and notice the comedy — Sakuragi is a joke who becomes real. The manga's genius is that the fundamentals arc is the drama."),
    ("GTO: Great Teacher Onizuka", 1997, "Tohru Fujisawa", ["Comedy", "Drama", "School"], 0, 1,
     "The ex-delinquent teacher manga — Onizuka's teaching method is 'win them over by being more delinquent', and the manga's real subject is how adults fail children.",
     "Read the first volume and notice the teaching method — Onizuka solves problems by joining them. The manga's genius is that the teacher is the student."),
    ("Rurouni Kenshin", 1994, "Nobuhiro Watsuki", ["Historical", "Action", "Samurai"], 0, 1,
     "The wandering-samurai manga about a killer who swore off killing — the 'reverse blade' sword is the thesis: strength without killing.",
     "Read the first volume and notice the reverse blade — the sword is the character. The manga's genius is that the redemption arc is the plot."),
    ("Rurouni Kenshin: Trust & Betrayal", 1999, "Nobuhiro Watsuki", ["Historical", "Drama", "Tragedy"], 0, 1,
     "The prequel OVA that shows the 'Battousai' the main series only references — the ending is considered one of the most devastating in anime history.",
     "Watch the first episode and notice the tone — it's a tragedy before the comedy. The OVA's genius is that the killer's past is the main series' shadow."),
    ("Kenshin: The Legend Ends", 1999, "Nobuhiro Watsuki", ["Historical", "Action", "Drama"], 0, 1,
     "The trilogy's conclusion — the 'Enishi' arc resolves the Battousai's past, and the manga's genius is that the villain is the protagonist's mirror.",
     "Read the Enishi arc and notice the mirror — the villain is Kenshin's past. The manga's genius is that the 'legend' ends with a choice."),
    ("20th Century Boys (Vol 2)", 1999, "Naoki Urasawa", ["Mystery", "Thriller", "Sci-Fi"], 0, 1,
     "The conspiracy deepens — the childhood friends realize the 'Friend' was in their group, and the manga's genius is that the villain is a memory.",
     "Read the second volume and notice the suspects — every childhood friend is a candidate. The manga's genius is that the mystery is about trust."),
    ("Berserk: Golden Age Arc", 1990, "Kentaro Miura", ["Dark Fantasy", "Tragedy", "Action"], 0, 1,
     "The arc that made Berserk a masterpiece — the Eclipse is considered the darkest moment in manga, and the arc's genius is that the tragedy is earned by the friendship it destroys.",
     "Read the Golden Age arc slowly — the horror is earned by the trust. The manga's genius is that the brand is the price."),
    ("Vagabond: The Duel", 1998, "Takehiko Inoue", ["Historical", "Martial Arts", "Drama"], 0, 1,
     "The 'Musashi vs Kojiro' duel that Inoue spent years on — the fight is drawn as a meditation, and the manga's genius is that the duel is internal.",
     "Read the duel and notice the stillness — the fight is a meditation. The manga's genius is that the swords are the characters."),
    ("One Punch Man (Manga)", 2015, "ONE / Yusuke Murata", ["Action", "Comedy", "Superhero"], 0, 1,
     "The webcomic's re-draw by Murata is considered the best-drawn manga of its generation — the art quality is film-level, and the story's satire is in the 'S-class' ranking system.",
     "Read the first volume and notice the art — Murata's detail is the selling point. The manga's genius is that the joke is the plot."),
    ("Goodnight Punpun (Vol 2)", 2007, "Inio Asano", ["Drama", "Psychological", "Coming of Age"], 0, 1,
     "The second volume follows Punpun through adolescence — the bird-doodle design stays, and the manga's genius is that the crude bird is how he sees himself.",
     "Read the second volume and notice the bird — the doodle is the self-image. The manga's genius is that the realism around him is the contrast."),
    ("Solanin", 2005, "Inio Asano", ["Drama", "Slice of Life", "Music"], 0, 1,
     "The manga about a post-grad couple who decide to quit their jobs — the 'Solanin' of the title is a flower that blooms in ruins, and the manga's genius is that the mundane IS the drama.",
     "Read the first volume and notice the quiet — nothing dramatic happens. The manga's genius is that the decision to quit is the climax."),
    ("Nijigahara Holograph", 2003, "Inio Asano", ["Psychological", "Mystery", "Horror"], 0, 1,
     "Asano's most cryptic work — a town's collective trauma told in disconnected fragments, and the manga's genius is that the 'holograph' is the memory.",
     "Read it twice — the fragments connect on the second pass. The manga's genius is that the timeline is a spiral."),
    ("The Summit of the Gods", 2000, "Jiro Taniguchi", ["Adventure", "Drama", "Mountain"], 0, 1,
     "The mountaineering manga about the mystery of George Mallory's disappearance — Taniguchi's art is photorealistic, and the manga's genius is that the climb is the character.",
     "Read the first volume and notice the art — the mountains are real. The manga's genius is that the obsession is the plot."),
    ("A Distant Neighborhood", 1998, "Jiro Taniguchi", ["Drama", "Slice of Life", "Time Travel"], 0, 1,
     "A middle-aged man time-travels to his teenage self — the manga's genius is that the nostalgia is the plot, and Taniguchi's quiet art makes the ache visible.",
     "Read the first volume and notice the pacing — the time travel is subtle. The manga's genius is that the past is a place you visit, not change."),
    ("Buddha", 1972, "Osamu Tezuka", ["Historical", "Biography", "Spiritual"], 0, 1,
     "Tezuka's 8-volume biography of Siddhartha — the 'God of Manga' drew the Buddha with flaws, and the manga's genius is that enlightenment is a process.",
     "Read the first volume and notice the humanity — the Buddha is not divine yet. The manga's genius is that the path is the story."),
    ("Phoenix", 1967, "Osamu Tezuka", ["Sci-Fi", "Philosophical", "Epic"], 0, 1,
     "Tezuka's unfinished magnum opus — each volume is set in a different era and connected by the immortal Phoenix, and the manga's genius is that the bird is the reader.",
     "Read the first volume and notice the eras — each story is a cycle. The manga's genius is that the Phoenix is immortality itself."),
    ("Astro Boy", 1952, "Osamu Tezuka", ["Sci-Fi", "Adventure", "Classic"], 0, 1,
     "The manga that created modern anime — Tezuka's robot boy was the first manga to have a serialized anime adaptation, and the 'Pinocchio with a heart' premise is the genre's foundation.",
     "Read the first volume and notice the innocence — the robot boy's kindness is the thesis. The manga's genius is that the machine is the most human."),
    ("Dragon Ball (Vol 1)", 1984, "Akira Toriyama", ["Action", "Adventure", "Shonen"], 0, 1,
     "The first volume is a martial-arts comedy — Goku is a kid with a tail hunting dragon balls with a girl, and the manga's genius is that the power scale didn't exist yet.",
     "Read the first volume and notice the comedy — it's a gag manga. The manga's genius is that the shift to action is the plot."),
    ("One Piece (Vol 1)", 1997, "Eiichiro Oda", ["Adventure", "Shonen", "Pirate"], 0, 1,
     "The first volume introduces the Straw Hats — Oda's hidden-detail style is already present, and the manga's genius is that the treasure is the premise, not the plot.",
     "Read the first volume and notice the cover — Oda hides details everywhere. The manga's genius is that the 'romance dawn' is the theme."),
    ("Naruto (Vol 1)", 1999, "Masashi Kishimoto", ["Action", "Shonen", "Ninja"], 0, 1,
     "The first volume is the academy arc — the 'demon fox' in Naruto is the plot, and the manga's genius is that the outcast is the hero.",
     "Read the first volume and notice the loneliness — Naruto's pranks are a cry for attention. The manga's genius is that the fox is the character."),
    ("Death Note (Vol 1)", 2003, "Tsugumi Ohba", ["Thriller", "Psychological", "Mystery"], 0, 1,
     "The first volume introduces the rules and the game — the manga's genius is that Light is the villain from page one, and the 'L' introduction is the plot's engine.",
     "Read the first volume and notice the rules — each one exists to make the game fair. The manga's genius is that the notebook is the character."),
    ("Bleach (Vol 1)", 2001, "Tite Kubo", ["Action", "Supernatural", "Shonen"], 0, 1,
     "The first volume introduces Ichigo and Rukia — the 'soul reaper' premise, and Kubo's panel whitespace is already the signature.",
     "Read the first volume and notice the whitespace — Kubo uses it like a composer. The manga's genius is that the sword is the character."),
    ("Fullmetal Alchemist (Vol 1)", 2001, "Hiromu Arakawa", ["Adventure", "Dark Fantasy", "Steampunk"], 0, 1,
     "The first volume establishes the 'equivalent exchange' law — the manga's genius is that the law is broken by the ending, and the brothers' search is the plot.",
     "Read the first volume and notice the law — equivalent exchange is the thesis. The manga's genius is that the law is the trap."),
    ("Attack on Titan (Vol 1)", 2009, "Hajime Isayama", ["Dark Fantasy", "Action", "Dystopian"], 0, 1,
     "The first volume's walled-city premise — Isayama's art was considered rough, and the manga's genius is that the roughness is the dread.",
     "Read the first volume and notice the walls — the height is the plot. The manga's genius is that the basement is the center."),
    ("Tokyo Revengers (Vol 1)", 2017, "Ken Wakui", ["Action", "Drama", "Gang"], 0, 1,
     "The first volume establishes the time-travel rules — the manga's genius is that each trip costs something, and the 'delinquent youth' fashion is authentic to the era.",
     "Read the first volume and notice the cost — the time travel has rules. The manga's genius is that the saving is the plot."),
    ("Blue Lock (Vol 1)", 2018, "Muneyuki Kaneshiro", ["Sports", "Psychological", "Soccer"], 0, 1,
     "The first volume's 'ego' philosophy — the manga's genius is that soccer is a battle, and the 300-striker death-game is the plot.",
     "Read the first volume and notice the ego framing — the psychological duels are the game. The manga's genius is that the 'egoist' is the hero."),
    ("Haikyuu!! (Vol 1)", 2012, "Haruichi Furudate", ["Sports", "Coming of Age", "Volleyball"], 0, 1,
     "The first volume's 'short protagonist' — the manga's genius is that height is a metaphor, and the 'garbage war' rivalry is the engine.",
     "Read the first volume and notice the height — the short protagonist is the thesis. The manga's genius is that the limits are the plot."),
    ("Kaguya-sama: Love Is War (Vol 1)", 2015, "Aka Akasaka", ["Romance", "Comedy", "Psychological"], 0, 1,
     "The first volume's mind-game framing — the manga's genius is that the 'war' is a love confession, and the narrator's 4D-chess framing is the joke.",
     "Read the first volume and notice the framing — the narration is the comedy. The manga's genius is that the mind-games are vulnerability."),
    ("Chainsaw Man (Vol 1)", 2018, "Tatsuki Fujimoto", ["Action", "Dark Comedy", "Horror"], 0, 1,
     "The first volume's 'contract' framing — the manga's genius is that the chainsaw is a literal deal with the devil, and the film references are the style.",
     "Read the first volume and notice the contracts — each devil deal has a cost. The manga's genius is that the 'film editing' is the pacing."),
    ("Frieren (Vol 1)", 2020, "Kanehito Yamada", ["Fantasy", "Drama", "Slice of Life"], 0, 1,
     "The first volume's post-adventure framing — the manga's genius is that the quest is already over, and the 'belief magic' is the theme.",
     "Read the first volume and notice the time-skips — decades pass in pages. The manga's genius is that memory is the magic."),
    ("Made in Abyss (Vol 1)", 2012, "Akihito Tsukushi", ["Adventure", "Dark Fantasy", "Sci-Fi"], 0, 1,
     "The first volume's curse system — the manga's genius is that depth has a price, and the cute art is the trap.",
     "Read the first volume and notice the curse — every descent costs. The manga's genius is that the Abyss is the character."),
    ("Vagabond (Vol 2)", 1998, "Takehiko Inoue", ["Historical", "Martial Arts", "Drama"], 0, 1,
     "The second volume introduces the Yoshioka — the manga's genius is that the rivals are the teachers, and the inkwork continues to be the star.",
     "Read the second volume and notice the rivals — each fight is a lesson. The manga's genius is that the way is the plot."),
]

MANHWA = [
    ("The Legend of the Northern Blade", 2019, "Woogack", ["Martial Arts", "Action", "Murim"], 0, 1,
     "The murim manhwa about a disabled martial artist who returns — the 'Northern Blade' sect's fall is the plot, and the manhwa's genius is that the disability is the strength.",
     "Read the first volume and notice the disability — the 'crippled' protagonist is the power. The manhwa's genius is that the recovery is the fight."),
    ("Return of the Mount Hua Sect", 2021, "Biga", ["Martial Arts", "Action", "Murim"], 0, 1,
     "The comedy-murim manhwa about the Mount Hua Sect's revival — the 'plum blossom sword' style is the plot, and the manhwa's genius is that the humble sect is the power.",
     "Read the first volume and notice the comedy — the 'beggar sect' is the joke. The manhwa's genius is that the revival is the plot."),
    ("Nano Machine", 2020, "Han Jung Wollya", ["Martial Arts", "Action", "Sci-Fi"], 0, 1,
     "The murim manhwa with a sci-fi twist — the 'nano machine' in the protagonist's blood is the cheat, and the manhwa's genius is that the future tech is the power.",
     "Read the first volume and notice the nano machine — the system is the plot. The manhwa's genius is that the 'cheat' is the character."),
    ("Doctor Elise: The Royal Lady with the Lamp", 2017, "Yuin", ["Romance", "Drama", "Isekai"], 0, 1,
     "The isekai medical romance — the surgeon who regresses to a noble lady, and the manhwa's genius is that the medicine is the plot.",
     "Read the first volume and notice the medicine — the surgeries are the drama. The manhwa's genius is that the 'lady with the lamp' is the thesis."),
    ("A Returner's Magic Should Be Special", 2018, "Usonan", ["Fantasy", "Action", "Regression"], 0, 1,
     "The regression manhwa about a failed mage who returns — the 'shadow world' apocalypse is the plot, and the manhwa's genius is that the failure is the teacher.",
     "Read the first volume and notice the regression — the failed future is the guide. The manhwa's genius is that the 'special magic' is teamwork."),
    ("The Second Coming of Gluttony", 2019, "Royale", ["Fantasy", "Action", "Isekai"], 0, 1,
     "The isekai manhwa about a gambler who becomes a hero — the 'tower of trials' is the plot, and the manhwa's genius is that the 'gluttony' is the sin.",
     "Read the first volume and notice the tower — the trials are the plot. The manhwa's genius is that the redemption is the arc."),
    ("I am the Sorcerer King", 2019, "Decaspell", ["Fantasy", "Action", "Revenge"], 0, 1,
     "The regression manhwa about a magic researcher who returns — the 'magic holes' are the plot, and the manhwa's genius is that the research is the power.",
     "Read the first volume and notice the research — the magic theory is the plot. The manhwa's genius is that the 'sorcerer king' is the title."),
    ("Tomb Raider King", 2019, "Redice Studio", ["Action", "Fantasy", "Revenge"], 0, 1,
     "The relic-hunting manhwa about a tomb raider who returns — the 'relics' are the power system, and the manhwa's genius is that the artifacts are the characters.",
     "Read the first volume and notice the relics — each one has a power. The manhwa's genius is that the 'tomb raider' is the antihero."),
    ("The Dark Magician Transmigrates After 66666 Years", 2021, "Lunaart", ["Fantasy", "Action", "Revenge"], 0, 1,
     "The regression manhwa about a dark magician sealed for 66,666 years — the 'misfits' are the plot, and the manhwa's genius is that the villain is the protagonist.",
     "Read the first volume and notice the 66666 framing — the number is the title's joke. The manhwa's genius is that the 'dark' magician is the antihero."),
    ("Ordeal", 2020, "Brent Bristol", ["Superhero", "Action", "Drama"], 0, 1,
     "The webtoon superhero story about a 'tribe' of fighters — the manhwa's genius is that the martial arts are the powers, and the 'ordeal' is the tournament.",
     "Read the first volume and notice the martial arts — the 'tribes' are the powers. The manhwa's genius is that the tournament is the plot."),
    ("Tower of God (Season 2)", 2010, "SIU", ["Fantasy", "Action", "Adventure"], 0, 1,
     "The second season skips years — Baam returns changed, and the manhwa's genius is that the Tower's rules are the plot.",
     "Read the second season's first chapters and notice the time-skip — Baam is not the same. The manhwa's genius is that the Tower's floors are the character."),
    ("The Breaker: New Waves", 2010, "Geuk-Jin Jeon", ["Martial Arts", "Action", "Murim"], 0, 1,
     "The sequel to The Breaker — the 'Sun-Woo clan' arc is the plot, and the manhwa's genius is that the murim is the world.",
     "Read the first volume and notice the world — the murim's politics are the plot. The manhwa's genius is that the 'new waves' is the title."),
    ("The God of High School (Season 2)", 2011, "Yongje Park", ["Action", "Martial Arts", "Tournament"], 0, 1,
     "The second season reveals the 'god' powers — the manhwa's genius is that the tournament is a recruitment tool, and the mythic war is the plot.",
     "Read the second season and notice the gods — the powers are the bait. The manhwa's genius is that the 'high school' is the front."),
    ("Unholy Blood", 2020, "Lina Im", ["Action", "Supernatural", "Drama"], 0, 1,
     "The vampire manhwa about a girl who hides her blood — the 'pure-blood' war is the plot, and the manhwa's genius is that the secret is the power.",
     "Read the first volume and notice the secret — the vampire is the protagonist. The manhwa's genius is that the 'unholy' is the title."),
    ("The Reincarnated Assassin is a Genius Swordsman", 2021, "Pega", ["Fantasy", "Action", "Reincarnation"], 0, 1,
     "The reincarnation manhwa about an assassin who becomes a noble — the 'sword' talent is the plot, and the manhwa's genius is that the assassin is the hero.",
     "Read the first volume and notice the sword — the talent is the plot. The manhwa's genius is that the 'genius swordsman' is the title."),
    ("Tales of Demons and Gods", 2015, "Mad Snail", ["Fantasy", "Action", "Cultivation"], 0, 1,
     "The cultivation manhwa about a demon who regresses — the 'demon lord' who returns to his youth, and the manhwa's genius is that the knowledge is the power.",
     "Read the first volume and notice the regression — the demon's knowledge is the cheat. The manhwa's genius is that the 'demons and gods' is the title."),
    ("Against the Gods", 2015, "Mars Gravity", ["Fantasy", "Action", "Cultivation"], 0, 1,
     "The cultivation manhwa about a boy with a poison body — the 'poison' is the power, and the manhwa's genius is that the curse is the cheat.",
     "Read the first volume and notice the poison — the body is the plot. The manhwa's genius is that the 'against the gods' is the title."),
    ("Solo Max-Level Newbie", 2021, "Maslow", ["Fantasy", "Action", "System"], 0, 1,
     "The system manhwa about a tower climber — the 'tower' is the plot, and the manhwa's genius is that the guide is the power.",
     "Read the first volume and notice the system — the tower's rules are the plot. The manhwa's genius is that the 'newbie' is the title."),
    ("Return to Player", 2021, "Jeho", ["Fantasy", "Action", "Regression"], 0, 1,
     "The regression manhwa about a 'returner' in a game world — the 'player' framing is the plot, and the manhwa's genius is that the game is real.",
     "Read the first volume and notice the game framing — the 'quests' are real. The manhwa's genius is that the 'return' is the plot."),
    ("The Player Who Can't Level Up", 2021, "Woo-gak", ["Fantasy", "Action", "System"], 0, 1,
     "The system manhwa about a player who can't level up — the 'level cap' is the plot, and the manhwa's genius is that the weakness is the strength.",
     "Read the first volume and notice the level cap — the 'can't level up' is the title. The manhwa's genius is that the weakness is the character."),
    ("Limit Breaker", 2021, "Pyeong-ah", ["Fantasy", "Action", "System"], 0, 1,
     "The system manhwa about a player who breaks limits — the 'limit break' is the plot, and the manhwa's genius is that the system is the character.",
     "Read the first volume and notice the system — the 'limit' is the enemy. The manhwa's genius is that the breaking is the plot."),
    ("The Dungeon Cleaning Life of a Once Genius Hunter", 2020, "Danduchu", ["Fantasy", "Action", "System"], 0, 1,
     "The system manhwa about a fallen hunter who cleans dungeons — the 'cleaning' is the plot, and the manhwa's genius is that the mundane is the power.",
     "Read the first volume and notice the cleaning — the 'genius hunter' is the title. The manhwa's genius is that the fall is the setup."),
    ("The Max Level Hero Has Returned! (Vol 2)", 2021, "Ray Halim", ["Fantasy", "Action", "Revenge"], 0, 1,
     "The second volume's political revenge — the 'max level' hero's return is the plot, and the manhwa's genius is that the level gap is the joke.",
     "Read the second volume and notice the politics — the 'revenge' is courtly. The manhwa's genius is that the power gap is the comedy."),
    ("Eleceed (Vol 2)", 2018, "Jeho Son", ["Action", "Comedy", "Superhero"], 0, 1,
     "The second volume introduces the 'awakened' world — the manhwa's genius is that the cat mentor is the comedy, and the found family is the plot.",
     "Read the second volume and notice the mentor — the cat is the comedy. The manhwa's genius is that the family is the plot."),
    ("Wind Breaker (Vol 2)", 2013, "Yongseok Jo", ["Sports", "Action", "Drama"], 0, 1,
     "The second volume's first race — the manhwa's genius is that the cycling physics are real, and the gang is the plot.",
     "Read the second volume and notice the race — the drafting is real. The manhwa's genius is that the violence and the racing are the same."),
    ("Sweet Home (Vol 2)", 2017, "Kim Carnby", ["Horror", "Survival", "Drama"], 0, 1,
     "The second volume's monster rules — the manhwa's genius is that each monster is a wish, and the 'desire' is the clue.",
     "Read the second volume and notice the monsters — each one is a desire. The manhwa's genius is that the horror is the wish."),
    ("Bastard (Vol 2)", 2014, "Kim Carnby", ["Thriller", "Psychological", "Horror"], 0, 1,
     "The second volume's tension — the manhwa's genius is that the reader knows the truth, and the complicity is the horror.",
     "Read the second volume and notice the irony — the knowledge is the tension. The manhwa's genius is that the killer is the least of it."),
    ("Lookism (Vol 2)", 2014, "Park Tae-joon", ["Drama", "Action", "Social"], 0, 1,
     "The second volume's gang arc — the manhwa's genius is that the body-switch is the commentary, and the 'lookism' is the thesis.",
     "Read the second volume and notice the commentary — the 'handsome body' is the metaphor. The manhwa's genius is that the beauty standards are the plot."),
    ("Study Group", 2019, "Shin Hyung-wook", ["Action", "Comedy", "School"], 0, 1,
     "The school manhwa about a student who wants to study but keeps fighting — the 'study group' is the plot, and the manhwa's genius is that the violence is the comedy.",
     "Read the first volume and notice the premise — the 'study' is the joke. The manhwa's genius is that the fights are the school."),
    ("DICE (Vol 2)", 2013, "Hyunseok Song", ["Fantasy", "Drama", "System"], 0, 1,
     "The second volume's dice rules — the manhwa's genius is that the stats come from others' loss, and the social commentary is the plot.",
     "Read the second volume and notice the cost — the dice are a zero-sum game. The manhwa's genius is that the education metaphor is the horror."),
    ("Get Schooled", 2019, "Yongtaek Chae", ["Action", "Drama", "School"], 0, 1,
     "The school manhwa about a teacher who fights bullies — the 'education' is the plot, and the manhwa's genius is that the violence is the lesson.",
     "Read the first volume and notice the teacher — the 'get schooled' is the title. The manhwa's genius is that the bullies are the system."),
    ("Locker Opener", 2020, "Pponya", ["Action", "School", "Drama"], 0, 1,
     "The school manhwa about a student who can open any locker — the 'locker' is the plot, and the manhwa's genius is that the mystery is the hook.",
     "Read the first volume and notice the lockers — each one is a story. The manhwa's genius is that the opening is the plot."),
    ("Money Game", 2020, "Bae Jin-soo", ["Thriller", "Drama", "Survival"], 0, 1,
     "The survival manhwa about 8 people locked in a house for 100 days — the 'money game' is the plot, and the manhwa's genius is that the greed is the horror.",
     "Read the first volume and notice the rules — the 100-day survival is the plot. The manhwa's genius is that the money is the trap."),
    ("The World Is Money and Power", 2020, "Hansol", ["Action", "Drama", "Survival"], 0, 1,
     "The survival manhwa about a game where money is power — the 'world is money' is the plot, and the manhwa's genius is that the class war is the game.",
     "Read the first volume and notice the game — the money is the power. The manhwa's genius is that the rich are the villains."),
    ("High School Lunch Dad", 2021, "Hee", ["Comedy", "School", "Family"], 0, 1,
     "The school manhwa about a father who becomes his daughter's classmate — the 'lunch dad' is the plot, and the manhwa's genius is that the comedy is the family.",
     "Read the first volume and notice the premise — the dad is the student. The manhwa's genius is that the lunch is the love."),
    ("My Daughter Is a Zombie", 2021, "Ggomdol", ["Comedy", "Family", "Fantasy"], 0, 1,
     "The comedy manhwa about a father and his zombie daughter — the 'zombie' is the plot, and the manhwa's genius is that the family is the comedy.",
     "Read the first volume and notice the premise — the zombie is the daughter. The manhwa's genius is that the fatherhood is the plot."),
    ("The Girl Downstairs", 2021, "Soonkki", ["Romance", "Comedy", "Slice of Life"], 0, 1,
     "The romance manhwa about a student and his mysterious neighbor — the 'downstairs' is the plot, and the manhwa's genius is that the mystery is the romance.",
     "Read the first volume and notice the mystery — the neighbor is the plot. The manhwa's genius is that the reveal is the romance."),
    ("A Good Day to Be a Dog", 2017, "Lee Hey", ["Romance", "Comedy", "Fantasy"], 0, 1,
     "The romance manhwa about a girl who turns into a dog when kissed — the 'dog' is the plot, and the manhwa's genius is that the curse is the comedy.",
     "Read the first volume and notice the curse — the dog is the premise. The manhwa's genius is that the kiss is the problem."),
    ("Seasons of Blossom", 2020, "Hongduck", ["Romance", "Drama", "School"], 0, 1,
     "The school romance manhwa about four seasons of love — the 'seasons' is the plot, and the manhwa's genius is that each arc is a season.",
     "Read the first volume and notice the seasons — each arc is a stage. The manhwa's genius is that the blossom is the metaphor."),
    ("Annarasumanara", 2011, "Ha Il-kwon", ["Drama", "Fantasy", "Coming of Age"], 0, 1,
     "The magic-realism manhwa about a girl and a magician — the 'magic' is the plot, and the manhwa's genius is that the trick is the theme.",
     "Read the first volume and notice the magic — the magician is the metaphor. The manhwa's genius is that the 'annarasumanara' is the spell."),
    ("Hellper", 2013, "Sakki", ["Action", "Fantasy", "Dark Comedy"], 0, 1,
     "The punk-fantasy manhwa about a hell where souls fight — the 'hellper' is the plot, and the manhwa's genius is that the punk aesthetic is the style.",
     "Read the first volume and notice the style — the punk is the tone. The manhwa's genius is that the hell is the world."),
    ("Knight Run", 2011, "Sungmin Kim", ["Sci-Fi", "Action", "War"], 0, 1,
     "The sci-fi manhwa about a war against an alien threat — the 'knight' is the plot, and the manhwa's genius is that the mecha are the characters.",
     "Read the first volume and notice the war — the alien threat is the plot. The manhwa's genius is that the knights are the last hope."),
    ("Dr. Frost", 2011, "Lee Jong-beom", ["Psychological", "Mystery", "Drama"], 0, 1,
     "The psychological manhwa about a psychologist who can't feel — the 'Frost' is the plot, and the manhwa's genius is that the psychology is the case.",
     "Read the first volume and notice the cases — each one is a lesson. The manhwa's genius is that the therapist is the patient."),
]


def _slug(text):
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "topic"


def _build(file_name, category_id, subtype, verb, rows):
    path = ASSETS / file_name
    existing = json.loads(path.read_text(encoding="utf-8")) if path.exists() else []
    existing_ids = {t["id"] for t in existing}
    seen_names = {t["name"] for t in existing}
    added = 0
    for (name, year, creator, tags, duration, tier, teaser, instruction) in rows:
        display = f"{name} ({year})" if year else name
        if display in seen_names:
            continue
        base = f"{subtype.lower()}-{_slug(name)}"
        tid = base
        n = 2
        while tid in existing_ids:
            tid = f"{base}-{n}"
            n += 1
        existing_ids.add(tid)
        seen_names.add(display)
        full_tags = list(tags)
        if year and not any(t.endswith("s") and t[:-1].isdigit() for t in full_tags):
            full_tags.append(f"{year // 10 * 10}s")
        existing.append({
            "id": tid,
            "categoryId": category_id,
            "subtype": subtype,
            "name": display,
            "teaser": teaser,
            "imageUrl": "",
            "byline": creator,
            "exploreAction": {
                "verb": verb,
                "targetName": f"{name} ({year}) end-to-end" if year else f"{name}",
                "durationMinutes": duration if duration else 45,
                "instruction": instruction,
            },
            "tags": full_tags,
            "tier": tier,
        })
        added += 1
    path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{file_name}: +{added} (total {len(existing)})")


def main():
    _build("anime.json", "ANIME", "Anime", "Watch", ANIME)
    _build("manga.json", "MANGA", "Manga", "Read", MANGA)
    _build("manhwa.json", "MANHWA", "Manhwa", "Read", MANHWA)


if __name__ == "__main__":
    main()
