#!/usr/bin/env python3
"""batch_media_topup.py — second drop for Songs / Series + the new Games lane.

Same schema + quality bar as batch_songs_series.py; idempotent (skips ids
and names already present). Songs/Series pull toward ~60; Games debuts ~65.

Usage: python3 scripts/batch_media_topup.py && python3 scripts/validate_topics.py
"""

import json
import re
import unicodedata
from pathlib import Path

ASSETS = Path("app/src/main/assets/topics")

SONGS = [
    ("Purple Rain", 1984, "Prince", ["Rock", "Ballad", "American"], 9, 1,
     "Prince wrote it as a guitar showcase and the film's concert scene is a real performance — the solo at the end is a single unedited take, and the song's gospel choir is the 'rain' made sound.",
     "Listen to the full nine minutes with the solo — it's one unedited take. The song's genius is that the grief is the guitar; the lyrics are the weather."),
    ("Hotel California", 1976, "Eagles", ["Rock", "Classic", "American"], 6, 1,
     "The song's lyrics were written as a literal road trip gone wrong — the 'you can check out any time you like, but you can never leave' line is the song's thesis, and the famous dual guitar solo was improvised.",
     "Listen for the dual guitar outro — two solos trading phrases. The song's genius is that the hotel is a metaphor you can't pin down; the ambiguity is the point."),
    ("Sweet Child o' Mine", 1987, "Guns N' Roses", ["Rock", "Hard Rock", "American"], 5, 1,
     "The riff started as a string-skipping warm-up exercise that Slash called a joke — Axl wrote the lyrics in five minutes about his girlfriend, and the song became the band's biggest hit.",
     "Listen to the intro and notice the 'joke' riff — the warm-up became the hook. The song's genius is that the guitar solo is a conversation with the vocal."),
    ("Creep", 1992, "Radiohead", ["Alternative", "Rock", "British"], 4, 1,
     "The band hated the song and nearly left it off the album — it became their only mainstream hit, and the 'special' lyric is about Thom Yorke's real crush at university.",
     "Listen for the quiet-loud structure — the verse is a whisper, the chorus is a scream. The song's genius is that the self-loathing is the hook."),
    ("Seven Nation Army", 2003, "The White Stripes", ["Garage Rock", "Alternative", "American"], 4, 1,
     "The iconic riff is a bass line played on a guitar with a pitch-shifter — Jack White wrote it while touring and the 'seven nation army' was his phrase for the US military draft.",
     "Listen for the riff and notice it's a guitar pretending to be a bass. The song's genius is that the riff carries the whole song; the lyrics are the counter-melody."),
    ("Dancing Queen", 1976, "ABBA", ["Pop", "Disco", "Swedish"], 4, 1,
     "Written for the Swedish king's wedding, the song's 'young and sweet, only seventeen' line was about a real 17-year-old who danced at a club ABBA visited — it's the only song ABBA wrote for a woman.",
     "Listen for the piano intro and the key change — the song is engineered joy. The song's genius is that the disco beat is the 'dance' made literal."),
    ("Superstition", 1972, "Stevie Wonder", ["Funk", "Soul", "American"], 4, 1,
     "Stevie wrote the drum groove first — the 'superstition' lyrics came after, and the song's famous clavinet riff is played on a real Hohner Clavinet through a wah pedal.",
     "Listen for the clavinet — it's the song's engine. The song's genius is that the groove is the thesis; the lyrics are the afterthought that made it a hit."),
    ("Comfortably Numb", 1979, "Pink Floyd", ["Progressive", "Rock", "British"], 6, 1,
     "The two guitar solos were recorded by two different guitarists (David Gilmour twice, years apart) — the song's lyrics are about Roger Waters' stage collapse and the doctor who injected him.",
     "Listen for the two solos — the first is distant, the second is the climax. The song's genius is that the numbness is the narrator and the music is the feeling."),
    ("Don't Stop Believin'", 1981, "Journey", ["Rock", "Classic", "American"], 4, 1,
     "The song flopped on release and became a hit years later through karaoke — the 'streetlight people' lyric is about real people in a real Detroit club, and the song's key change is its famous kick.",
     "Listen for the key change before the final chorus — it's the song's ignition. The song's genius is that the 'believin'' is the instruction."),
    ("Crazy in Love", 2003, "Beyoncé", ["R&B", "Pop", "American"], 4, 1,
     "The horn sample is from a 1970s Chi-Lites song and the 'uh oh' hook was improvised — Beyoncé's debut solo hit was written in a studio with Jay-Z in two days.",
     "Listen for the horn sample and the 'uh oh' — both are the hooks. The song's genius is that the horns are the chaos; the beat is the control."),
    ("I Will Survive", 1978, "Gloria Gaynor", ["Disco", "Soul", "American"], 3, 1,
     "Written as the B-side after the label demanded a song about Gaynor's real injury — the 'survive' anthem became the first disco song to top the charts after disco's fall, a comeback in itself.",
     "Listen for the string section and the spoken intro — the song is a speech. The song's genius is that the defiance is the hook; the 'survive' is the thesis."),
    ("London Calling", 1979, "The Clash", ["Punk", "Rock", "British"], 4, 1,
     "Written as a warning about the Thames flooding London — the band predicted the 'ice age' of climate change 40 years early, and the song's bassline is its most copied riff.",
     "Listen for the bassline and the flood imagery — the warning is real. The song's genius is that the punk rage is a prophecy."),
]

SERIES = [
    ("Seinfeld", 1989, "Larry David & Jerry Seinfeld", ["Comedy", "Sitcom", "American"], 22 * 9, 1,
     "The 'show about nothing' that changed sitcoms — every episode was built on real-life observations, and the 'no hugging, no learning' rule made it the darkest comedy on TV.",
     "Watch the 'Chinese Restaurant' episode — it's the show's thesis in 22 minutes. The genius is that nothing happens and that's the point."),
    ("Twin Peaks", 1990, "David Lynch & Mark Frost", ["Mystery", "Surreal", "Drama"], 22 * 30, 1,
     "The murder mystery that made TV surreal — Lynch refused to reveal the killer when the network demanded, and the show's 'Who killed Laura Palmer?' became the first TV mystery to break the fourth wall.",
     "Watch the pilot and notice the dream logic — the show's clues are symbols, not facts. The genius is that the mystery is the atmosphere."),
    ("The X-Files", 1993, "Chris Carter", ["Sci-Fi", "Mystery", "Horror"], 22 * 11, 1,
     "The 'trust no one' show that made conspiracy TV mainstream — the 'monster of the week' episodes and the mythology episodes run on different rules, and the 'I want to believe' poster is the thesis.",
     "Watch a 'monster of the week' episode first — the show's two engines are different. The genius is that the myth arc is the conspiracy you never solve."),
    ("Lost", 2004, "J.J. Abrams & Damon Lindelof", ["Mystery", "Sci-Fi", "Drama"], 22 * 6, 1,
     "The island mystery that made serialized TV a genre — the writers famously didn't know the ending for seasons, and the 'smoke monster' was a production accident that became the plot.",
     "Watch the pilot and notice the mystery density — every shot seeds a question. The genius is that the characters are the plot; the island is the frame."),
    ("24", 2001, "Joel Surnow", ["Thriller", "Action", "Real Time"], 22 * 9, 1,
     "The real-time gimmick (each episode is one hour of a day) made it a phenomenon — the split-screen format was born from a technical accident, and the 'ticking clock' became the genre standard.",
     "Watch the first episode and notice the split-screen — the format is the show. The genius is that the real-time structure IS the tension."),
    ("Grey's Anatomy", 2005, "Shonda Rhimes", ["Medical", "Drama", "Romance"], 22 * 21, 1,
     "The medical drama that made Shonda Rhimes a brand — the 'McDreamy' nickname was a writing-room joke that became canon, and the show's real subject is the cost of caring.",
     "Watch the first season and notice the voiceover — Meredith's narration is the show's thesis. The genius is that the medicine is the metaphor."),
    ("Band of Brothers", 2001, "Steven Spielberg & Tom Hanks", ["War", "Drama", "Historical"], 22 * 10, 1,
     "The $125M miniseries about Easy Company — real veterans' interviews open each episode, and the show's genius is that the combat is honest about fear, not glory.",
     "Watch the first episode and notice the interviews — the real men frame the fiction. The genius is that the horror is the point, not the heroism."),
    ("Fargo", 2014, "Noah Hawley", ["Crime", "Drama", "Black Comedy"], 22 * 5, 1,
     "The anthology series inspired by the Coen film — each season is a new crime story with the same 'Minnesota nice' tone, and the show's genius is that the kindness is the violence's frame.",
     "Watch the first season's pilot and notice the tone — the violence is absurd, the accents are real. The genius is that the 'true story' claim is a lie and the point."),
    ("Parks and Recreation", 2009, "Greg Daniels & Michael Schur", ["Comedy", "Mockumentary", "American"], 22 * 7, 1,
     "The mockumentary about local government — the show famously got better after its first season, and Leslie Knope's optimism became the template for wholesome comedy.",
     "Watch the first season's finale and then the second season's premiere — the tonal shift is the story. The genius is that the bureaucracy is the comedy."),
    ("The Simpsons", 1989, "Matt Groening", ["Comedy", "Animation", "Satire"], 22 * 34, 1,
     "The longest-running scripted show in TV history — the first 12 seasons are considered the golden age, and the show's genius is that the satire is the structure.",
     "Watch the first 'Treehouse of Horror' — the anthology format is the show's lab. The genius is that the family is the frame for everything."),
    ("South Park", 1997, "Trey Parker & Matt Stone", ["Comedy", "Animation", "Satire"], 22 * 26, 1,
     "The show's production is famous for its one-week turnaround — episodes air days after current events, and the 'respect my authoritah' catchphrase is the show's thesis.",
     "Watch the first episode and then the 'Cartman Gets an Anal Probe' anniversary special — the animation evolution is the story. The genius is that the crudeness is the point."),
    ("The Twilight Zone", 1959, "Rod Serling", ["Sci-Fi", "Horror", "Anthology"], 22 * 5, 1,
     "The anthology that invented the twist ending — Serling wrote most episodes himself as social commentary disguised as sci-fi, and the 'you're traveling through another dimension' intro is the most parodied in TV.",
     "Watch 'The Monsters Are Due on Maple Street' — it's the show's thesis in 25 minutes. The genius is that the sci-fi is the mask for the social commentary."),
    ("Black Mirror", 2011, "Charlie Brooker", ["Sci-Fi", "Dystopian", "Anthology"], 22 * 6, 1,
     "The anthology about technology's dark side — the name comes from the black reflection of a screen, and the show's genius is that the tech is always near-future plausible.",
     "Watch 'San Junipero' — the show's rare happy ending is the reveal. The genius is that the anthology format lets every episode be a different genre."),
    ("The Good Place", 2016, "Michael Schur", ["Comedy", "Fantasy", "Philosophy"], 22 * 4, 1,
     "The sitcom about the afterlife that teaches actual moral philosophy — the show's first-season twist is considered one of TV's best, and the 'point system' is real ethical theory.",
     "Watch the first season knowing there's a twist — the setup is the reveal. The genius is that the philosophy is the plot."),
    ("Dexter", 2006, "James Manos Jr.", ["Crime", "Drama", "Psychological"], 22 * 8, 1,
     "The serial-killer drama about a killer who kills killers — the show's famous 'code' (from his father) is the premise, and the show's genius is that the monster is the protagonist.",
     "Watch the first episode and notice the code — the rules are the character. The genius is that the 'dark passenger' is the show's narrator."),
    ("The Americans", 2013, "Joe Weisberg", ["Spy", "Drama", "Historical"], 22 * 6, 1,
     "Created by a former CIA officer, the show's KGB couple is drawn from real Cold War history — the 'illegals' program the show depicts was real and declassified during its run.",
     "Watch the first episode and notice the neighbors — the family is the cover. The genius is that the marriage and the mission are the same spy game."),
]

GAMES = [
    ("Pong", 1972, "Atari", ["Arcade", "Classic", "Sports"], 15, 1,
     "Atari's first hit was a rejected idea — Nolan Bushnell copied table tennis after playing a Magnavox demo, and the game's 'failure to add coins' made it the first quarter-eating arcade phenomenon.",
     "Play one round and notice the physics — the ball's angle is the whole game. The genius is that the simplicity is the design."),
    ("Space Invaders", 1978, "Taito", ["Arcade", "Shooter", "Classic"], 20, 1,
     "The game that caused a Japanese coin shortage — the aliens speed up as you kill them because the CPU runs faster with fewer sprites, an accident that became the difficulty curve.",
     "Play and notice the speed-up — the CPU is the game designer. The genius is that the 'invaders' march is the countdown."),
    ("Pac-Man", 1980, "Namco", ["Arcade", "Classic", "Maze"], 20, 1,
     "The first game with a mascot — the maze was hand-drawn as a single continuous line, and the ghosts' AI (Blinky, Pinky, Inky, Clyde) was designed so each one behaves differently.",
     "Play one maze and notice the ghost personalities — each one has a real AI pattern. The genius is that the maze is a single line."),
    ("Donkey Kong", 1981, "Nintendo", ["Arcade", "Platformer", "Classic"], 20, 1,
     "The game that introduced Mario (then 'Jumpman') — the barrels' physics are the game, and the 'skip screen' trick (the 22nd level kill screen) was a bug that became legend.",
     "Play the first level and notice the barrel physics — the timing is the game. The genius is that the jump is the whole vocabulary."),
    ("Super Mario Bros.", 1985, "Nintendo", ["Platformer", "Classic", "Adventure"], 60, 1,
     "The game that saved the video game industry after the 1983 crash — the level 1-1 was designed as a tutorial that teaches you to play without a single word.",
     "Play level 1-1 and notice the teaching — every hazard is introduced safely first. The genius is that the level is a lesson."),
    ("The Legend of Zelda", 1986, "Nintendo", ["Adventure", "Action", "Classic"], 90, 1,
     "Shigeru Miyamoto designed it as a 'miniature garden' — the game famously has no linear path, and the 'it's dangerous to go alone' line is the most quoted in gaming.",
     "Play the first dungeon and notice the openness — you can go anywhere. The genius is that the exploration is the plot."),
    ("Metroid", 1986, "Nintendo", ["Action", "Sci-Fi", "Exploration"], 90, 1,
     "The game that invented the 'Metroidvania' genre — the ending reveals the protagonist is a woman, a twist that was hidden until you finished the game.",
     "Play the first area and notice the locked doors — the backtracking is the design. The genius is that the reveal is the reward."),
    ("Final Fantasy VII", 1997, "Square", ["RPG", "Fantasy", "Story"], 240, 1,
     "The JRPG that made the genre global — the game's famous death scene is the moment the genre grew up, and the game's budget was so large it nearly bankrupted Square.",
     "Play the opening and notice the scale — the game is a film in 1997 terms. The genius is that the story is the combat."),
    ("Chrono Trigger", 1995, "Square", ["RPG", "Time Travel", "Story"], 180, 1,
     "Developed by the 'Dream Team' (Final Fantasy, Dragon Quest and Dragon Ball creators) — the game has 13 endings and no random encounters, a radical choice in 1995.",
     "Play the first few hours and notice the pacing — no random battles, no filler. The genius is that the time travel is the structure."),
    ("Sonic the Hedgehog", 1991, "Sega", ["Platformer", "Action", "Classic"], 60, 1,
     "Built to counter Mario — Sonic's speed was the answer to Mario's jump, and the first level's loop-the-loop was the first time a console game felt fast.",
     "Play the Green Hill Zone and notice the speed — the level is a rollercoaster. The genius is that the speed is the character."),
    ("Street Fighter II", 1991, "Capcom", ["Fighting", "Arcade", "Classic"], 60, 1,
     "The fighting game that created the genre — every character had a unique move set, and the 'hadouken' became the most famous input in gaming history.",
     "Play as Ryu and learn the special moves — the quarter-circle is the grammar. The genius is that the roster is the game."),
    ("Mortal Kombat", 1992, "Midway", ["Fighting", "Arcade", "Classic"], 45, 1,
     "The game that caused the ESRB rating system — the digitized actors and fatalities were so violent that the US government held hearings on video game violence.",
     "Play one match and notice the digitized realism — real actors, real motion. The genius is that the controversy IS the marketing."),
    ("Doom", 1993, "id Software", ["FPS", "Horror", "Classic"], 90, 1,
     "The game that defined the FPS — the engine was written in a week, and the game's shareware model (free first episode) made it the most-installed game of its era.",
     "Play the first episode and notice the level design — the geometry is the combat. The genius is that the shareware was the marketing."),
    ("Quake", 1996, "id Software", ["FPS", "Sci-Fi", "Classic"], 90, 1,
     "The first fully 3D FPS — the game's engine was so advanced it was licensed for decades, and the 'rocket jump' was an accident that became a skill.",
     "Play the first level and notice the 3D — the verticality is new. The genius is that the rocket jump is the speedrun."),
    ("Half-Life", 1998, "Valve", ["FPS", "Sci-Fi", "Story"], 120, 1,
     "The game that invented the scripted FPS — the entire story happens in real time with no cutscenes, and the opening tram ride is a tutorial disguised as a commute.",
     "Play the first 30 minutes and notice the scripted events — no cutscenes, all in-world. The genius is that the story is the environment."),
    ("Portal", 2007, "Valve", ["Puzzle", "First Person", "Comedy"], 90, 1,
     "Built from a student project (Narbacular Drop) — the game's 'companion cube' and GLaDOS are the most quoted AI in gaming, and the ending song was written by the writer's band.",
     "Play the first chambers and notice the teaching — each test is a lesson. The genius is that the puzzle is the character."),
    ("Counter-Strike", 2000, "Valve", ["FPS", "Multiplayer", "Tactical"], 120, 1,
     "Born as a Half-Life mod — the game's economic system (buy rounds) became the template for tactical shooters, and its one-life-per-round tension defined esports.",
     "Play a round and notice the economy — the buy system is the strategy. The genius is that the tension is the design."),
    ("Team Fortress 2", 2007, "Valve", ["FPS", "Multiplayer", "Comedy"], 120, 1,
     "The class-based shooter with nine distinct characters — the game's 'Meet the Team' videos became the standard for game marketing, and the hats became a meme economy.",
     "Play as two different classes and notice the difference — the classes are the game. The genius is that the personality is the balance."),
    ("Minecraft", 2011, "Mojang", ["Sandbox", "Survival", "Creative"], 180, 1,
     "The best-selling game of all time — built from a 'cave game' prototype in a week, and the game's 'crafting table' UI was designed in a single night.",
     "Play the first night and notice the survival loop — dig, build, survive. The genius is that the block is the entire vocabulary."),
    ("Tetris", 1984, "Alexey Pajitnov", ["Puzzle", "Classic", "Arcade"], 45, 1,
     "Built on a Soviet computer by a mathematician — the game's 'tetromino' shapes are the plot, and the 'Tetris effect' (seeing blocks in your sleep) is a real psychological phenomenon.",
     "Play for ten minutes and notice the piece selection — the randomness is the challenge. The genius is that the geometry is the game."),
    ("Pokémon Red and Blue", 1996, "Game Freak", ["RPG", "Monster", "Classic"], 240, 1,
     "The monster-catching RPG that became a global phenomenon — the 'MissingNo' glitch became a legend, and the game's social element (trading) was the original multiplayer.",
     "Play the first town and notice the design — the 'catch' is the hook. The genius is that the trading is the multiplayer."),
    ("GoldenEye 007", 1997, "Rare", ["FPS", "Spy", "Classic"], 120, 1,
     "The movie tie-in that became a legend — the four-player split-screen was a late addition that defined the console FPS, and the game's 'Oddjob' controversy was the first balance debate.",
     "Play the Facility level and notice the level design — the mission is the stealth. The genius is that the multiplayer was an afterthought."),
    ("Super Mario 64", 1996, "Nintendo", ["Platformer", "3D", "Classic"], 120, 1,
     "The game that taught the industry how to do 3D — the camera system was invented from scratch, and the first level's opening was a crash course in 3D movement.",
     "Play the first level and notice the camera — the controls are the design. The genius is that the 3D is the learning."),
    ("The Legend of Zelda: Ocarina of Time", 1998, "Nintendo", ["Adventure", "Action", "3D"], 240, 1,
     "Considered by many the greatest game ever made — the time-travel structure (young/old Link) was a technical breakthrough, and the game's 'Z-targeting' lock-on became the 3D action standard.",
     "Play the first temple and notice the lock-on — the combat is the design. The genius is that the time travel is the structure."),
    ("Resident Evil", 1996, "Capcom", ["Survival Horror", "Action", "Classic"], 120, 1,
     "The game that invented survival horror — the 'tank controls' were a design accident, and the game's famous 'zombie dog' jump scare was a programming bug that was kept.",
     "Play the mansion and notice the resource management — the ammo IS the tension. The genius is that the horror is the economy."),
    ("Silent Hill", 1999, "Konami", ["Survival Horror", "Psychological", "Classic"], 120, 1,
     "The horror game that replaced monsters with psychology — the fog was a technical limitation that became the atmosphere, and the game's 'otherworld' is a descent into the protagonist's mind.",
     "Play the first town and notice the fog — the limitation is the design. The genius is that the horror is the psychology."),
    ("Metal Gear Solid", 1998, "Konami", ["Stealth", "Action", "Story"], 150, 1,
     "The game that made stealth a genre — the 'Psycho Mantis' boss fight (which reads your memory card) is the most famous fourth-wall break in gaming.",
     "Play the first mission and notice the stealth — the radar is the game. The genius is that the boss fights are the philosophy."),
    ("Halo: Combat Evolved", 2001, "Bungie", ["FPS", "Sci-Fi", "Action"], 180, 1,
     "The game that made the Xbox — the two-weapon limit and regenerating shields became the FPS standard, and the 'flood' reveal is one of gaming's best twists.",
     "Play the first level and notice the shield — the health design is the game. The genius is that the 'ring' is the level."),
    ("Grand Theft Auto III", 2001, "Rockstar", ["Open World", "Action", "Crime"], 240, 1,
     "The game that made open worlds mainstream — the 'sandbox' design was a technical gamble, and the radio stations became the game's real soul.",
     "Play the first hour and notice the freedom — the city IS the game. The genius is that the radio is the character."),
    ("Grand Theft Auto V", 2013, "Rockstar", ["Open World", "Action", "Crime"], 300, 1,
     "The most expensive game ever made at $265M — the three-protagonist structure was the design answer to GTA IV's linearity, and the game's heist missions are the set pieces.",
     "Play the first heist and notice the planning — the structure is the design. The genius is that the three characters are the game's three genres."),
    ("The Elder Scrolls V: Skyrim", 2011, "Bethesda", ["RPG", "Open World", "Fantasy"], 300, 1,
     "The game that 'you can play forever' — the 'arrow to the knee' guard line became a global meme, and the game's mod support made it a decade-long phenomenon.",
     "Play the opening and notice the freedom — the world is the game. The genius is that the mods are the longevity."),
    ("Fallout: New Vegas", 2010, "Obsidian", ["RPG", "Post-Apocalyptic", "Open World"], 300, 1,
     "The RPG with the most branching stories in the genre — every faction is morally gray, and the game's 'Hardcore mode' was the design answer to immersion.",
     "Play the first town and notice the factions — every choice has a cost. The genius is that the writing is the combat."),
    ("Mass Effect 2", 2010, "BioWare", ["RPG", "Sci-Fi", "Story"], 240, 1,
     "The game where your choices determine who lives and dies — the 'suicide mission' finale is the most famous consequence system in gaming, and the game's characters are its real draw.",
     "Play the character recruitment missions — the loyalty is the mechanic. The genius is that the ending is the consequence."),
    ("The Witcher 3: Wild Hunt", 2015, "CD Projekt Red", ["RPG", "Fantasy", "Open World"], 360, 1,
     "The RPG that redefined side quests — every contract has a moral choice, and the 'Bloody Baron' quest is considered the best-written quest in gaming.",
     "Play the Bloody Baron quest and notice the choices — every answer has a cost. The genius is that the side quests are the story."),
    ("Dark Souls", 2011, "FromSoftware", ["Action RPG", "Dark Fantasy", "Challenging"], 300, 1,
     "The game that made difficulty a design philosophy — the 'Souls-like' genre was born here, and the game's lore is hidden in item descriptions instead of cutscenes.",
     "Play the Undead Burg and notice the level design — the shortcut is the reward. The genius is that the lore is the exploration."),
    ("Bloodborne", 2015, "FromSoftware", ["Action RPG", "Gothic", "Challenging"], 300, 1,
     "The faster, more aggressive sibling of Dark Souls — the 'regain' mechanic (heal by attacking) changed the combat philosophy, and the game's Lovecraftian horror is its real setting.",
     "Play the first area and notice the regain — the aggression is the design. The genius is that the horror is the genre."),
    ("Elden Ring", 2022, "FromSoftware", ["Action RPG", "Open World", "Challenging"], 360, 1,
     "The open-world Souls game with lore written by George R.R. Martin — it sold 20M+ copies and won Game of the Year, and the 'open world' is the first in the genre that respects discovery.",
     "Play the opening area and notice the discovery — the map rewards curiosity. The genius is that the open world is the dungeon."),
    ("God of War (2018)", 2018, "Santa Monica Studio", ["Action", "Adventure", "Mythology"], 240, 1,
     "The reboot that turned a rage god into a father — the one-shot camera (no cuts) was a technical feat, and the game's real subject is parenting and legacy.",
     "Play the opening and notice the camera — one continuous shot. The genius is that the axe is the character."),
    ("The Last of Us", 2013, "Naughty Dog", ["Action", "Survival", "Story"], 240, 1,
     "The game that made video game stories cinematic — the 'giraffe scene' became the most discussed moment in gaming, and the game's ending is a deliberate moral test.",
     "Play the first hour and notice the opening — the prologue is the thesis. The genius is that the story is the gameplay."),
    ("Uncharted 2: Among Thieves", 2009, "Naughty Dog", ["Action", "Adventure", "Platformer"], 180, 1,
     "The game that made action set-pieces cinematic — the opening train sequence is considered the best in gaming, and the game's 'impossible' set pieces are the draw.",
     "Play the train sequence and notice the set-piece design — the action IS the story. The genius is that the spectacle is the craft."),
    ("Red Dead Redemption 2", 2018, "Rockstar", ["Open World", "Western", "Story"], 360, 1,
     "The most detailed open world ever made — every NPC has a life, and the game's epilogue is a meditation on endings and honor.",
     "Play the opening chapter and notice the detail — the world is alive. The genius is that the tragedy is the structure."),
    ("The Legend of Zelda: Breath of the Wild", 2017, "Nintendo", ["Open World", "Adventure", "Action"], 360, 1,
     "The game that reinvented open worlds — you can climb anything, and the game's physics engine is a real simulation. The 'it's dangerous to go alone' tradition continues in the Glider.",
     "Play the opening plateau and notice the freedom — the physics IS the game. The genius is that the climb is the answer."),
    ("Super Mario Odyssey", 2017, "Nintendo", ["Platformer", "3D", "Adventure"], 240, 1,
     "The 3D Mario that added a companion — Cappy (the hat) is the game's mechanic and character, and the game's 'New Donk City' is the most playful level in the series.",
     "Play the first kingdom and notice the hat — the capture mechanic is the design. The genius is that the power-up is the character."),
    ("Celeste", 2018, "Maddy Makes Games", ["Platformer", "Indie", "Story"], 180, 1,
     "The platformer about anxiety disguised as a mountain climb — the game's 'assist mode' was a design statement, and the story of Madeline's climb is the game's real content.",
     "Play the first chapter and notice the theme — the mountain is the metaphor. The genius is that the difficulty is the therapy."),
    ("Hollow Knight", 2017, "Team Cherry", ["Metroidvania", "Indie", "Action"], 300, 1,
     "The indie Metroidvania that defined the genre's modern era — the hand-drawn world is a single connected map, and the game's lore is buried in the world itself.",
     "Play the first area and notice the map — the exploration is the game. The genius is that the world is the story."),
    ("Undertale", 2015, "Toby Fox", ["RPG", "Indie", "Comedy"], 120, 1,
     "The RPG where you can finish without killing anyone — the 'mercy' mechanic is the game's thesis, and the game's music was composed on a laptop by one person.",
     "Play the first area and notice the mercy — the pacifist path is the design. The genius is that the violence is the choice."),
    ("Hades", 2020, "Supergiant Games", ["Roguelike", "Action", "Story"], 240, 1,
     "The roguelike where death is the story — the 'escape attempts' are the narrative, and the game's characters remember your failures.",
     "Play your first few runs and notice the story — the deaths are the content. The genius is that the roguelike IS the narrative."),
    ("Stardew Valley", 2016, "ConcernedApe", ["Simulation", "Farming", "Indie"], 300, 1,
     "Built by one person over four years — the farming sim is a love letter to Harvest Moon, and the game's real content is the community of Pelican Town.",
     "Play the first season and notice the community — the town is the game. The genius is that the farming is the rhythm."),
    ("Animal Crossing: New Horizons", 2020, "Nintendo", ["Simulation", "Life", "Relaxing"], 300, 1,
     "The game that defined the pandemic lockdown — the real-time clock and island economy made it a cultural phenomenon, and the game's design philosophy is 'no pressure, ever'.",
     "Play the first few days and notice the real-time — the clock is the game. The genius is that the gentleness is the design."),
    ("Among Us", 2018, "Innersloth", ["Multiplayer", "Social Deduction", "Party"], 60, 1,
     "The social deduction game that exploded during lockdown — the game's 'emergency meeting' format became a genre, and the game's simple graphics are the point.",
     "Play a round and notice the social gameplay — the deduction is the game. The genius is that the simplicity is the design."),
    ("Fortnite", 2017, "Epic Games", ["Battle Royale", "Multiplayer", "Shooter"], 180, 1,
     "The battle royale that became a cultural platform — the building mechanic is the differentiator, and the game's live events (concerts, crossovers) made it a metaverse.",
     "Play a match and notice the building — the mechanic is the game. The genius is that the live events are the culture."),
    ("League of Legends", 2009, "Riot Games", ["MOBA", "Multiplayer", "Strategy"], 240, 1,
     "The game that made esports mainstream — the 'MOBA' genre was defined by it, and the game's champion roster (160+) is the deepest character design in gaming.",
     "Play a match and notice the roles — the team composition is the strategy. The genius is that the champions are the depth."),
    ("World of Warcraft", 2004, "Blizzard", ["MMORPG", "Fantasy", "Multiplayer"], 360, 1,
     "The MMO that made online worlds mainstream — the game's 'dance' and 'leeroy jenkins' moments became internet history, and the game's community is its real content.",
     "Play the starting zone and notice the world — the community is the game. The genius is that the scale is the design."),
    ("StarCraft", 1998, "Blizzard", ["RTS", "Sci-Fi", "Strategy"], 240, 1,
     "The RTS that defined competitive gaming — the game's balance (Protoss/Zerg/Terran) is still studied, and the game made South Korean esports a national sport.",
     "Play the first mission and notice the factions — the asymmetry is the design. The genius is that the balance is the esport."),
    ("Civilization VI", 2016, "Firaxis", ["Strategy", "4X", "Historical"], 360, 1,
     "The 'one more turn' game — the tech tree and district system are the design, and the game's real content is the history it teaches.",
     "Play the first era and notice the districts — the placement is the strategy. The genius is that the history is the content."),
    ("Age of Empires II", 1999, "Ensemble Studios", ["RTS", "Strategy", "Historical"], 240, 1,
     "The RTS that is still played competitively 25 years later — the game's 'wololo' (conversion) meme is internet history, and the game's campaigns are history lessons.",
     "Play the William Wallace campaign — it's the tutorial. The genius is that the history is the content."),
    ("Diablo II", 2000, "Blizzard", ["Action RPG", "Loot", "Dark Fantasy"], 360, 1,
     "The game that invented the loot ARPG genre — the 'item hunt' is the game, and the game's rune system created an economy still alive today.",
     "Play the first act and notice the loot — the drops are the game. The genius is that the item hunt is the depth."),
    ("Journey", 2012, "thatgamecompany", ["Adventure", "Art", "Multiplayer"], 90, 1,
     "The art game that made games 'art' — the anonymous co-op (you meet strangers without names) is the design, and the game's emotional ending is a thesis on connection.",
     "Play through once without rushing — the companion is the game. The genius is that the anonymity is the design."),
    ("Disco Elysium", 2019, "ZA/UM", ["RPG", "Mystery", "Narrative"], 300, 1,
     "The RPG with no combat — the 'skills' are voices in your head, and the game's political dialogues are the actual gameplay.",
     "Play the first day and notice the skills — the internal voices are the game. The genius is that the dialogue is the combat."),
    ("Baldur's Gate 3", 2023, "Larian Studios", ["RPG", "Fantasy", "Strategy"], 360, 1,
     "The CRPG that won Game of the Year 2023 — the game's reactivity (every choice matters) is the design, and the game's companion romances became cultural moments.",
     "Play the first act and notice the choices — the dice are the tension. The genius is that the freedom is the design."),
    ("Cyberpunk 2077", 2020, "CD Projekt Red", ["RPG", "Sci-Fi", "Open World"], 360, 1,
     "The game that launched broken and was fixed into a masterpiece — the 2.0 update and Phantom Liberty DLC redeemed it, and the game's world design is the best realized cyberpunk in games.",
     "Play the opening act and notice the world — the city is the character. The genius is that the redemption is the story."),
    ("Persona 5", 2016, "Atlus", ["RPG", "Social", "Stylish"], 360, 1,
     "The stylish JRPG about rebellious teens — the 'phantom thieves' frame is the design, and the game's calendar system (days matter) is the tension.",
     "Play the first palace and notice the calendar — the time is the resource. The genius is that the style is the substance."),
    ("Sekiro: Shadows Die Twice", 2019, "FromSoftware", ["Action", "Samurai", "Challenging"], 300, 1,
     "The FromSoftware game that replaced rolls with parries — the 'posture' system is the design, and the game won Game of the Year 2019.",
     "Play the first boss and notice the posture — the parry is the game. The genius is that the duel is the design."),
    ("Doom Eternal", 2020, "id Software", ["FPS", "Action", "Fast"], 180, 1,
     "The FPS where you're the demon — the 'glory kill' and resource loop (you must kill to heal) is the design, and the game's combat is a puzzle.",
     "Play the first level and notice the loop — the kills are the resources. The genius is that the aggression is the design."),
    ("Papers, Please", 2013, "Lucas Pope", ["Simulation", "Moral", "Indie"], 120, 1,
     "The border guard simulation — the 'glory to Arstotzka' bureaucracy is the game, and the moral choices are the real content.",
     "Play your first day and notice the rules — the bureaucracy is the game. The genius is that the morality is the tension."),
]


def _slug(text):
    text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "topic"


def _build(file_name, category_id, subtype, verb, rows):
    path = ASSETS / file_name
    existing = json.loads(path.read_text(encoding="utf-8")) if path.exists() else []
    existing_ids = {t["id"] for t in existing}
    seen_names = {t["name"] for t in existing}
    added = 0
    for (name, year, creator, tags, duration, tier, teaser, instruction) in rows:
        display = f"{name} ({year})" if year else name
        if display in seen_names:
            continue
        base = f"{subtype.lower()}-{_slug(name)}"
        tid = base
        n = 2
        while tid in existing_ids:
            tid = f"{base}-{n}"
            n += 1
        existing_ids.add(tid)
        seen_names.add(display)
        full_tags = list(tags)
        if year and not any(t.endswith("s") and t[:-1].isdigit() for t in full_tags):
            full_tags.append(f"{year // 10 * 10}s")
        existing.append({
            "id": tid,
            "categoryId": category_id,
            "subtype": subtype,
            "name": display,
            "teaser": teaser,
            "imageUrl": "",
            "byline": creator,
            "exploreAction": {
                "verb": verb,
                "targetName": f"{name} ({year}) end-to-end" if year else f"{name}",
                "durationMinutes": duration if duration else 60,
                "instruction": instruction,
            },
            "tags": full_tags,
            "tier": tier,
        })
        added += 1
    path.write_text(json.dumps(existing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{file_name}: +{added} (total {len(existing)})")


def main():
    _build("songs.json", "SONGS", "Song", "Listen", SONGS)
    _build("series.json", "SERIES", "Series", "Watch", SERIES)
    _build("games.json", "GAMES", "Game", "Play", GAMES)


if __name__ == "__main__":
    main()
