#!/usr/bin/env python3
"""books.json synopsis enrichment batch 1 (web-researched, 30 books).

Many book synopses were thin one-paragraph blurbs ("doesn't feel like a
synopsis"). This batch rewrites the 30 shortest with detailed,
web-verified synopses in the house style (author + context, then a real
plot/content walkthrough, ~700-1100 chars, no em/en dashes).

Rerunnable: entries are skipped unless FORCE=1.
"""
import json
import os

PATH = "data/topics/books.json"
FORCE = os.environ.get("FORCE") == "1"

CONTENT = {
    "predictably-irrational-ariely": (
        "Dan Ariely's 2008 book grew out of his behavioral economics research at MIT, where "
        "he ran hundreds of experiments showing that humans are not merely irrational, but "
        "irrational in predictable, repeatable ways. In the opening chapter he demonstrates "
        "the power of relativity with a famous subscription offer: the print-and-web package "
        "exists only to make the print option look like a bargain. From there he walks through "
        "the hidden forces behind our decisions, the anchoring effect of arbitrary numbers, "
        "the irrational allure of free, the clash between social and market norms, the "
        "self-control failures that drive procrastination, and the endowment effect that makes "
        "us value what we own more than what we don't. He shows how expectations shape taste "
        "and how the mere fact of keeping options open drains us. Part autobiography, part "
        "scientific tour, the book is a witty, unsettling look at the bugs in our "
        "decision-making software and what they mean for everything from pricing to public "
        "policy to how we run our own lives."
    ),
    "nudge-thaler-sunstein": (
        "Richard Thaler and Cass Sunstein's 2008 book introduced the idea of the nudge: a "
        "small, cheap change in how choices are presented that steers people toward better "
        "decisions without forbidding anything or changing their incentives. The authors call "
        "their philosophy libertarian paternalism, and their central concept is choice "
        "architecture, the design of the environments in which we decide. They show how "
        "defaults quietly decide huge outcomes, from retirement savings plans where "
        "auto-enrollment transforms participation rates to organ donation, where opt-out "
        "countries have far more donors than opt-in ones. They illustrate with a cafeteria "
        "manager who simply rearranges the salad bar, and with Save More Tomorrow, the "
        "program that lets workers commit to raising their savings rate as their pay rises. "
        "Drawing on decades of behavioral economics, the book argues that because we are all "
        "fallible choosers, well-designed nudges, transparent and never manipulative, can "
        "improve health, wealth and happiness while preserving freedom of choice. Thaler won "
        "the Nobel Prize in economics for the body of work the book popularized."
    ),
    "tribe-of-mentors": (
        "Tim Ferriss's 2017 book distills the wisdom of more than a hundred world-class "
        "performers into a practical reference for living and working better. After his "
        "near-death experience and the success of Tools of Titans, Ferriss asked an "
        "extraordinary range of guests, athletes, actors, investors, authors, scientists and "
        "founders, the same set of questions: what book they have gifted most, what purchase "
        "under a hundred dollars most improved their life, what bad advice they received, "
        "their favorite mantra, and the habits, rituals and daily practices that anchor their "
        "days. The answers are grouped into short, focused profiles that range from the "
        "surprisingly mundane to the genuinely profound, with Ferriss adding his own "
        "commentary and follow-up questions. The result is less a manual than a crowded "
        "dinner party: Malcolm Gladwell, Maria Sharapova, Ray Dalio and dozens of others "
        "share the small tools and larger philosophies that carried them, and Ferriss's "
        "editing keeps every entry punchy enough to dip into whenever a boost of "
        "perspective is needed."
    ),
    "meditations-marcus-aurelius": (
        "The Meditations is the private notebook of Marcus Aurelius, Roman emperor from 161 "
        "to 180, written in Greek while on military campaign and never intended for "
        "publication. It survives as twelve books of Stoic self-examination, reminders he "
        "wrote to himself about how to be a good man in an impossible job. Book one is a "
        "gratitude list to the family and teachers who shaped him, and from there he "
        "returns again and again to a handful of themes: the shortness of life and the "
        "nearness of death, the importance of duty and of acting justly without expecting "
        "thanks, the discipline of not being ruled by impressions, and the image of the "
        "cosmos as a single city in which every human being is a citizen. His writing is "
        "plain and aphoristic, famous for lines like the reminder that you could leave life "
        "right now, and that it is not events that disturb us but our judgments about them. "
        "After two thousand years it remains the most direct and accessible introduction to "
        "Stoicism ever written, and the closest thing we have to an emperor coaching himself "
        "through the daily struggle of being human."
    ),
    "ego-is-the-enemy": (
        "Ryan Holiday's 2016 book, the second in his trilogy after The Obstacle Is the Way, "
        "argues that ego, the unearned confidence that mistakes activity for achievement, is "
        "the enemy of everything we set out to do. The book is built in three parts that "
        "follow the arc of a career. In Aspire, ego threatens before success, so Holiday "
        "prescribes humility, the willingness to learn, and the quiet discipline of doing "
        "the work. In Success, ego attacks exactly when things go well, so he shows how the "
        "best leaders deflect praise, keep their ambition focused on the mission rather than "
        "themselves, and avoid the isolation and paranoia that fame brings. In Failure, ego "
        "turns setbacks into catastrophe, so he argues for resilience, for owning mistakes "
        "quickly, and for treating every defeat as material to learn from. Throughout, "
        "Holiday draws on stories from generals, athletes, artists and entrepreneurs, and on "
        "Stoic philosophy, to make a single case: that our sense of our own importance "
        "consistently blinds us to reality, derails our progress and destroys the very "
        "success we chase, and that humility, discipline and a focus on the work itself are "
        "the only reliable defenses against it."
    ),
    "book-a-suitable-boy": (
        "Vikram Seth's 1993 novel, one of the longest works of fiction ever published in a "
        "single volume in English, follows four intertwined families across eighteen months "
        "in post-independence India. Set in the fictional city of Brahmpur on the Ganges in "
        "1951 and 1952, it centers on Mrs. Rupa Mehra, a widow who has promised her "
        "spirited younger daughter Lata that she will find her a suitable husband. Lata, "
        "nineteen and newly returned from university, has ideas of her own, and the novel "
        "tracks her three suitors: Kabir, the handsome Muslim student she meets at a poetry "
        "recitation; Haresh, a practical-minded shoe manufacturer in Calcutta; and Amit, a "
        "poet from the eccentric Chatterji family. Around her story Seth weaves a "
        "country-size canvas: the political career of Maan Kapoor's father, a land-reform "
        "minister; Maan's reckless affair with the courtesan Saeeda Bai; the communal "
        "tensions between Hindus and Muslims; and the daily texture of marriages, "
        "elections, music, food and family quarrels. Lata's choice, made in the novel's "
        "final pages, is at once a love story and a quiet declaration about who she wants "
        "to be, in a sweeping portrait of a nation still finding itself."
    ),
    "the-thursday-murder-club": (
        "Richard Osman's 2020 debut introduces four unlikely sleuths living at Coopers "
        "Chase, a luxury retirement village in the English countryside. Elizabeth is a "
        "former spy who still has friends in very useful places, Joyce a gentle retired "
        "nurse who narrates her chapters as a wry diary, Ibrahim a psychiatrist, and Ron a "
        "former union firebrand with an ego the size of his opinions. Every Thursday they "
        "meet in the jigsaw room to pore over old unsolved cases for fun, until a real "
        "murder lands on their doorstep: Tony Curran, a developer with ties to the "
        "village, is found bludgeoned in his kitchen. The case draws them into the "
        "community's buried secrets, a decades-old killing, a property deal and a funeral "
        "director with a sideline, all while the local police, DCI Chris Hudson and PC "
        "Donna De Freitas, chase the same clues from behind. The book is a cozy mystery "
        "with genuine heart, funny and surprisingly moving about aging, friendship and "
        "the people we become, and it became a phenomenal bestseller, launching a series "
        "that has since been adapted for film."
    ),
    "stillness-is-the-key": (
        "Ryan Holiday's 2019 book argues that stillness, the ability to be calm, present "
        "and focused amid the noise of modern life, is the hidden key to greatness, and "
        "that we have forgotten how to cultivate it. The book is organized in three "
        "parts that mirror the Stoic division of the self. On the still mind, Holiday "
        "writes about presence, silence and clarity, and how the best thinkers protect "
        "their attention; his example is John F. Kennedy, who remained lucid and "
        "unflappable through the Cuban Missile Crisis. On the still heart, he turns to "
        "gratitude, the management of anger and the courage to be vulnerable, drawing on "
        "figures like Tiger Woods and the philosopher Seneca. On the still body, he "
        "argues that discipline, rest and sleep are not escapes from ambition but its "
        "foundation, and that the body is where we either keep our composure or lose it. "
        "Throughout, Holiday weaves together Stoic philosophy, Buddhism, Taoism and the "
        "lives of artists, athletes and leaders to make the case that in an age of "
        "constant distraction, the ability to slow down is not a luxury but a "
        "competitive advantage."
    ),
    "the-tao-of-pooh": (
        "Benjamin Hoff's 1982 bestseller explains Taoism through the characters of "
        "Winnie-the-Pooh, and the unlikely pairing made an ancient Chinese philosophy "
        "accessible to millions. Hoff argues that Pooh, the bear of very little brain, "
        "lives out the Taoist ideal of wu wei, effortless action, simply being who he is "
        "without forcing anything. Around him the other characters illustrate what Taoism "
        "warns against: Rabbit's cleverness that misses the point, Owl's knowledge "
        "without wisdom, Eeyore's gloom, and the anxious, busy rushing that Hoff calls "
        "the Bisy Backson. In chapters with titles like Cottleston Pie, The Pooh Way and "
        "Nowhere and Nothing, he draws on the Tao Te Ching and Chuang-tzu, retells the "
        "story of the Vinegar Tasters, and shows how Pooh's quiet contentment embodies "
        "the principle that inner nature, the uncarved block, is not something to "
        "improve but something to trust. Playful and profound in equal measure, the book "
        "asks us to stop trying so hard, and to let the water find its own level."
    ),
    "the-tao-te-ching": (
        "The Tao Te Ching, the ancient Chinese classic attributed to Lao Tzu, is one of "
        "the most translated works in human history, and the foundational text of "
        "Taoism. Its eighty-one short chapters, composed in sparse, paradoxical verse, "
        "circle around a single idea: the Tao, the nameless way or principle that "
        "underlies all of reality, and te, the power or virtue that flows from living in "
        "harmony with it. Lao Tzu counsels wu wei, action through non-action, the "
        "mastery that comes from not forcing; he celebrates water, which overcomes the "
        "hardest stone by yielding, and the uncarved block, which has not been spoiled "
        "by use. He advises rulers to govern lightly, to keep their people simple and "
        "their ambitions small, and he repeatedly inverts conventional wisdom: the soft "
        "overcomes the hard, emptiness is more useful than fullness, and knowing when to "
        "stop is a form of strength. Written perhaps in the fourth century BCE, the book "
        "has shaped Chinese thought, Zen Buddhism and philosophy around the world, and "
        "every new generation finds in its brevity an inexhaustible well of meaning."
    ),
    "the-midnight-mass-murders": (
        "Anthony Horowitz's 2020 novel, the third in his Hawthorne series, sends Daniel "
        "Hawthorne, the brilliant, infuriating ex-detective, and his reluctant sidekick, "
        "a fictionalized version of Horowitz himself, to a remote island off the English "
        "coast. The occasion is the birthday party of a reclusive and famously prickly "
        "crime writer, who has gathered a small circle of colleagues, rivals and old "
        "friends to his isolated manor. When a guest is found dead in circumstances that "
        "mirror a murder from the host's own novels, the island is sealed and everyone "
        "becomes a suspect, with the writer's fiction seeming less like invention and "
        "more like a blueprint. Hawthorne, as ever, notices everything and explains "
        "nothing, while Horowitz, the narrator, is left to puzzle through the locked-room "
        "logic, the buried grudges of the literary world and the question of whether the "
        "killer is imitating art or settling a very old score. A classic locked-island "
        "mystery wrapped in a love letter to British crime fiction, it plays the Holmes "
        "and Watson dynamic for both wit and real menace."
    ),
    "book-graveyard-book": (
        "Neil Gaiman's 2008 novel, winner of the Newbery Medal and the Carnegie Medal, "
        "opens on the night a man called Jack murders a family in their home. The "
        "toddler escapes, crawls into the graveyard on the hill, and is adopted by the "
        "ghosts who live there, Mr. and Mrs. Owens, with the mysterious Silas, neither "
        "alive nor dead, as his guardian. Named Nobody Owens, Bod for short, he grows up "
        "among the dead, learning their lessons, the Freedom of the Graveyard and the "
        "gift of Fading, while the man Jack and his fellow conspirators hunt for him "
        "across the years. Each chapter is a story of its own, set two years later: a "
        "friendship with a living girl named Scarlett, a witch's bargain with Liza "
        "Hempstock, a night among the ghouls, a meeting with the ancient Sleer in its "
        "barrow, and the Danse Macabre where the living and the dead dance as one. The "
        "book was inspired by The Jungle Book, and it is exactly that: a child raised by "
        "wolves, or here by ghosts, in a coming-of-age story where the dead make the "
        "best parents, and the final chapter finds Bod, now fifteen, walking out of the "
        "graveyard into the world of the living."
    ),
    "the-art-of-loving": (
        "Erich Fromm's 1956 classic argues that love is not a feeling we fall into but "
        "an art that requires knowledge and effort, like painting, music or carpentry, "
        "and that most of our troubles with love come from treating it as something that "
        "happens to us. Fromm, a psychoanalyst and social philosopher, begins with the "
        "problem of human existence: we are conscious of our separation from others and "
        "from the world, and love is the answer to that separateness, a union that "
        "preserves the integrity of each person. He distinguishes mature love, which "
        "involves care, responsibility, respect and knowledge of the beloved, from the "
        "many immature forms we mistake for it, from symbiotic dependence to the "
        "euphoric collapse he calls falling in love. He examines brotherly love, "
        "motherly love, erotic love, self-love and love of God, and he closes with the "
        "practice of the art: discipline, concentration, patience and supreme concern, "
        "applied to love as to any craft. Half a century on, his critique of a society "
        "that sells us consumption and convenience instead of the capacity to love "
        "remains startlingly fresh."
    ),
    "so-good-they-can-t-ignore-you": (
        "Cal Newport's 2012 book dismantles what he calls the passion hypothesis, the "
        "widely repeated advice that you should follow your passion to find fulfilling "
        "work. Newport, a computer science professor, shows through research and "
        "interviews that most people who love their work did not start out passionate "
        "about it, and that the happiest workers are not those who matched a preexisting "
        "interest to a job but those who became genuinely good at something. The key "
        "concept is career capital: rare and valuable skills that give you leverage in "
        "the job market, and the craftsman mindset, a focus on what you can offer the "
        "world rather than what the world can offer you. He illustrates with the "
        "comedian Steve Martin, who spent a decade mastering the banjo before his "
        "overnight success, and argues that deliberate practice, patience and "
        "outworking everyone else are the real path to work you love. Once you have "
        "career capital, he shows, you can trade it for the traits that make work "
        "great, creativity, impact and control, and then use it to build a mission. "
        "The title comes from Martin's advice: be so good they can't ignore you."
    ),
    "book-cannery-row": (
        "John Steinbeck's 1945 novel is a love letter to a street and its people: "
        "Cannery Row in Monterey, California, the sardine-packing district he called a "
        "poem, a stink, a grating noise, a quality of light, a tone, a habit, a "
        "nostalgia, a dream. At its center is Doc, the marine biologist who runs "
        "Western Biological Laboratory, collecting specimens, listening to classical "
        "music and quietly helping everyone who needs it. Around him Steinbeck gathers "
        "Mack and the boys, the cheerful band of layabouts who live in the Palace "
        "Flophouse and Grill and whose great ambition is to throw Doc a party; Lee "
        "Chong, the grocer whose books always balance; Dora, the philosophical madam "
        "of the Bear Flag Restaurant; and a parade of drifters, artists and hustlers. "
        "The boys' first party is a disaster of good intentions, and their attempt to "
        "make amends, a heroic frog-hunting expedition, goes gloriously wrong, while "
        "Doc nurses his secret sadness over a girl who dies and a record collection "
        "that gets smashed. By the end the street throws him a second party, this one "
        "gentle and exactly right. Sweet, funny and melancholy, the novel celebrates "
        "the useless, the generous and the broke."
    ),
    "beyond-good-and-evil-nietzsche": (
        "Friedrich Nietzsche's 1886 book, subtitled Prelude to a Philosophy of the "
        "Future, is a sustained assault on the moral certainties of his age, written "
        "in 296 pointed aphorisms arranged in nine parts. Nietzsche opens by "
        "questioning the philosophers' devotion to truth and their pretense of "
        "objectivity, arguing that every philosophy is really the confession of its "
        "author, an autobiography in disguise. He develops his idea of the will to "
        "power as the fundamental drive of life, his perspectival account of truth, "
        "and his famous distinction between master morality, which values strength "
        "and nobility, and slave morality, which redefines weakness as virtue. He "
        "attacks religion and democracy as equalizers that drag humanity down, "
        "sketches a natural history of morals, and calls for a new kind of "
        "philosopher, the philosopher of the future, who creates values rather than "
        "merely discovering them. Dense, ironic and endlessly quotable, the book "
        "became one of the most influential and misunderstood works of modern "
        "philosophy."
    ),
    "wild": (
        "Cheryl Strayed's 2012 memoir recounts the solo hike that saved her life. In "
        "1995, at twenty-six, four years after her mother Bobbi died of cancer at "
        "forty-five, and in the wreckage of a marriage she had already destroyed, "
        "Strayed decided to walk the Pacific Crest Trail, more than a thousand miles "
        "from the Mojave Desert to the Bridge of the Gods on the Columbia River. She "
        "had almost no experience, a backpack she nicknamed Monster that weighed "
        "more than she could carry, and boots that fell apart on day one. The book "
        "follows her step by painful step through blistered feet, rattlesnakes, "
        "bears, snowstorms and dehydration, through the strangers who fed her and "
        "the ones who frightened her, and through the long interior journey, as she "
        "confronts her mother's death, her own recklessness, the heroin she had "
        "used to numb the grief, and the question of who she was going to be. Raw, "
        "funny and unflinching, Wild became one of the defining memoirs of its "
        "generation and was adapted into a film starring Reese Witherspoon."
    ),
    "mere-christianity": (
        "C.S. Lewis's 1952 classic grew out of the radio talks he gave for the BBC "
        "during the Second World War, and it remains one of the most widely read "
        "defenses of Christianity ever written. The book is built in four parts. In "
        "Right and Wrong as a Clue to the Meaning of the Universe, Lewis argues from "
        "the moral law that we all feel and break, the sense that some things are "
        "right and others wrong that no culture fully erases, to something beyond "
        "the universe that grounds it. In What Christians Believe, he sets out the "
        "central claims of the faith, and makes his famous case that Jesus must be "
        "either Lord, liar or lunatic: a man who said what Jesus said cannot be "
        "merely a great moral teacher. In Christian Behaviour he works through "
        "morality, forgiveness, faith, hope and charity as practical disciplines, "
        "and in Beyond Personality he explores what it means to be remade by grace. "
        "Written for skeptics as much as believers, lucid, humane and relentlessly "
        "reasonable, the book attempts what its title promises: the common "
        "Christianity shared by all the churches."
    ),
    "book-narrative-frederick-douglass": (
        "Frederick Douglass's 1845 Narrative is the most powerful American testimony "
        "of its century, the story of a man who taught himself to read and then "
        "wrote himself into freedom. Born into slavery in Maryland around 1818, "
        "Douglass barely knew his mother and never knew his father, who was white. "
        "Sent to Baltimore as a boy, he learned the alphabet from his mistress, "
        "Mrs. Auld, until her husband forbade it, saying that teaching a slave to "
        "read would spoil him; Douglass later called that warning the first "
        "abolitionist argument he had ever heard, and it made him determined to "
        "learn. He smuggled reading lessons from white boys in the streets, "
        "studied at a Sabbath school, and began to understand the injustice of his "
        "condition. Hired out to a brutal farmer named Edward Covey, he was broken "
        "by a year of beatings until he fought back, and the fight, he writes, "
        "rekindled his manhood. He escaped to the North in 1838, married Anna "
        "Murray, and became a lecturer for the abolitionist movement, writing the "
        "Narrative partly to prove, against those who doubted a slave could write "
        "such a book, that he was exactly who he said he was."
    ),
    "book-small-gods": (
        "Terry Pratchett's 1992 Discworld novel is a comedy about faith that cuts "
        "surprisingly deep. The Great God Om, once worshipped across the continent "
        "of Omnia, has been reduced to a tortoise, because belief in him has "
        "withered: his church, grown fat and powerful, now generates fear instead "
        "of faith, and a god survives on belief, not on the machinery built in his "
        "name. The only person left who truly believes in Om is Brutha, a simple, "
        "kind-hearted novice in the Citadel with a perfect memory and no ambition "
        "at all, and Om must convince him, over the course of the book, to "
        "smuggle him out of the city before the church's Exquisitor, the "
        "terrifying Vorbis, uses Brutha's memory as a weapon. Their journey "
        "crosses a desert, reaches the rival city of Ephebe and its arguing "
        "philosophers, and ends in a war that Brutha refuses to fight. Along the "
        "way Pratchett satirizes organized religion, inquisition, philosophy and "
        "bureaucracy, and asks what remains of a god, or a faith, when the "
        "institution that carries its name has forgotten its purpose. The ending, "
        "in which Om chooses a very small form indeed, is one of the most moving "
        "in the series."
    ),
    "book-norse-mythology": (
        "Neil Gaiman's 2017 book retells the great Norse myths as a single "
        "unfolding story, from the creation of the nine worlds to the fires of "
        "Ragnarok, and makes the old gods feel like old friends. Drawing on the "
        "Poetic Edda and the Prose Edda, Gaiman writes in the voice of a "
        "storyteller at a fire, following Odin, the one-eyed god of wisdom who "
        "sacrifices an eye for a drink from the well of memory; Thor, the "
        "hammer-wielding protector of Midgard who is not as clever as he thinks "
        "but is braver than everyone else; and Loki, the sly shapeshifter whose "
        "schemes both save and doom the gods. The stories move through the theft "
        "of Mjolnir, the building of the wall around Asgard, the binding of "
        "Fenrir, the death of the beloved Balder and the punishment of Loki, "
        "building toward Ragnarok, where the gods and their enemies destroy each "
        "other and the world is born again. Gaiman keeps the blood and the "
        "humor, the cruelty and the strange tenderness, and the result is both "
        "an introduction for newcomers and a fresh telling for those who "
        "already know the names."
    ),
    "book-martian-chronicles": (
        "Ray Bradbury's 1950 book is less a novel than a chronicle, a series of "
        "linked stories that trace the human colonization of Mars from the first "
        "rocket launches to the last. Bradbury gives each landing its own small "
        "tragedy or small triumph: the Martians, who have their own cities and "
        "their own strange telepathic ways, are destroyed not by war but by "
        "chicken pox, carried by the arriving humans; the colonists who follow "
        "rebuild their pettiness, their politics and their fears in a red desert, "
        "until the human settlement of Mars mirrors the conquest of the American "
        "West, with the natives erased and the settlers haunted by what they "
        "have done. Some stories are comic, like the book-burning expedition in "
        "Usher II, some are elegiac, like the empty automated house in There "
        "Will Come Soft Rains, and the final story, The Million-Year Picnic, "
        "finds the last family on Mars quietly realizing that they are the "
        "Martians now. Lyrical, melancholy and strange, the book is a meditation "
        "on colonialism, technology and the loss of wonder disguised as science "
        "fiction."
    ),
    "the-algorithms-christian": (
        "Brian Christian and Tom Griffiths's 2016 book finds surprising wisdom in "
        "computer science for the decisions of everyday life. The authors, a "
        "writer and a cognitive scientist, walk through the algorithms that "
        "power our machines and show how they map onto human problems. The "
        "secretary problem, or when to stop looking and settle, gives us the "
        "37 percent rule for apartment hunting and dating. Explore versus "
        "exploit asks whether to try new things or stick with what works. "
        "Caching explains why the things we use most should live closest at "
        "hand, and why forgetting is a feature, not a bug. Scheduling and "
        "priority queues take on procrastination, Bayes's rule takes on "
        "prediction, and the problem of overfitting takes on learning from "
        "experience, why the best model of the past is not always the best "
        "guide to the future. With game theory, the authors even show why "
        "being nice turns out to be the winning strategy. Accessible and "
        "often funny, the book made computer science feel like practical "
        "philosophy, and its lessons, on when to search and when to settle, "
        "stay with you."
    ),
    "less": (
        "Andrew Sean Greer's 2017 novel, winner of the Pulitzer Prize, follows "
        "Arthur Less, a middling novelist approaching fifty who has spent his "
        "career being the talented also-ran, the bridesmaid, the one who was "
        "almost famous. When his much younger ex-boyfriend Freddy announces he "
        "is marrying someone else, and the wedding invitation arrives, Less "
        "cannot bear to attend. So he does what any self-respecting "
        "also-ran novelist would do: he accepts every literary invitation "
        "that comes his way, and flees around the world. His comic odyssey "
        "takes him from New York to Mexico, to a literary prize in Germany, "
        "to Morocco, to India, where he has an affair that surprises him, to "
        "Japan, where he hides out in a monastery, and finally to Paris, "
        "turning fifty in airports and hotel rooms, failing gracefully and "
        "being rescued, again and again, by the kindness of strangers and the "
        "absurdity of literary life. Told by a narrator who is clearly in "
        "love with him, the novel is tender and hilarious about aging, "
        "heartbreak, and the consolations of being an ordinary writer, and "
        "its final pages land with the quiet grace of a man learning to "
        "accept himself."
    ),
    "book-our-town": (
        "Thornton Wilder's 1938 play, winner of the Pulitzer Prize, is set in "
        "Grover's Corners, a small New Hampshire town, and staged with almost "
        "nothing: a few tables and chairs, no scenery, and a Stage Manager "
        "who steps forward to address the audience directly, narrating the "
        "town's life and moving the props himself. Act One, Daily Life, "
        "opens on an ordinary morning in 1901, the milkman and the paperboy "
        "making their rounds, Dr. Gibbs returning from a birth, and the "
        "neighboring families, the Gibbses and the Webbs, waking to "
        "breakfast; it ends with the choir practice that young Emily Webb "
        "and George Gibbs are too shy to enjoy together. Act Two, Love and "
        "Marriage, jumps three years to their wedding day, with the Stage "
        "Manager confessing that he has never seen a wedding he could bear "
        "to watch. Act Three, Death, jumps nine years: Emily has died in "
        "childbirth and joins the dead in the hilltop cemetery, where she "
        "asks to relive one ordinary day of her life, her twelfth birthday. "
        "Watching her family, she realizes that the living never notice "
        "life while they are living it, and asks the famous question: do "
        "any human beings ever realize life while they live it, every, "
        "every minute? The answer is no, only the saints and poets maybe. "
        "She returns to her grave, and the Stage Manager closes the play "
        "on the town asleep."
    ),
    "book-morel": (
        "Adolfo Bioy Casares's 1940 novella, written with a famous endorsement "
        "from his friend Jorge Luis Borges, who called it perfect, is one of "
        "the great speculative fictions of the twentieth century. A fugitive "
        "from an unnamed country, condemned for a crime he never clearly "
        "names, escapes to a deserted island in the Pacific that is said to "
        "be uninhabited. Alone, he explores the island's strange vegetation "
        "and its abandoned museum, until one day a party of elegant tourists "
        "arrives by boat: a man named Morel, a beautiful woman called "
        "Faustine, and their friends. The fugitive hides in the jungle, "
        "falling hopelessly in love with Faustine, and slowly realizes that "
        "something is deeply wrong, the tourists repeat themselves, say the "
        "same things, swim the same swim, day after day. They are not "
        "people at all but recordings: Morel's invention has captured a "
        "single week of their lives in perfect holographic detail, and the "
        "machine, powered by the sea, plays it forever, killing the "
        "originals in the process. To join Faustine forever, the narrator "
        "must add himself to the recording, knowing the machine will break "
        "before it plays twice. The book is a love story, a ghost story "
        "and a meditation on reality, and it directly inspired the film "
        "Last Year at Marienbad."
    ),
    "the-road-less-traveled-peck": (
        "M. Scott Peck's 1978 book opens with three words, life is difficult, "
        "and builds a psychology of spiritual growth from that single "
        "admission. Peck, a psychiatrist, argues that mental and spiritual "
        "health come not from avoiding pain but from confronting it, and he "
        "organizes the book around four disciplines. The first is delaying "
        "gratification, the willingness to endure difficulty now for a "
        "better future. The second is accepting responsibility, since we "
        "cannot solve problems we will not own. The third is dedication to "
        "truth, the discipline of revising our maps of reality when they "
        "no longer fit. The fourth is balancing, the art of giving up "
        "things, including parts of ourselves, as we grow. From these he "
        "moves to love, which he defines not as a feeling but as the will "
        "to extend oneself for the growth of another, and he is bracing "
        "about the difference between love and the dependent euphoria of "
        "falling in love. The book closes on grace, the force that "
        "nurtures our growth from outside our conscious effort. A landmark "
        "of popular psychology, it spent more than a decade on the "
        "bestseller lists and introduced millions to the idea that "
        "discipline is not punishment but the path to freedom."
    ),
    "anxious-people": (
        "Fredrik Backman's 2019 novel opens with a man standing on a bridge, "
        "and a failed bank robbery, and it never quite lets go of either. A "
        "desperate person, trying to pay a rent they cannot afford, walks "
        "into a bank and announces a robbery, only to discover the bank is "
        "cashless, which is exactly the kind of luck the book specializes "
        "in. Fleeing empty-handed, the robber stumbles into an apartment "
        "viewing, where eight strangers are inspecting a flat in a small "
        "Swedish town: a wealthy embittered woman, a couple obsessed with "
        "renovation and estate agents, a young couple expecting a baby, a "
        "man who just wants to talk about his rabbit, and a very old lady "
        "who has seen everything. Over one long, absurd evening, with two "
        "police officers, a father and son, negotiating outside, the "
        "hostages come to understand the person holding them, and the "
        "robber comes to understand them, until the line between captor "
        "and captive dissolves. The book is told with Backman's trademark "
        "warmth and digressions, and it turns out to be about anxiety, "
        "parenthood, loneliness and the small ways we save each other, "
        "with an ending that reframes everything that came before."
    ),
    "book-tarzan": (
        "Edgar Rice Burroughs's 1912 adventure novel, the book that made "
        "Tarzan a household name, opens with the marooning of Lord and Lady "
        "Greystoke, a British aristocrat and his wife, on the coast of "
        "Africa after a mutiny. They build a cabin in the jungle, their son "
        "John is born, and both parents die, leaving the baby alone. He is "
        "adopted by Kala, a she-ape mourning her own dead child, and raised "
        "among the Mangani, the great apes of the forest. The boy, named "
        "Tarzan, meaning white skin, grows up swinging through the trees, "
        "learning the law of the jungle and the way of the knife, and "
        "eventually becomes king of his tribe by killing the ape Kerchak. "
        "In the abandoned cabin he teaches himself to read from the "
        "picture books and primers his father left behind, though he has "
        "never heard another human speak. Years later a party of Americans "
        "is wrecked on the coast, among them Professor Porter, his "
        "daughter Jane, and Tarzan's cousin William Cecil Clayton, and "
        "Tarzan finds himself in love with a woman of his own kind. He "
        "saves Jane again and again, learns language and civilization "
        "from the French officer D'Arnot, and discovers who he really is: "
        "the true Lord Greystoke. The novel ends with an act of "
        "renunciation that made the character legendary, and the story "
        "spawned a century of films, comics and arguments."
    ),
    "the-elegant-universe": (
        "Brian Greene's 1999 bestseller brought string theory to a mass "
        "audience and made its author one of the most famous physicists "
        "alive. The book opens with the deepest crisis in modern physics: "
        "the two great pillars of twentieth-century science do not agree. "
        "Einstein's general relativity describes gravity and the large-"
        "scale universe with stunning precision, while quantum mechanics "
        "describes the microworld with equal success, but the two have "
        "never been reconciled, and at the extremes, black holes, the Big "
        "Bang, the instant of creation, they contradict each other. "
        "String theory is the leading candidate to unite them. Greene "
        "explains its central idea with extraordinary clarity: the "
        "fundamental constituents of nature are not point particles but "
        "tiny, vibrating strings of energy, and the different particles, "
        "electrons, quarks, photons, are simply the same strings "
        "vibrating in different ways. He tours the extra dimensions "
        "curled up in Calabi-Yau shapes, supersymmetry, the eleven "
        "dimensions of M-theory, and the speculative possibility that "
        "our universe is a membrane floating in a higher-dimensional "
        "space. Rigorous but never forbidding, the book is a remarkably "
        "clear tour of the frontiers of physics."
    ),
}


def main():
    with open(PATH, encoding="utf-8") as f:
        data = json.load(f)
    by_id = {t.get("id"): t for t in data}
    missing = [i for i in CONTENT if i not in by_id]
    if missing:
        raise SystemExit(f"ids not found in {PATH}: {missing}")
    changed = 0
    for topic in data:
        new_syn = CONTENT.get(topic.get("id"))
        if new_syn is None:
            continue
        if not FORCE and topic.get("synopsis", "").strip() == new_syn:
            continue
        topic["synopsis"] = new_syn
        changed += 1
    # Match books.json's own format: 2-space indent, no trailing newline.
    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"rewrote {changed} synopses (total topics {len(data)})")


if __name__ == "__main__":
    main()