#!/usr/bin/env python3
"""books.json synopsis enrichment batch 2 (web-researched, 30 books).

Continues batch 1: rewrites the next 30 shortest synopses with detailed,
web-verified synopses in the house style (author + context, then a real
plot/content walkthrough, ~900-1300 chars, no em/en dashes).

Rerunnable: entries already matching the new text are skipped unless
FORCE=1. Matches books.json's format (2-space indent, no trailing newline).
"""
import json
import os

PATH = "data/topics/books.json"
FORCE = os.environ.get("FORCE") == "1"

CONTENT = {
    "book-up-from-slavery": (
        "Booker T. Washington's 1901 autobiography tells the story of his rise "
        "from slavery to become the most powerful Black leader of his era. Born "
        "into slavery on a Virginia plantation around 1856, he was nine when "
        "emancipation came, and he describes the moment with unforgettable "
        "plainness: the slaves learning they were free, the great rejoicing, "
        "and the sudden responsibility of making a life. He worked in salt "
        "furnaces and coal mines as a boy, walked hundreds of miles to "
        "Hampton Institute, and passed the school's entrance test by "
        "cleaning a recitation room, a story he tells as proof that "
        "industry matters more than brilliance. In 1881 he was chosen to "
        "found a school for Black students in Tuskegee, Alabama, starting "
        "in a shanty with thirty students and building it, brick by "
        "brick, into a great institution of industrial education. The "
        "book includes his famous Atlanta Compromise speech of 1895, "
        "his friendship with white philanthropists, and his philosophy "
        "of self-help, thrift and practical skill, a doctrine that made "
        "him famous, controversial and, by the end of his life, "
        "unavoidable in American public life."
    ),
    "influence": (
        "Robert Cialdini's 1984 classic explains why we say yes, and why we "
        "sometimes say yes to things we later regret. Cialdini, a social "
        "psychologist, spent years going undercover in the world of "
        "compliance professionals, car dealers, fundraisers, salespeople "
        "and cult recruiters, and he found that influence runs through six "
        "principles. Reciprocity: we feel obliged to return favors, which "
        "is why free samples and small gifts work. Commitment and "
        "consistency: once we take a small stand, we pressure ourselves "
        "to act in line with it. Social proof: in uncertainty we copy "
        "others, which is why laugh tracks and long lines persuade us. "
        "Liking: we say yes to people we like, so salespeople find "
        "similarities and compliments. Authority: we defer to titles, "
        "uniforms and expertise, sometimes past all reason. Scarcity: "
        "what is rare feels valuable, which is why limited-time offers "
        "work. Each principle, Cialdini shows, is normally a useful "
        "shortcut, and each can be triggered automatically, and "
        "sometimes exploited, without our noticing. The book's "
        "practical defense is to recognize the triggers and ask "
        "whether the influence is legitimate."
    ),
    "book-little-house-on-the-prairie": (
        "Laura Ingalls Wilder's 1935 novel, the second in the Little House "
        "series, sends the Ingalls family west: Pa has heard the land in "
        "Kansas is open for settlement, so the family loads a covered wagon "
        "and leaves the woods of Wisconsin behind. Laura, four years old in "
        "the story, remembers the long journey across the plains, the fords "
        "and the tall grass, and the building of a new life on the prairie: "
        "Pa felling logs for a cabin, the well he digs with Mr. Scott, the "
        "chimney that catches fire while Pa is away, and the Christmas "
        "without presents, when Mr. Edwards wades the creek to bring the "
        "girls their tin cups and candy. The prairie itself is the other "
        "main character, the wolves howling at night, the great Indian "
        "jamboree gathering on the rise, the panther, and the constant "
        "loneliness of a family alone on the grass. When the government "
        "decides the land belongs to the Osage and the settlers must go, "
        "the family packs up again, and the book ends with them driving "
        "away, the little house left to the prairie. Warm, precise and "
        "unsentimental, it is the memory of a childhood made out of "
        "almost nothing."
    ),
    "the-freakonomics-levitt": (
        "Steven Levitt and Stephen Dubner's 2005 bestseller applies the "
        "tools of economics to questions no economist was supposed to "
        "touch, and the results are as entertaining as they are "
        "unsettling. Levitt, a University of Chicago economist, is less "
        "interested in money than in incentives, and the book is a tour "
        "of the hidden structures that shape behavior. Why did sumo "
        "wrestlers cheat? The data says some matches were fixed. Why did "
        "Chicago schoolteachers cheat on standardized tests? Because "
        "their pay depended on them. Who do real estate agents really "
        "work for, and why do they sell your house for less than their "
        "own? Why does the Ku Klux Klan have so much in common with "
        "real estate agents, and what does an undercover researcher "
        "learn about a crack gang's books, that the gang's foot "
        "soldiers earn less than minimum wage and the organization is "
        "run like a fast-food franchise? The book's most controversial "
        "chapter argues that the legalization of abortion in the 1970s "
        "explains much of the crime drop of the 1990s. Throughout, "
        "the authors' method is the same: follow the incentives, "
        "measure what people actually do, and let the numbers tell "
        "stories that conventional wisdom never would."
    ),
    "book-ocean-at-the-end-of-the-lane": (
        "Neil Gaiman's 2013 novella opens with an unnamed man in middle "
        "age returning to the village of his childhood for a funeral, and "
        "finding himself drawn to the farm at the end of the lane where "
        "the Hempstock women live, and to the pond that Lettie Hempstock "
        "always called an ocean. The memory that comes back is from when "
        "he was seven. A lodger at his family's house steals the family "
        "car, drives it into a pond and drowns himself, and the "
        "aftermath opens a door: the opal miner who died in the car had "
        "brought something back from a place where the world is thinner, "
        "and the something takes the shape of Ursula Monkton, a "
        "beautiful and terrifying woman who insinuates herself into the "
        "boy's home as his nanny. Only the Hempstocks, old Mrs. "
        "Hempstock, her daughter Ginnie and eleven-year-old Lettie, "
        "who are older than the world itself, understand what is "
        "happening. To save him, Lettie must take him through her "
        "ocean, to the other side and back, and the price she pays "
        "shapes the rest of his life. Tender and strange, the book "
        "is about childhood, memory and the debts we carry forever."
    ),
    "book-my-antonia": (
        "Willa Cather's 1918 novel is the story of Jim Burden, an orphan "
        "sent from Virginia to his grandparents' farm in Nebraska, and "
        "Antonia Shimerda, the bright-eyed daughter of Bohemian "
        "immigrants who arrive on the same train. On the vast, still "
        "prairie the two children become friends, and Cather's great "
        "subject is the land itself, the grass that covered the earth "
        "like a sea, and the people who broke it. Antonia's father, a "
        "gentle musician who cannot bear the strangeness of his new "
        "life, shoots himself in the barn, and the family is left to "
        "survive without him. Jim goes to the university and then to "
        "law, while Antonia works in town, is wooed, seduced and "
        "abandoned by a man who promises to marry her, and returns "
        "disgraced to her family's farm. The novel's last section "
        "finds her years later, worn but unbroken, married to a "
        "farmer named Anton Cuzak with a house full of children, "
        "and Jim recognizes that she has kept something the rest of "
        "them lost, a vigor and a rootedness in the land. A "
        "portrait of pioneer life that is also a meditation on "
        "memory and on the precious, incommunicable past, it is "
        "Cather's most loved book."
    ),
    "book-awakening": (
        "Kate Chopin's 1899 novel scandalized readers on publication and "
        "has never stopped being read since. Edna Pontellier is a "
        "respectable New Orleans wife and mother, on summer holiday with "
        "her husband Leonce and their sons at Grand Isle, a resort where "
        "the Creole society of the city relaxes and flirts. That summer "
        "she learns to swim, and the sensation of being in the water "
        "alone, far from shore, is her first taste of independence. She "
        "becomes infatuated with Robert Lebrun, the charming young man "
        "who attaches himself to married women every summer, and when "
        "he leaves for Mexico, her restlessness takes hold. Back in New "
        "Orleans she abandons her Tuesday receiving days, moves out of "
        "the family house into a little pigeon house of her own, takes "
        "up painting, and refuses the duties of a mother-woman, the "
        "ideal her friend Adele Ratignolle embodies. When Robert "
        "returns and she declares her love, he cannot follow where she "
        "leads, and the novel ends with Edna swimming far out into the "
        "sea, the awakening complete. Chopin's portrait of a woman "
        "who would rather drown than be owned made the book a "
        "landmark of early feminism and a masterpiece of the "
        "American novel."
    ),
    "the-48-laws-of-power": (
        "Robert Greene's 1998 book is a handbook of the strategies that "
        "have let the powerful gain and keep power, drawn from three "
        "thousand years of history, philosophy and warfare. Each of the "
        "forty-eight laws is presented the same way: a statement of the "
        "law, a transgression from history that shows what happens when "
        "it is broken, an observance that shows its successful use, and "
        "a closing interpretation of its meaning. Never outshine the "
        "master. Always say less than necessary. Win through your "
        "actions, never through argument. Create a compelling specter "
        "of unpredictability. Greene draws his examples from figures "
        "like Sun Tzu, Machiavelli, Richelieu, Queen Elizabeth I, "
        "Napoleon and P. T. Barnum, and the book's tone is "
        "deliberately amoral, presenting the laws as tools that "
        "operate whether or not we believe in them. It became a "
        "phenomenon in business, entertainment and politics, "
        "recommended in the most unlikely places, and it remains "
        "as controversial as its subject: a book about power that "
        "asks you to see the game for what it is, whether you "
        "choose to play it or not."
    ),
    "book-bridge-of-sanjay-luis-rey": (
        "Thornton Wilder's 1927 novel, winner of the Pulitzer Prize, opens "
        "with an event of no obvious meaning: on July 20, 1714, the "
        "finest bridge in Peru, the bridge of San Luis Rey, breaks and "
        "five people plunge into the gorge below. Brother Juniper, a "
        "Franciscan who witnesses the fall, devotes his life to proving "
        "that it was not chance, that the five died because they "
        "deserved to, and Wilder unfolds each of the five lives in turn. "
        "The Marquesa de Montemayor, absurd and passionate, who loves "
        "her cold, beautiful daughter from a distance and writes her "
        "letters that are among the greatest in the Spanish language. "
        "Her companion Pepita, an orphan raised by the abbess of a "
        "convent. Esteban and Manuel, twin brothers so close they "
        "seem one person, and whose attachment cannot survive Manuel's "
        "love for an actress. Uncle Pio, the old impresario who "
        "discovered the actress Camila Perichole, and who is "
        "traveling with her sickly son. None of them, Wilder shows, "
        "died for the reasons Juniper imagines; all of them loved, "
        "imperfectly and at cross purposes. The book's famous "
        "conclusion is that love is the only bridge, that we are "
        "all connected by the loves we fail at and are failed by."
    ),
    "book-pratchett-hogfather": (
        "Terry Pratchett's 1996 Discworld novel is a Christmas story with "
        "the tinsel stripped off. On the Disc, Hogswatchnight is when the "
        "Hogfather, a jolly fat man in a red robe, flies his sleigh "
        "delivering presents, and the little people of the Disc leave "
        "him sausages and brandy. This year the Hogfather has "
        "vanished, and the Auditors of Reality, beings who hate the "
        "messiness of belief, have hired a hitman, the unnerving Mr. "
        "Teatime, to make sure he never returns. Death, who has a "
        "soft spot for the season, decides to take the Hogfather's "
        "place, flying a sleigh pulled by boars and handing out "
        "presents in his own bony way, while his granddaughter "
        "Susan, a governess who does not believe in the Hogfather "
        "and therefore can see him, races to uncover what Teatime "
        "is really doing and why the Hogfather's disappearance "
        "matters so much. The book is Pratchett at his most "
        "pointed about the value of stories and belief: the "
        "Hogfather exists because people believe in him, and "
        "Death's most quoted speech insists that humans need "
        "fantasies to be human, that the little lies make the "
        "big truths possible. Dark, funny and genuinely moving, "
        "it became a beloved annual tradition."
    ),
    "book-going-postal": (
        "Terry Pratchett's 2004 Discworld novel gives its hero the "
        "simplest of choices: hang, or take over the Ankh-Morpork Post "
        "Office. Moist von Lipwig, a master con man, takes the second "
        "option, and finds himself the master of a building full of "
        "decades of undelivered mail, a workforce of elderly clerks "
        "who have been sorting letters by candlelight for years, and "
        "a golem named Mr. Pump who has been assigned to keep him "
        "honest, literally. The post office has been made obsolete "
        "by the clacks, the great semaphore towers that send messages "
        "across the Disc in seconds, and the company that runs them, "
        "the Grand Trunk, is run by a man who will do anything to "
        "keep the post office dead. Moist, who cannot resist a "
        "scheme, decides to revive the post office properly, "
        "designing stamps, hiring postmen, delivering every lost "
        "letter, and taking the Grand Trunk on in a race that "
        "becomes a corporate war. The book is Pratchett's love "
        "letter to communication itself, to letters and the "
        "people who carry them, and its hero, a liar who "
        "discovers he is very good at telling the truth, "
        "remains one of the most beloved characters in the "
        "series."
    ),
    "book-watership-down": (
        "Richard Adams's 1972 novel began as stories he told his "
        "daughters on long car journeys, and it became one of the "
        "best-loved books of the century. Fiver, a small, nervous "
        "rabbit who sees things that others cannot, is seized by a "
        "vision of death and destruction sweeping the warren at "
        "Sandleford, and he persuades his brother Hazel to lead a "
        "small band of rabbits out before it is too late. Their "
        "journey across the English downs is an odyssey of escape "
        "and survival: they cross a river, are saved from a fox "
        "at the last moment, and shelter in a warren where life "
        "seems comfortable until they discover the snares that "
        "keep it that way. Guided by the lapine mythology of the "
        "hero El-ahrairah, whose stories Hazel tells to give them "
        "courage, the survivors find a hill they can defend, "
        "Watership Down, and face their hardest test: to bring "
        "does to the warren they must negotiate with Efrafa, the "
        "vast, militarized warren ruled by the tyrant General "
        "Woundwort. With the help of Kehaar, a wounded gull, they "
        "plan an escape, and the book ends in a great battle for "
        "the survival of the new warren. An adventure story with "
        "the moral weight of an epic, it won the Carnegie Medal "
        "and the Guardian Prize."
    ),
    "republic-plato": (
        "Plato's Republic, written around 375 BCE, is the founding work "
        "of Western political philosophy, a dialogue in which Socrates "
        "and his friends try to answer the question of what justice is "
        "and why it is better to be just than unjust. Because justice "
        "in a single person is hard to see, Socrates proposes to "
        "build one in speech, a city, and the dialogue unfolds as a "
        "blueprint for an ideal state: a city of guardians trained "
        "from childhood, with no private property and no families of "
        "their own, ruled by philosopher-kings who have seen the "
        "Forms, the eternal truths behind appearances. The dialogue "
        "contains some of the most famous images in philosophy: the "
        "allegory of the cave, in which prisoners mistake shadows for "
        "reality and the one who escapes can never make them see; the "
        "divided line, mapping the levels of knowledge and opinion; "
        "the myth of Er, a soldier's vision of the afterlife and the "
        "choice of lives. Plato also offers his analogy of the soul, "
        "divided into reason, spirit and appetite, mirroring the "
        "three classes of the city. Dense, provocative and "
        "sometimes frightening, the Republic has shaped two "
        "thousand years of thinking about justice, education and "
        "the meaning of the good life."
    ),
    "book-wizard-of-earthsea-tombs": (
        "Ursula K. Le Guin's 1971 novel, the second in the Earthsea "
        "cycle, is the story of Tenar, taken from her family as a "
        "child to be the priestess Arha, the Eaten One, servant of "
        "the Nameless Ones in the Tombs of Atuan, a vast and "
        "ancient labyrinth cut into a desert mountain. There she "
        "grows up in darkness and ritual, learning to fear the "
        "powers she serves and to walk the endless corridors and "
        "the great treasure chambers that no one else may enter. "
        "When Ged, the archmage, comes seeking the lost Ring of "
        "Erreth-Akbe, half of which lies hidden in the tombs, he "
        "is caught and left in her power, a man who has come to "
        "steal from the gods she serves. But he does not fear "
        "her as everyone else does, and he shows her the world "
        "she has never seen. The book becomes a story of two "
        "kinds of power: the sterile, possessive power of the "
        "darkness that Tenar has served, and the living power of "
        "a man who can speak to her as a person. In the end "
        "Tenar must choose, to stay in the darkness with "
        "everything she knows or to walk out into a world she "
        "does not know at all, and her choice is one of the "
        "most quietly heroic acts in fantasy literature."
    ),
    "lessons-in-chemistry": (
        "Bonnie Garmus's 2022 novel is the story of Elizabeth Zott, a "
        "chemist in 1950s and 1960s America who has the bad luck to "
        "be better at science than almost everyone around her, and "
        "the audacity to know it. Denied a doctorate because a "
        "colleague assaults her and the university blames her, she "
        "lands at Hastings Research, where she meets Calvin Evans, "
        "a brilliant, Nobel-nominated scientist who falls for her "
        "in the rowing club, and the two build a life together "
        "until a sudden tragedy leaves her alone and pregnant. "
        "Fired from the lab for being a single mother, she finds "
        "herself, to her complete bewilderment, hosting a "
        "television cooking show called Supper at Six, where she "
        "treats cooking as chemistry, explains the science of "
        "baking soda and pH to a national audience, and "
        "accidentally becomes a feminist icon, to the horror of "
        "the network and the delight of the women watching. The "
        "novel is told with wit and rage, narrated partly by her "
        "dog Six-Thirty, and it is at once a love story, a "
        "reckoning with the sexism of mid-century science, and "
        "a portrait of a woman who never once doubts that she "
        "deserves a place at the lab bench."
    ),
    "book-maggie-girl-of-the-streets": (
        "Stephen Crane's 1893 novella is a landmark of American "
        "naturalism, written when he was twenty-two and published at "
        "his own expense after publishers found it too shocking. "
        "Maggie Johnson grows up in the Bowery, the most brutal "
        "slum in New York, in a tenement where her father drinks "
        "and her mother, Mary, rules the family with drunken "
        "violence, cursing her children and screaming at her "
        "neighbors. Maggie, pretty and vague, works in a collar "
        "factory and dreams of a better life, and when Pete, a "
        "bartender with a waxed mustache and a fine suit, begins "
        "to court her, she believes she has found it. He takes "
        "her to the theater and the museum, she gives herself "
        "to him, and then he grows bored of her. Cast out by "
        "her mother, who plays the wronged woman before her "
        "neighbors, Maggie drifts through the streets, "
        "becoming one of the women she used to pity, and "
        "the novel ends with her death, never shown, only "
        "reported. Crane's detached, ironic style, his "
        "refusal to moralize about characters who are "
        "simply crushed by their environment, made the "
        "book a scandal and then a classic, and its "
        "portrait of poverty as a machine that grinds "
        "up the innocent has never lost its power."
    ),
    "book-progress-and-poverty": (
        "Henry George's 1879 book asked a question that still burns: why "
        "does poverty persist in the midst of progress? In boomtown "
        "California he watched the railroads and the gold rush create "
        "enormous wealth while workers sank deeper into want, and he "
        "set out to find the cause. His answer was land. George argued "
        "that as a community grows, the value of its land rises, not "
        "because landowners do anything but because the community "
        "itself creates that value, and he traced the cycle of boom "
        "and bust to land speculation: people holding land out of "
        "use, waiting for it to appreciate. The remedy he proposed "
        "was as simple as his diagnosis was radical: tax land values, "
        "and only land values, abolishing all taxes on labor and "
        "capital, so that the wealth created by the community "
        "returns to the community, and land speculation becomes "
        "impossible. He called it the single tax, and the book, "
        "written in plain, passionate prose, became one of the "
        "best-selling works of the nineteenth century, read by "
        "everyone from Tolstoy to Sun Yat-sen, and it founded "
        "a political movement that swept America and Britain. "
        "The questions it raised, about who owns the value "
        "we create together, remain unsettled."
    ),
    "book-the-posthumous-memoirs-of-bras-cubas": (
        "Machado de Assis's 1881 novel begins with the best opening in "
        "Brazilian literature: the narrator introduces himself as a "
        "dead man writing his memoirs, a writer who has taken up the "
        "pen after death because he is, he explains, freer than "
        "other biographers, since he no longer has to please the "
        "living. Bras Cubas was a wealthy man of Rio de Janeiro, "
        "and his memoirs are a digressive, ironic account of a "
        "life that never quite happened: his youthful love for "
        "the courtesan Marcela, who loved his money more; his "
        "aborted political career; his great invention, the "
        "Emplasto Bras Cubas, an anti-hypochondriacal plaster "
        "he never gets around to making; his affair with "
        "Virgilia, the wife of his rival, which burns out in "
        "boredom; his childhood, his father's death, his "
        "friends. Nothing in the book turns out well, and "
        "Bras Cubas reports it all with the complacency of a "
        "man who never suffered for anything and never "
        "learned anything either, punctuating his story "
        "with little chapters of pure digression, a "
        "delirium in which he is carried through the "
        "ages by the Universe itself, and the famous "
        "negative epilogue, in which he declares that "
        "he has not had descendants, and has "
        "transmitted to no one the legacy of his "
        "misery. A century ahead of its time, the "
        "book is a masterpiece of irony and one of "
        "the founding works of modern fiction."
    ),
    "book-brave-new-world-revisited": (
        "Aldous Huxley's 1958 book is the sequel he never wanted to "
        "write: a work of nonfiction in which he looks back at the "
        "dystopia he imagined in Brave New World and measures it "
        "against the real world of the 1950s. His verdict is that "
        "the future arrived faster and along different roads than "
        "he predicted. He examines overpopulation, the crowding "
        "that he believed would make freedom unaffordable; "
        "propaganda and the new arts of persuasion, from "
        "advertising to political manipulation; brainwashing and "
        "the techniques of psychological conditioning drawn from "
        "Pavlov, which he saw applied not only in totalitarian "
        "states but in democratic ones; and the drugs, then "
        "tranquilizers and alcohol, that he feared would become "
        "the soma of his novel. His central worry is not tyranny "
        "by force but what he calls the dictatorship of the "
        "immediate future, rule through the manipulation of "
        "wants and the management of opinion, in which "
        "freedom is surrendered not at gunpoint but in "
        "exchange for comfort and distraction. Written in "
        "Huxley's lucid essayistic voice, the book is a "
        "chillingly precise set of predictions, many of "
        "which have come true, and an argument for "
        "awareness as the only defense."
    ),
    "book-ethan-frome": (
        "Edith Wharton's 1911 novella is set in the stark New England "
        "village of Starkfield, Massachusetts, where winter lasts half "
        "the year and poverty is a kind of weather. The frame is a "
        "visit: a young engineer, stranded in the town, is driven "
        "around by Ethan Frome, a silent, crippled man of fifty who "
        "was once a bright young farmer, and he pieces together "
        "Ethan's story from the fragments the town will tell. Years "
        "before, Ethan was trapped in a loveless marriage to Zeena, "
        "his hypochondriac wife, whose illness eats the money and "
        "the warmth out of their house. When Zeena's cousin Mattie "
        "Silver comes to help, Ethan falls in love with her, and "
        "for one short season the house has light in it. Zeena, "
        "returning from a doctor's visit, announces that Mattie "
        "must go, and Ethan and Mattie, facing separation, "
        "choose the only freedom they can imagine: one last "
        "sled ride down the hill, into the great elm at the "
        "bottom. They survive, Ethan crippled and Mattie "
        "paralyzed, and the frame closes on the two of them, "
        "old before their time, tended by Zeena. A tragedy "
        "of the narrowest kind, it is Wharton's most "
        "perfect book, every sentence as bare and hard as "
        "a Starkfield winter."
    ),
    "the-tipping-point-gladwell": (
        "Malcolm Gladwell's 2000 bestseller explains how ideas, "
        "products and behaviors suddenly catch fire, and why small "
        "changes can have enormous effects. His model is the "
        "epidemic: fads spread the way diseases do, and they tip, "
        "cross a threshold and explode into fashion or panic or "
        "crime. The book identifies the forces that make tipping "
        "possible. The law of the few: a handful of exceptional "
        "people drive epidemics, the connectors who know "
        "everyone, the mavens who accumulate and share "
        "information, and the salesmen who can persuade anyone. "
        "The stickiness factor: some messages stick in memory, "
        "whether it is a Sesame Street segment or a rumor, and "
        "small tweaks can make an idea unforgettable. The power "
        "of context: behavior is shaped more by environment than "
        "by character, which is why the broken-windows theory "
        "claimed that cleaning up graffiti could reduce violent "
        "crime, and why the rule of a hundred and fifty "
        "governs how many people a community can truly know. "
        "Gladwell's examples run from Hush Puppies to Paul "
        "Revere's ride to the sudden drop in New York crime, "
        "and the book made the phrase tipping point a "
        "permanent part of the language."
    ),
    "book-pedro-paramo": (
        "Juan Rulfo's 1955 novel is one of the founding works of "
        "magical realism, a book of barely a hundred and fifty "
        "pages that changed Latin American literature. Juan "
        "Preciado, his mother dying, promises her he will find "
        "his father, Pedro Paramo, in the town of Comala, and "
        "he sets out on foot. What he finds is a town of the "
        "dead, a place where the living have all gone and the "
        "dead whisper in the streets, in the plazas and under "
        "the earth, their voices drifting up from the graves "
        "of the cemetery. The novel moves between Juan's "
        "increasingly strange arrival and the story of Pedro "
        "Paramo himself, the tyrant who built Comala and "
        "sucked it dry, who took the land and the women he "
        "wanted and the money he needed, and who was "
        "destroyed not by his enemies but by his one "
        "impossible love, Susana San Juan, who loved "
        "only a dead man. The narrative is told in "
        "fragments, voices and echoes, time folding "
        "back on itself, and the reader slowly "
        "understands that the whole book is being "
        "narrated from beyond the grave. Rulfo's "
        "masterpiece, it influenced Garcia Marquez "
        "and generations after him, and it remains "
        "a perfect novel, every word necessary."
    ),
    "book-death-comes-for-the-archbishop": (
        "Willa Cather's 1927 novel, written after the death of her "
        "own priest, is a quiet masterpiece about faith, landscape "
        "and time. It follows Father Jean Marie Latour, a "
        "Frenchman of exquisite cultivation, and his friend "
        "Father Joseph Vaillant, as they are sent in 1851 to "
        "revive the Catholic church in the vast, newly annexed "
        "territory of New Mexico, a desert world of adobe "
        "missions, ancient pueblos and priests who have gone "
        "native or gone bad. Cather tells their story as a "
        "series of episodes across thirty years: the journey "
        "across the plains, the long rides between missions, "
        "the stubborn Indian converts, the carved wooden "
        "saints, the snake dances, the ordeal of the "
        "priest on the rock of Acoma, Kit Carson and the "
        "raids, and the slow, patient building of a "
        "cathedral in Santa Fe, for which Latour "
        "imports architects and stone from France. "
        "There is almost no conventional plot; the "
        "drama is in the weathering of two holy "
        "lives, and the book's famous meditation, "
        "on the moment when Death comes for the "
        "archbishop, brings the whole story to a "
        "close of extraordinary serenity. It is "
        "Cather's own favorite among her novels."
    ),
    "book-the-adventures-of-tom-sawyer": (
        "Mark Twain's 1876 novel made Tom Sawyer immortal, the "
        "mischievous boy of St. Petersburg, Missouri, a town on "
        "the Mississippi that Twain modeled on his own Hannibal. "
        "The book is a string of adventures held together by Tom's "
        "genius for getting into and out of trouble: the "
        "whitewashed fence he tricks the other boys into painting "
        "for him, the Sunday school tickets he trades for a Bible "
        "he has never read, his courtship of Becky Thatcher, and "
        "his friendship with Huckleberry Finn, the son of the "
        "town drunk, who lives free and answers to nobody. But "
        "the idyll turns dark when the boys witness a murder in "
        "the graveyard: Injun Joe kills the doctor, frames "
        "Muff Potter, and Tom and Huck swear a blood oath "
        "never to tell. Tom testifies at the trial and saves "
        "Potter, and the boys' search for buried treasure "
        "leads them into a haunted house where they hear "
        "Injun Joe talking about a hidden hoard, and "
        "finally into the labyrinth of McDougal's Cave, "
        "where Tom and Becky are lost for days with the "
        "murderer somewhere in the dark. Tom and Huck "
        "find the treasure, twelve thousand dollars "
        "each, and the book ends with Huck "
        "considering whether he can bear being "
        "adopted and civilized. Funny, warm and "
        "suddenly frightening, it is the great "
        "American novel of boyhood."
    ),
    "book-far-seer": (
        "Robin Hobb's 1995 novel opens the Farseer trilogy and "
        "introduces one of the most beloved narrators in fantasy. "
        "Fitz, the bastard son of Prince Chivalry, is six years "
        "old when he is dumped at the royal keep of Buckkeep, "
        "a shame the king would rather forget. Raised by "
        "Burrich, the stablemaster who despises what Fitz "
        "is, and tutored in secret, he grows up a servant "
        "and a weapon: a boy with the royal magic of the "
        "Skill, which lets a mind reach into other minds, "
        "and the older, uglier magic of the Wit, which "
        "binds a man to an animal, a magic that is "
        "hated and feared in the Six Duchies. Trained "
        "in secret as an assassin by the ancient Chade, "
        "Fitz is drawn into the plots of the court as "
        "the Red Ship Raiders ravage the coast, "
        "turning their captives into Forged "
        "creatures, empty of feeling and loyalty. "
        "His life is a succession of uses and "
        "betrayals, his only loyalties the "
        "people who forget him and the wolf "
        "whose mind he meets in the wilderness. "
        "Slow, rich and devastating, the book "
        "is fantasy as character study, and "
        "its quiet, wounded hero carried the "
        "genre's weight for a generation."
    ),
    "book-murderbot": (
        "Martha Wells's 2017 novella, the first in the Murderbot "
        "Diaries, is the story of a security unit that has hacked "
        "its own governor module and now makes its own decisions, "
        "the first of which is to watch as much entertainment "
        "media as possible. Murderbot, as it calls itself "
        "dryly, is a part-organic, part-robotic construct "
        "assigned to protect a team of scientists on a "
        "survey mission to a planet that should have been "
        "routine. Its clients are kind and vulnerable and "
        "annoying, its secret is that it is free, and it "
        "is trying very hard not to care about any of "
        "them. Then the survey goes wrong: another "
        "expedition on the planet has gone silent, "
        "something is hunting the scientists, and "
        "Murderbot, which has spent its life being "
        "told it is just a machine, has to decide "
        "what it actually is. The novella is told "
        "in Murderbot's own voice, deadpan, "
        "self-aware and unexpectedly moving, "
        "and its story of a being that would "
        "rather watch serials than save the "
        "world, and saves it anyway, made "
        "Murderbot one of the most beloved "
        "characters in modern science "
        "fiction, the start of a series "
        "that won the Hugo and Nebula "
        "awards."
    ),
    "the-sapiens-harari": (
        "Yuval Noah Harari's 2011 book is a history of humankind in "
        "one volume, from the emergence of our species to the "
        "present, told as a story with a thesis: that the secret "
        "of our success is not intelligence or toolmaking but the "
        "ability to believe in fictions. The book moves through "
        "three revolutions. The cognitive revolution, around "
        "seventy thousand years ago, gave Homo sapiens language "
        "flexible enough to tell stories, and with it the power "
        "to cooperate in large numbers, to invent gods, nations, "
        "money and laws that exist only because we all agree "
        "they do. The agricultural revolution, about ten "
        "thousand years ago, traded the freedom of foraging "
        "for the security of farming, and Harari calls it "
        "the greatest fraud in history, arguing that it "
        "made life harder, not easier, and created "
        "hierarchy and inequality. The scientific "
        "revolution, beginning around five hundred "
        "years ago, admitted ignorance and turned "
        "it into a method, unleashing empire, "
        "industry and the modern world. "
        "Throughout, Harari insists that we "
        "are the most destructive species "
        "in history, and that our ability "
        "to tell stories is also our "
        "greatest danger. Provocative, "
        "global and written for "
        "everyone, it became an "
        "international phenomenon."
    ),
    "tuesdays-with-morrie": (
        "Mitch Albom's 1997 memoir began as a promise kept. Sixteen "
        "years after graduating from Brandeis, Albom, now a busy "
        "sports journalist, sees his old sociology professor, "
        "Morrie Schwartz, on Nightline, dying of ALS, the "
        "degenerative disease that is taking his body apart "
        "piece by piece. Albom flies to Massachusetts to see "
        "him, and the visit becomes a course: every Tuesday "
        "he comes back, and they talk, as they did when "
        "Albom was a student, about the things Morrie "
        "still has time to teach. The chapters are the "
        "lessons: about the world and the meaning of "
        "life, about feeling sorry for yourself, "
        "about regrets, death and the fear of "
        "aging, about family, money, love and "
        "forgiveness. Morrie, who taught his "
        "students that the most important "
        "thing in life is to learn how to "
        "give out love and let it come "
        "in, treats his own dying as a "
        "final class, saying goodbye to "
        "everyone he loves. The book "
        "ends with his death, at "
        "seventy-eight, and with "
        "Albom learning the last "
        "lesson: that the only "
        "way to find meaning "
        "is to devote "
        "yourself to "
        "loving others. A "
        "phenomenon that "
        "spent years on "
        "the bestseller "
        "lists, it "
        "became one "
        "of the most "
        "widely read "
        "books about "
        "dying, and "
        "about living, "
        "in the world."
    ),
    "book-of-mice-and-men": (
        "John Steinbeck's 1937 novella is a tragedy in six short "
        "chapters, set among the migrant ranch hands of the "
        "Salinas Valley during the Depression. George Milton is "
        "small, sharp and quick; his companion Lennie Small is "
        "huge, gentle and simple, a giant who loves soft things "
        "and does not know his own strength. The two travel "
        "together, George watching over Lennie, telling him "
        "the story that keeps them going, the dream of the "
        "little farm they will own someday, with rabbits "
        "that Lennie can tend, a place of their own where "
        "nobody can fire them or chase them off. On a new "
        "ranch they find a fragile peace: the old "
        "stablehand Candy, who has lost a hand and "
        "will lose his old dog too, wants to buy "
        "into the dream; the boss's son Curley, "
        "a small man full of violence, wants "
        "to fight Lennie; and Curley's wife, "
        "lonely and flirtatious, drifts "
        "through the bunkhouse looking "
        "for company. When Lennie, "
        "frightened, accidentally "
        "kills her, the dream "
        "dies with her, and "
        "George is left to do "
        "the only thing he "
        "can to protect "
        "his friend. "
        "Bare, brutal "
        "and "
        "profoundly "
        "tender, "
        "it is "
        "Steinbeck's "
        "most perfect "
        "book."
    ),
    "book-rendezvous-with-rama": (
        "Arthur C. Clarke's 1973 novel won every major science "
        "fiction award and remains the purest example of his "
        "style: an idea, rigorously worked out, told with "
        "clarity and wonder. In the year 2130, astronomers "
        "detect a large object entering the solar system "
        "at high speed, an object moving on a trajectory "
        "that proves it is not natural. Rama, as it is "
        "named, is a cylinder fifty kilometers long "
        "and twenty wide, spinning slowly, and the "
        "crew of the spaceship Endeavour, commanded "
        "by Commander Bill Norton, is sent to "
        "rendezvous with it and find out what "
        "it is. Inside, they find a world: a "
        "dark, cold landscape with a frozen "
        "sea ringing the interior, strange "
        "mechanical life forms, the biots, "
        "and three structures at the sea's "
        "edge that they call the three "
        "Ramans. The explorers are "
        "watched but never "
        "acknowledged, and "
        "slowly they realize "
        "that Rama is not a "
        "ship but a habitat, "
        "and that its "
        "builders are not "
        "interested in "
        "them at all. "
        "The novel has "
        "no villain and "
        "no love story, "
        "only the "
        "awe of "
        "encounter, "
        "and its "
        "ending, "
        "as Rama "
        "swings "
        "around "
        "the sun "
        "and "
        "leaves, "
        "is "
        "one of "
        "the "
        "greatest "
        "in "
        "science "
        "fiction."
    ),
}


def main():
    with open(PATH, encoding="utf-8") as f:
        data = json.load(f)
    by_id = {t.get("id"): t for t in data}
    missing = [i for i in CONTENT if i not in by_id]
    if missing:
        raise SystemExit(f"ids not found in {PATH}: {missing}")
    changed = 0
    for topic in data:
        new_syn = CONTENT.get(topic.get("id"))
        if new_syn is None:
            continue
        if not FORCE and topic.get("synopsis", "").strip() == new_syn:
            continue
        topic["synopsis"] = new_syn
        changed += 1
    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"rewrote {changed} synopses (total topics {len(data)})")


if __name__ == "__main__":
    main()