#!/usr/bin/env python3
"""books.json synopsis QUALITY pass (connected prose, 30 books).

The user reported that some synopses "don't feel connected" and don't
read like proper synopses. Two problems fixed here:
1. Eight of the batch-1/2 rewrites (non-fiction) were LISTY: sentences
   of the form "he shows X; he explores Y; he examines Z" with
   colon-catalogues. Rewritten as flowing, connected prose.
2. Twenty-two of the shortest pre-existing synopses in the catalog
   (320-494 chars) were thin one-paragraph blurbs with the same
   disconnected feel. Rewritten as proper synopses.

House rules: no em/en dashes, no curly quotes, ~800-1350 chars,
paragraphs (\\n\\n) only where a book has a genuinely distinct part.
Rerunnable; matches books.json format (2-space indent, no trailing
newline).
"""
import json
import os

PATH = "data/topics/books.json"
FORCE = os.environ.get("FORCE") == "1"

CONTENT = {
    "predictably-irrational-ariely": (
        "Dan Ariely's 2008 book grew out of a lifetime of bad decisions. "
        "As a young man he was badly burned, and the nurses who treated "
        "him ripped the bandages off his wounds as quickly as possible, "
        "convinced that fast pain was better than slow pain; Ariely, who "
        "was on the receiving end, knew they were wrong, and the "
        "realization that people make systematically bad choices in "
        "predictable ways became the subject of his life's work. From his "
        "behavioral economics lab at MIT came the experiments the book "
        "walks through, each one exposing a hidden force behind our "
        "decisions. He shows how a cleverly priced subscription menu can "
        "make a mediocre option look like a bargain, how the word free "
        "makes us grab things we do not want, how the memory of an "
        "arbitrary number can anchor a price we pay days later, and how "
        "the simple fact of owning something makes us value it more. He "
        "even demonstrates that social rules and market rules govern "
        "different worlds, and that mixing them up can ruin a perfectly "
        "good date. Part science, part confession, the book is a witty "
        "and unsettling tour of the bugs in our decision-making software, "
        "and a quiet argument that understanding them is the first step "
        "to outsmarting them."
    ),
    "nudge-thaler-sunstein": (
        "Richard Thaler and Cass Sunstein's 2008 book begins with a "
        "simple observation: every choice we face has been arranged by "
        "someone, and the person doing the arranging, whether a "
        "cafeteria manager or a government, has enormous power over what "
        "we pick. They call that person a choice architect, and their "
        "term for a well-designed arrangement is a nudge, a small, cheap "
        "change in how options are presented that steers people toward "
        "better decisions without forbidding anything. A school "
        "cafeteria discovered that simply moving the salad can shift "
        "how many children eat it, and the same logic applies to "
        "retirement plans, where auto-enrollment transforms "
        "participation rates, and to organ donation, where opt-out "
        "countries have dramatically more donors than opt-in ones, "
        "because people stick with whatever the default is. From "
        "these examples the authors build their philosophy of "
        "libertarian paternalism: because human beings are fallible "
        "choosers who procrastinate, misjudge probabilities and "
        "follow the crowd, well-designed nudges, transparent and "
        "never manipulative, can improve health, wealth and "
        "happiness while preserving everyone's freedom of choice. "
        "Thaler's contribution to the field they popularized won "
        "him the Nobel Prize in economics."
    ),
    "ego-is-the-enemy": (
        "Ryan Holiday's 2016 book, the middle volume of his Stoic "
        "trilogy, is about the enemy that attacks from inside: ego, the "
        "unearned confidence that mistakes activity for achievement, and "
        "that tells you you have already arrived before you have done "
        "the work. Holiday tracks it through the three great moments of "
        "any career. Before success, ego whispers that you are too good "
        "for the humble tasks that would teach you, so the book's first "
        "lesson is humility, the willingness to learn and to take the "
        "small job seriously. At the height of success, ego is at its "
        "most dangerous, because praise convinces us we are the source "
        "of our own good fortune, so Holiday shows how the leaders he "
        "admires, generals and champions and artists alike, deflect "
        "credit, stay focused on the mission rather than themselves, and "
        "refuse the isolation that fame brings. And when things fall "
        "apart, ego turns every setback into a catastrophe, so the final "
        "lesson is resilience: own the mistake quickly, treat the "
        "failure as material, and get back to work. Drawing on stories "
        "from history and on Stoic philosophy throughout, the book makes "
        "one case with relentless force: our sense of our own importance "
        "blinds us to reality, and humility, discipline and a focus on "
        "the work itself are the only defenses that hold."
    ),
    "stillness-is-the-key": (
        "Ryan Holiday's 2019 book makes a counterintuitive argument for "
        "a noisy age: the ability to be still, to be calm, present and "
        "focused, is not a retreat from ambition but the hidden engine "
        "of greatness. The book is built on the Stoic map of the self, "
        "three territories to be cultivated. The first is the mind, and "
        "Holiday's example is John F. Kennedy, who kept his thinking "
        "clear and unhurried through the Cuban Missile Crisis while the "
        "world held its breath; presence, silence and the protection of "
        "attention are the disciplines that make such clarity possible. "
        "The second is the heart, where gratitude, the management of "
        "anger and the courage to be vulnerable determine whether our "
        "emotions serve us or rule us, and where Holiday draws on "
        "figures from the philosopher Seneca to the golfer Tiger Woods. "
        "The third is the body, because composure has to be carried in "
        "the flesh: rest, sleep and daily discipline are not escapes "
        "from ambition but its foundation. Weaving together Stoicism, "
        "Buddhism, Taoism and the lives of artists, athletes and "
        "leaders, Holiday argues that in an age engineered for "
        "distraction, the ability to slow down is not a luxury but a "
        "competitive advantage."
    ),
    "the-tipping-point-gladwell": (
        "Malcolm Gladwell's 2000 bestseller asks a deceptively simple "
        "question: why do some ideas, products and behaviors suddenly "
        "catch fire while others never move? His answer is that "
        "social change spreads like an epidemic, and that epidemics "
        "tip, crossing a threshold and exploding into fashion or "
        "panic or crime, all because of a few small forces. The "
        "first is the law of the few: a handful of exceptional "
        "people do most of the work, the connectors who seem to "
        "know everyone, the mavens who gather and share "
        "information, and the salesmen who can persuade anyone of "
        "anything. The second is stickiness: some messages cling "
        "to memory, and tiny adjustments, the way a lesson is "
        "framed or a rumor is told, can make the difference "
        "between something forgotten and something unforgettable. "
        "The third is the power of context, the discovery that "
        "behavior is shaped more by the environment than by "
        "character, which is why cleaning graffiti was supposed "
        "to reduce violent crime and why a community larger "
        "than about a hundred and fifty people stops feeling "
        "like a community at all. From Hush Puppies to Paul "
        "Revere's ride to the sudden drop in New York crime, "
        "Gladwell's examples made the phrase tipping point a "
        "permanent part of the language."
    ),
    "the-algorithms-christian": (
        "Brian Christian and Tom Griffiths's 2016 book is built on a "
        "happy accident of scale: the problems of daily life, when to "
        "stop looking for something better, what to remember, how to "
        "schedule an overloaded day, are the same problems computer "
        "scientists solved decades ago, and their solutions turn out "
        "to be genuinely useful advice for humans. The authors, a "
        "writer and a cognitive scientist, walk through the classic "
        "algorithms one by one. The optimal-stopping problem tells "
        "us when to stop searching and settle, and it turns out the "
        "best moment to commit is about 37 percent of the way "
        "through your options, whether you are choosing an "
        "apartment or a spouse. The explore-exploit tradeoff asks "
        "how much novelty to try before sticking with what "
        "works. Caching explains why the things we use most "
        "should live closest at hand, and why forgetting is a "
        "feature, not a bug. Scheduling and priority queues "
        "take on procrastination, Bayes's rule takes on "
        "prediction, and the problem of overfitting explains "
        "why the best model of the past is not always the "
        "best guide to the future. Even game theory gets a "
        "chapter, arguing that being nice turns out to be "
        "the winning strategy. Accessible and often funny, "
        "the book makes computer science feel like "
        "practical philosophy."
    ),
    "the-48-laws-of-power": (
        "Robert Greene's 1998 book distills three thousand years of "
        "history, philosophy and warfare into the forty-eight rules "
        "that have let the powerful gain and keep power. Each law is "
        "presented the same way, as a piece of practical instruction "
        "with a story attached: never outshine the master, always say "
        "less than necessary, win through your actions never through "
        "argument, learn to keep people dependent on you, use absence "
        "to increase respect and honor. For every law Greene supplies "
        "a transgression from history that shows the cost of breaking "
        "it and an observance that shows its successful use, drawing "
        "on figures from Sun Tzu and Machiavelli to Richelieu, Queen "
        "Elizabeth I, Napoleon and P. T. Barnum. The tone is "
        "deliberately amoral, treating power as a game with rules "
        "that operate whether or not we believe in them, which is "
        "exactly why the book became a phenomenon in business, "
        "entertainment and politics, quoted in boardrooms, "
        "prisons and dorm rooms alike. Its real subject is the "
        "mechanics of influence itself, the moves and "
        "countermoves that decide who rises and who falls, "
        "and whether you use them or not, they are happening "
        "around you."
    ),
    "so-good-they-can-t-ignore-you": (
        "Cal Newport's 2012 book takes aim at one of the most "
        "repeated pieces of career advice in America: follow your "
        "passion. Newport, a computer science professor, argues "
        "that the passion hypothesis is not just wrong but "
        "actively harmful, because most people who love their "
        "work did not start out passionate about it. What they "
        "did instead was become genuinely good at something, "
        "and the book's central idea is career capital, the "
        "rare and valuable skills that give you leverage in "
        "the job market. He illustrates with the comedian "
        "Steve Martin, who spent a decade mastering the "
        "banjo before his overnight success, and with "
        "artisans and programmers and farmers, all of "
        "whom found meaning not by matching a job to a "
        "pre-existing interest but by adopting what "
        "Newport calls the craftsman mindset, a focus "
        "on what you can offer the world rather than "
        "what the world owes you. Once you have "
        "career capital, he shows, you can trade it "
        "for the traits that make work great, "
        "creativity, impact and control, and then "
        "use it to build a mission. The title is "
        "the point: be so good they can't ignore "
        "you, and the passion will follow."
    ),
    "book-dispossessed": (
        "Ursula K. Le Guin's 1974 novel, which won both the Hugo and "
        "the Nebula, is the story of a wall, and of the man who "
        "crosses it. Shevek is a brilliant physicist from Anarres, the "
        "moon settled by anarchist exiles who live without property, "
        "government or leaders, and he is the first of his people to "
        "travel to Urras, the wealthy, stratified homeworld his "
        "ancestors fled. The novel alternates between two timelines, "
        "his youth on Anarres, where the dream of freedom slowly "
        "hardens into its own quiet conformity, and his visit to "
        "Urras, where he is courted as a trophy and discovers what "
        "his people gave up and what they kept. His work on a theory "
        "of time, the physics of simultaneity, is the key to "
        "everything, because what he is really searching for is a way "
        "to bring the two worlds together, to break down the wall "
        "between them. Le Guin called it her favorite of her own "
        "books, an utopia and an anti-utopia in one, and its "
        "famous last lines, that true journey is return, are a "
        "quiet thesis about what freedom actually costs."
    ),
    "book-princess-bride": (
        "William Goldman's 1973 novel pretends to be an abridgment, "
        "the good parts version of a classic fairy tale by the "
        "fictional S. Morgenstern, complete with a framing story in "
        "which Goldman himself is reading it to his son. Inside the "
        "frame is one of the great comic fairy tales: Buttercup, a "
        "beautiful farm girl, falls in love with Westley, the "
        "farmhand who answers all her commands with as you wish, "
        "and when he sails away to seek his fortune and is "
        "reported killed by the Dread Pirate Roberts, she is "
        "betrothed against her will to the cruel Prince Humperdinck "
        "of Florin. The adventure that follows has everything a "
        "fairy tale needs and more: the kidnapping by the Sicilian "
        "genius Vizzini and his two companions, the giant Fezzik "
        "and the swordsman Inigo Montoya, whose revenge quest, "
        "hello, my name is Inigo Montoya, you killed my father, "
        "prepare to die, gives the book its beating heart; the "
        "Cliffs of Insanity, the Fire Swamp, the Zoo of Death "
        "and Miracle Max. Funny, swashbuckling and unexpectedly "
        "moving about true love, it became an instant classic "
        "and a beloved film."
    ),
    "book-jungle": (
        "Upton Sinclair's 1906 novel was written to expose the "
        "exploitation of immigrant workers, and it ended up exposing "
        "something even the author did not expect. Jurgis Rudkus, a "
        "strong young Lithuanian, arrives in Chicago full of hope and "
        "takes a job in the stockyards of Packingtown, and the novel "
        "follows the slow destruction of everything he believes in. "
        "His family is cheated into buying a house they cannot "
        "afford, his bride Ona is forced into degradation to keep "
        "her job, accidents and illness eat the wages the family "
        "never sees, and every institution that was supposed to "
        "help them, the church, the union, the courts, the "
        "political machine, takes its cut or looks away. Sinclair "
        "wrote the book to convert Americans to socialism, and the "
        "novel's final chapters argue that only the collective "
        "ownership of industry can end such misery, but the "
        "public, horrified by the filth of the meatpacking "
        "industry instead of the workers' plight, forced the "
        "Pure Food and Drug Act through Congress. Sinclair "
        "famously said he aimed at the public's heart and hit "
        "it in the stomach, and the novel's raw power has "
        "never faded."
    ),
    "book-sister-carrie": (
        "Theodore Dreiser's 1900 novel shocked its first readers and "
        "changed American fiction, because it told the truth about "
        "desire without punishing it. Carrie Meeber, a naive girl "
        "from a Wisconsin small town, arrives in Chicago with four "
        "dollars and a dream, and finds the city indifferent: the "
        "factory work is grinding, the wages barely keep her alive, "
        "and when illness costs her the job, she is rescued by "
        "Charles Drouet, a charming salesman who takes her as his "
        "mistress. Through him she meets George Hurstwood, a "
        "successful, married restaurant manager who falls for her "
        "and, in a moment of panic, steals money from his employer "
        "and flees with her to New York. There the novel's "
        "architecture becomes clear: as Carrie rises, first on the "
        "chorus line and then on the stage, Hurstwood sinks, "
        "unable to find work, drifting into poverty and finally "
        "into suicide in a cheap hotel. Dreiser's naturalism "
        "refused to moralize, and the book's portrait of the "
        "city as a machine that consumes the weak and rewards "
        "the beautiful made it a landmark, and a scandal, of "
        "American literature."
    ),
    "book-uncle-toms-cabin": (
        "Harriet Beecher Stowe's 1852 novel was the most influential "
        "work of fiction in American history, a book that changed how "
        "millions of readers thought about slavery. Its two threads "
        "follow the fate of the enslaved people of the Shelby farm in "
        "Kentucky. The first is Eliza, who learns her son is to be "
        "sold, grabs him and flees across the ice-choked Ohio River "
        "to freedom, helped by Quakers and the network of the "
        "Underground Railroad. The second is Uncle Tom, who accepts "
        "his sale south out of loyalty to his master, and whose "
        "patient faith carries him through the brutal plantation of "
        "Simon Legree, where he refuses to betray his fellow "
        "enslaved people and dies a martyr, forgiven even of "
        "Legree. Stowe wrote with evangelical fury and enormous "
        "narrative skill, and the book sold hundreds of thousands "
        "of copies, turned public opinion against the Fugitive "
        "Slave Act and is said to have been greeted by Lincoln, "
        "perhaps apocryphally, as the little lady who started "
        "this great war. It also shaped, for better and for "
        "worse, the stereotypes that American culture would "
        "carry for a century, which is why it remains both a "
        "landmark and a contested text."
    ),
    "book-love-in-the-time-of-cholera": (
        "Gabriel Garcia Marquez's 1985 novel is a love story that "
        "refuses to end, told across more than fifty years. Florentino "
        "Ariza falls in love with Fermina Daza when they are young, "
        "courting her through letters and a promise of marriage, "
        "until her father drags her away and she marries Dr. Juvenal "
        "Urbino, the most eligible man in the city, a marriage of "
        "comfort and routine that lasts half a century. Florentino "
        "waits, and while he waits he climbs, he builds a shipping "
        "career, and he records six hundred and twenty-two affairs, "
        "each one a substitute for the woman he cannot have. When "
        "Urbino dies at eighty-one, falling from a ladder while "
        "chasing a parrot, Florentino appears at the widow's door "
        "the same day to renew his vow, and the two elderly lovers "
        "take to the river on a steamship, flying the yellow flag "
        "of cholera so no one will board them, adrift on the river "
        "forever, as the novel's famous last word promises. Marquez "
        "wrote it as a love story for old age, a book in which "
        "love is less a feeling than a stubborn discipline, and "
        "its tenderness and humor made it his most widely loved "
        "novel after One Hundred Years of Solitude."
    ),
    "book-gideon-the-ninth": (
        "Tamsyn Muir's 2019 novel is a locked-room murder mystery set "
        "in a crumbling space empire ruled by necromancers. Gideon "
        "Nav, a swordswoman with a mouth full of complaints, has "
        "spent her life trying to escape the Ninth House, a "
        "dark, dying fortress of bone and ritual, and its "
        "necromancer heir, the brilliant and impossible "
        "Harrowhark Nonagesimus, who raised her. When the "
        "Emperor summons every house to send its necromancer "
        "and her cavalier to the haunted space station "
        "Canaan House, Harrow claims Gideon as her sword, "
        "and the two arrive to find a competition: one "
        "pair will be granted lyctorhood, immortality "
        "and godlike power, if they can solve the "
        "station's ancient tests. Then the contestants "
        "begin to die, one by one, in ways that are "
        "anything but accidental. The book combines "
        "the locked-room puzzle of a classic murder "
        "mystery with Muir's baroque world-building "
        "and her corrosive, hilarious dialogue, "
        "and its ending, a final revelation about "
        "the price of lyctorhood, reshapes "
        "everything that came before and made "
        "the series an instant phenomenon."
    ),
    "book-souls-of-black-folk": (
        "W. E. B. Du Bois's 1903 collection of essays is the founding "
        "text of the African American intellectual tradition. Its "
        "opening chapter announces the central problem of the new "
        "century as the problem of the color line, and its most "
        "famous passage describes double consciousness, the sense "
        "of always looking at oneself through the eyes of others, "
        "of two souls, two thoughts, two unreconciled strivings "
        "in one dark body. From that framing Du Bois ranges "
        "across the life of his people: the history of "
        "emancipation and its failure, the rise of "
        "sharecropping and disenfranchisement, the "
        "sorrow songs that he reads as the spiritual "
        "archive of a nation, and a full-length "
        "portrait of the veil that separates Black "
        "and white America. The book also contains "
        "his famous open quarrel with Booker T. "
        "Washington, arguing against the Atlanta "
        "Compromise's bargain of submission for "
        "industrial training, and insisting on "
        "the right of the educated to demand "
        "the vote and full citizenship. Elegant, "
        "bitter and prophetic, The Souls of "
        "Black Folk shaped the century of "
        "Black thought that followed it."
    ),
    "book-ball-lightning": (
        "Liu Cixin's 2005 novel begins with a death that defines a "
        "life: when Chen is fourteen, ball lightning appears in his "
        "family's home and kills his parents, and he devotes himself "
        "to understanding the phenomenon that took them. His quest "
        "takes him through the strange world of Chinese military "
        "science, where he works alongside the brilliant and "
        "frightening Major Lin Yun, a soldier who lost her own "
        "family to the same terror and wants to turn ball "
        "lightning into a weapon. Liu's science fiction is famous "
        "for taking one fantastic idea seriously, and here the "
        "idea is that ball lightning is not plasma at all but a "
        "macroscopic quantum state, a question of observation "
        "as much as energy. The novel unfolds as a puzzle box "
        "of discoveries, from the weather laboratory that "
        "generates the lightning to the revelation that "
        "conventional particle physics cannot account for "
        "it, and it builds toward a finale in which "
        "Lin's weapon, and Chen's obsession, become "
        "something stranger than revenge. Cold, "
        "precise and deeply felt, Ball Lightning "
        "is a meditation on grief and sacrifice "
        "wearing the armor of hard science "
        "fiction."
    ),
    "book-genji": (
        "Murasaki Shikibu's Tale of Genji, written in the early "
        "eleventh century, is often called the world's first novel, "
        "and it remains one of its greatest. Genji, the shining "
        "prince, is the son of the emperor and a low-ranking "
        "concubine, beautiful, gifted and magnetic, and the long "
        "narrative follows his life through the glittering, "
        "ritual-bound world of the Heian court. His loves are "
        "the novel's engine, from the forbidden passion for his "
        "father's young wife, the lady Fujitsubo, whose son he "
        "raises in secret as his own, to the idealized Murasaki, "
        "whom he takes as a child and raises to be the woman of "
        "his heart, to the jealous Rokujo and the many affairs "
        "that make and unmake his reputation. Around these "
        "entanglements Murasaki weaves a vast social panorama: "
        "poetry exchanges, moon-viewing parties, seasonal "
        "rituals, political maneuvering, exile and return, "
        "and, in its final books, the melancholy of age and "
        "the fading of the house of Genji. The novel's "
        "sensibility, its awareness of the beauty and "
        "sadness of impermanence, has shaped Japanese "
        "culture for a thousand years, and it reads "
        "today with startling intimacy."
    ),
    "the-four-agreements-ruiz": (
        "Don Miguel Ruiz's 1997 book grew out of the Toltec wisdom "
        "tradition of Mexico, and it distills that teaching into four "
        "personal vows. Ruiz begins with a striking idea: that "
        "everything we believe about ourselves and the world is a "
        "dream, a story we were told as children and have been "
        "retelling ever since, and that our suffering comes from "
        "living inside that dream without questioning it. The four "
        "agreements are the tools for waking up. Be impeccable "
        "with your word, and your words will no longer be "
        "weapons. Do not take anything personally, because "
        "other people's behavior is about them, never about "
        "you. Do not make assumptions, because assumptions "
        "are the source of most of our conflicts, and "
        "always do your best, which keeps the other three "
        "agreements alive no matter what happens. Each "
        "chapter takes one agreement and works through "
        "the habits of mind it replaces, and the book "
        "closes on the freedom that comes when the "
        "old dream loses its grip. Simple, "
        "repeatable and quietly profound, The "
        "Four Agreements has sold millions of "
        "copies and become a touchstone of "
        "modern spiritual writing."
    ),
    "12-rules-for-life": (
        "Jordan Peterson's 2018 bestseller is organized as twelve "
        "chapters, each built around a single rule, and each rule is "
        "less a commandment than an invitation to think about "
        "responsibility. Stand up straight with your shoulders back "
        "opens with lobsters, of all things, because they too "
        "organize themselves into hierarchies, and posture is "
        "biology's oldest language of confidence. Treat yourself "
        "like someone you are responsible for helping reframes "
        "self-care as a duty rather than an indulgence. Make "
        "friends with people who want the best for you, "
        "compare yourself to who you were yesterday, set "
        "your house in order before you criticize the "
        "world, pursue what is meaningful not what is "
        "expedient, tell the truth or at least do not "
        "lie, and assume that the person you are "
        "listening to might know something you do "
        "not. Peterson draws on psychology, the "
        "Bible, mythology and his own clinical "
        "practice, and his recurring argument is "
        "that meaning comes from accepting "
        "responsibility and confronting "
        "suffering head-on rather than "
        "avoiding it. Provocative, "
        "combative and unexpectedly "
        "moving, the book became a "
        "phenomenon and a battleground "
        "all at once."
    ),
    "book-dark-forest": (
        "Liu Cixin's 2008 novel, the second volume of the "
        "Remembrance of Earth's Past trilogy, opens with the "
        "universe's worst news: the Trisolaran fleet is on its way "
        "to Earth, four hundred years out, and its arrival means "
        "the end of human civilization. Facing an enemy that "
        "knows every human secret and cannot be out-fought, "
        "humanity devises its strangest strategy: four "
        "wallfacers, chosen individuals who are given "
        "unlimited resources and whose plans are kept "
        "secret even from their own governments, on "
        "the theory that only minds the enemy cannot "
        "read can save the species. Luo Ji, an "
        "astronomer and dreamer who never asked "
        "for the job, discovers the key to "
        "everything in an old puzzle about "
        "the silence of the stars: if "
        "civilizations are common and the "
        "universe is a dark forest, then "
        "every civilization that reveals "
        "itself is a hunter's target, and "
        "the only safe strategy is to "
        "shoot first. His solution, a "
        "star used as a threat and "
        "then as a test, forces the "
        "universe to answer, and "
        "the novel's final pages "
        "land like a fist on "
        "the table. Grand, "
        "cold and "
        "unforgettable, The "
        "Dark Forest is "
        "the trilogy's "
        "dark heart."
    ),
    "book-solaris": (
        "Stanislaw Lem's 1961 novel is science fiction about the "
        "failure of science itself. Kris Kelvin, a psychologist, "
        "arrives at a research station orbiting Solaris, a planet "
        "whose entire surface is one vast, living ocean, studied "
        "for decades by scientists who cannot make contact with "
        "it and cannot even agree on what they are seeing. The "
        "station is in crisis: the crew is hiding something, and "
        "Kelvin soon learns what it is. The ocean has begun to "
        "reach back, not with messages but with materializations "
        "drawn from the deepest, most private memories of the "
        "scientists, and for Kelvin this means Harey, his dead "
        "wife, returned in perfect, horrifying form, a being "
        "who does not know she is a copy and cannot be "
        "destroyed. Lem's novel refuses every comfort of the "
        "genre: the ocean is not a mirror of human concerns, "
        "contact does not lead to understanding, and the "
        "scientists' elaborate theories collapse into "
        "admissions of ignorance. Kelvin is left with "
        "the most human question of all, what we owe "
        "to the things we love even when we cannot "
        "understand them, and the book's brooding "
        "atmosphere, captured unforgettably in "
        "Tarkovsky's film adaptation, has made "
        "it a touchstone of philosophical "
        "science fiction."
    ),
    "book-lion-witch-wardrobe": (
        "C. S. Lewis's 1950 novel, the first published book of the "
        "Chronicles of Narnia, begins in the most ordinary place "
        "possible: four children, Peter, Susan, Edmund and Lucy "
        "Pevensie, evacuated from wartime London to a "
        "professor's rambling country house. Hiding from a "
        "game of hide-and-seek, Lucy steps through a "
        "wardrobe into a wood under snow, and the "
        "doorway leads to Narnia, a land under the "
        "spell of the White Witch, where it is "
        "always winter and never Christmas. She "
        "finds the faun Mr. Tumnus, who nearly "
        "betrays her and then cannot, and when "
        "the other children follow, Edmund falls "
        "under the Witch's spell with promises "
        "of Turkish delight and becomes her "
        "traitor. The children's arrival is the "
        "fulfillment of an old prophecy, and "
        "the great lion Aslan, who has been "
        "absent from Narnia for years, is "
        "returning. The book builds to "
        "Aslan's willing sacrifice on the "
        "Stone Table, and the resurrection "
        "that follows, and ends with the "
        "children crowned kings and "
        "queens of Narnia. A Christian "
        "allegory that works perfectly "
        "as an adventure, it remains "
        "the most beloved entry in "
        "the series."
    ),
    "book-last-unicorn": (
        "Peter S. Beagle's 1968 novel opens with a unicorn living in "
        "a lilac wood, content and immortal, until she overhears two "
        "hunters talking and learns a terrible thing: she may be the "
        "last of her kind. So she leaves the wood to find out what "
        "happened to the others, and the road takes her across a "
        "world that has forgotten her kind, until she meets "
        "Schmendrick, a magician who cannot do real magic yet, "
        "and Molly Grubb, a woman who remembers what it was "
        "like when magic was real. Their journey leads to the "
        "castle of King Haggard, who keeps his Red Bull, the "
        "beast that drove the unicorns into the sea, and to "
        "break the Bull's power the unicorn must be "
        "something it can catch: Schmendrick, in his "
        "one moment of true magic, turns her into a "
        "woman named Amalthea. The novel is a fairy "
        "tale about mortality and wonder, about the "
        "difference between living forever and "
        "living at all, and its ending, in which "
        "the unicorn becomes herself again and "
        "the last unicorn is revealed to be "
        "the first, has moved readers for "
        "generations. Elegant, funny and "
        "achingly sad, it is one of the "
        "greatest fantasy novels ever "
        "written."
    ),
    "the-power-of-now-tolle": (
        "Eckhart Tolle's 1997 book grew out of his own awakening, a "
        "night of despair in which he suddenly saw that he was not "
        "his thoughts, and its teaching is built on that one "
        "realization. The mind, Tolle argues, lives almost "
        "entirely in the past and the future, replaying what "
        "has happened and dreading what might, and it is "
        "that mental noise, not the world, that causes "
        "our suffering. The way out is presence: the "
        "practice of inhabiting the present moment, "
        "the only place where life actually "
        "happens. The book works through the "
        "obstacles to that practice, the ego "
        "that builds an identity out of "
        "complaint and comparison, the "
        "pain-body, a kind of reservoir "
        "of accumulated emotional "
        "suffering that feeds on "
        "negativity, and the "
        "habits of resistance "
        "and acceptance. It "
        "closes with the "
        "experience of the "
        "watcher, the "
        "still awareness "
        "behind the "
        "thoughts that "
        "is the real "
        "self, and "
        "with the "
        "promise "
        "that "
        "surrendering "
        "to the now "
        "is the "
        "doorway "
        "to "
        "peace. "
        "Sparse, "
        "repetitive "
        "and "
        "profoundly "
        "calming, "
        "it "
        "became "
        "one "
        "of "
        "the "
        "best-selling "
        "spiritual "
        "books "
        "of "
        "its "
        "era."
    ),
    "the-prophet-gibran": (
        "Kahlil Gibran's 1923 book is a series of poetic meditations "
        "framed by a single story. Almustafa, the chosen and beloved "
        "prophet, has lived for twelve years in the city of "
        "Orphalese, waiting for the ship that will carry him home, "
        "and when it finally arrives the people gather to ask him "
        "for his wisdom before he sails. Each question becomes a "
        "chapter, and each chapter a small essay in verse: on "
        "love, which he calls the only way to grow; on marriage "
        "and children, who are not ours to keep; on giving and "
        "work, joy and sorrow, crime and punishment, freedom "
        "and reason and passion, pain, self-knowledge, "
        "teaching, friendship, time, good and evil, prayer, "
        "pleasure, beauty, religion and death. Gibran's "
        "voice is biblical and aphoristic, and his "
        "answers circle the same gentle conviction: "
        "that the life of the spirit is lived in "
        "the ordinary particulars of living, "
        "that work and love and suffering "
        "are all forms of the same "
        "worship, and that death is "
        "only the last and greatest "
        "sailing. Translated into "
        "dozens of languages and "
        "quoted at weddings and "
        "funerals ever since, "
        "The Prophet is one "
        "of the best-selling "
        "books of the "
        "twentieth "
        "century."
    ),
    "book-homo-deus": (
        "Yuval Noah Harari's 2016 book, the sequel to Sapiens, asks "
        "what comes next. Its first half argues that the ancient "
        "scourges that shaped human history, famine, plague and "
        "war, have been largely conquered, and that the goals "
        "humanity has pursued for millennia are within reach; "
        "its second half asks what we will do with our success. "
        "Harari's answer is that we will turn on ourselves, "
        "using biotechnology, artificial intelligence and "
        "data to upgrade humans into something new: "
        "immortal, blissful and divine, no longer Homo "
        "sapiens at all. The book is at its most "
        "provocative when it examines the religion "
        "of the future, which he calls dataism, "
        "the faith that information flows are the "
        "highest good, and when it confronts the "
        "possibility that intelligence will "
        "outlive consciousness, that machines "
        "will come to know us better than we "
        "know ourselves, and that a large "
        "part of humanity will become "
        "economically useless. Written "
        "with the same lucid, "
        "globalizing sweep as "
        "Sapiens, Homo Deus is "
        "less a prediction than "
        "a warning, a book "
        "about the choices "
        "humanity will have "
        "to make once the "
        "old fears are "
        "gone."
    ),
    "book-the-art-of-war": (
        "Sun Tzu's treatise, written in China around the fifth century "
        "BCE, is the most influential work on strategy ever composed, "
        "a book of thirteen short chapters that has been studied by "
        "generals, executives, athletes and politicians for two and a "
        "half thousand years. Its core teaching is that war is won "
        "before it is fought: the supreme art is to break the "
        "enemy's resistance without fighting at all, by knowing "
        "yourself and knowing your enemy, by choosing the ground "
        "and the moment, and by making victory inevitable before "
        "a single blow is struck. Sun Tzu's advice ranges from "
        "the grand, that all warfare is based on deception and "
        "that the best victory is the one that costs nothing, "
        "to the tactical, how to move through terrain, how "
        "to use spies, how to attack by fire, how to "
        "handle the nine situations in which an army "
        "finds itself. Its terse, aphoristic style, "
        "full of lines that have entered the "
        "language, that the general who wins "
        "makes many calculations before the "
        "battle and the general who loses "
        "makes but few, has kept the "
        "book alive in boardrooms "
        "and battlefields alike, "
        "and it remains as "
        "sharp as the "
        "day it "
        "was written."
    ),
    "the-outliers-gladwell": (
        "Malcolm Gladwell's 2008 book takes the most American of "
        "subjects, the self-made success story, and asks what the "
        "story leaves out. His answer is that individual merit is "
        "real but never sufficient, and that success is built on "
        "opportunity, timing and inheritance as much as on talent "
        "and effort. The book's most famous idea is the ten "
        "thousand hour rule: the Beatles played Hamburg's clubs "
        "for years before they were the Beatles, and Bill Gates "
        "found the one computer in his school at exactly the "
        "moment he could spend thousands of hours on it. "
        "Around those stories Gladwell builds a whole "
        "ecology of advantage: the Matthew effect that "
        "gives early leads to the already-favored, the "
        "birth-date cutoffs that quietly decide which "
        "Canadian hockey players become stars, the "
        "cultural legacies, rice paddies versus "
        "cotton fields, that shape how whole "
        "peoples work and fail, and the "
        "cohort effects that made "
        "depression-era Jewish lawyers "
        "the most successful of their "
        "generation. By the end the "
        "book's real subject is "
        "clear: we tell stories "
        "about genius to avoid "
        "the uncomfortable "
        "truth that success "
        "is never "
        "solo."
    ),
    "grit-angela-duckworth": (
        "Angela Duckworth's 2016 book began with a question she "
        "asked as a young teacher in New York: why did some of her "
        "students succeed while others, just as bright, fell "
        "behind? The answer she came to, after studying West "
        "Point cadets, spelling bee champions and sales "
        "teams, is that talent matters far less than "
        "perseverance and passion sustained over "
        "years, the quality she calls grit. Duckworth "
        "shows that gritty people share a "
        "particular way of relating to their "
        "goals, a deep interest they have "
        "cultivated, a habit of daily "
        "deliberate practice aimed at "
        "weaknesses, a sense of "
        "purpose that connects the "
        "work to something beyond "
        "themselves, and the "
        "hope that comes from "
        "believing effort "
        "matters more than "
        "fixed ability. "
        "She is bracing "
        "about what "
        "grit is not: "
        "it is not "
        "talent, "
        "and it "
        "is not "
        "optimism "
        "without "
        "effort, "
        "and she "
        "closes "
        "with "
        "the "
        "hard "
        "question "
        "of how "
        "parents "
        "and "
        "teachers "
        "can "
        "help "
        "children "
        "develop "
        "it. "
        "Part "
        "memoir, "
        "part "
        "research "
        "report, "
        "Grit "
        "became "
        "an "
        "instant "
        "bestseller "
        "and "
        "a "
        "touchstone "
        "of "
        "the "
        "psychology "
        "of "
        "achievement."
    ),
    "the-midnight-library-haig": (
        "Matt Haig's 2020 novel begins at the end of a life. Nora "
        "Seed, thirty-five, is full of regrets: the music career "
        "she gave up, the love she pushed away, the dreams she "
        "let go, and the day her cat dies and she loses her "
        "job, she decides she has had enough. Between life "
        "and death she finds the midnight library, a vast "
        "room of books where each volume is a different "
        "version of her life, the one she could have "
        "lived if she had made another choice, and "
        "Mrs. Elm, her childhood librarian, offers "
        "her the chance to try them all. Nora "
        "steps into life after life: an Olympic "
        "swimmer, a rock star, a glaciologist "
        "in the Arctic, a pub owner, a "
        "mother in a coastal village, "
        "and in each one she learns "
        "the same uncomfortable "
        "truth, that every life "
        "has its own grief "
        "and its own "
        "regrets, and "
        "that the "
        "library's "
        "final "
        "lesson "
        "is not "
        "that "
        "another "
        "choice "
        "would "
        "have "
        "been "
        "better "
        "but "
        "that "
        "this "
        "one "
        "is "
        "hers. "
        "Warm, "
        "funny "
        "and "
        "relentlessly "
        "kind, "
        "The "
        "Midnight "
        "Library "
        "became "
        "one "
        "of "
        "the "
        "best-selling "
        "novels "
        "of "
        "its "
        "year."
    ),
    "quiet-susan-cain": (
        "Susan Cain's 2012 book is an argument about personality, "
        "and about the culture that made one kind of person the "
        "ideal. Cain traces how America moved from a culture of "
        "character, which valued the inner virtues of "
        "discipline and integrity, to a culture of "
        "personality, which prizes the magnetic, the "
        "outgoing, the quick with a story, and she "
        "shows what that shift cost the roughly a "
        "third of us who are introverts. Drawing "
        "on psychology, biology and her own "
        "experience as a Wall Street lawyer "
        "who learned to speak up, she "
        "explains what introversion "
        "actually is, a preference "
        "for lower stimulation "
        "and deeper "
        "processing, "
        "not shyness "
        "or "
        "weakness, "
        "and "
        "she "
        "shows "
        "the "
        "quiet "
        "strengths "
        "that "
        "the "
        "extrovert "
        "ideal "
        "overlooks: "
        "the "
        "focus, "
        "the "
        "empathy, "
        "the "
        "willingness "
        "to "
        "listen, "
        "the "
        "solitude "
        "out "
        "of "
        "which "
        "creativity "
        "grows. "
        "She "
        "closes "
        "with "
        "a "
        "defense "
        "of "
        "a "
        "more "
        "balanced "
        "culture, "
        "one "
        "that "
        "can "
        "hear "
        "its "
        "Rosa "
        "Parkses "
        "and "
        "Gandhis, "
        "and "
        "Quiet "
        "became "
        "a "
        "phenomenon "
        "for "
        "introverts "
        "everywhere "
        "who "
        "finally "
        "felt "
        "seen."
    ),
}


def main():
    with open(PATH, encoding="utf-8") as f:
        data = json.load(f)
    by_id = {t.get("id"): t for t in data}
    missing = [i for i in CONTENT if i not in by_id]
    if missing:
        raise SystemExit(f"ids not found in {PATH}: {missing}")
    changed = 0
    for topic in data:
        new_syn = CONTENT.get(topic.get("id"))
        if new_syn is None:
            continue
        if not FORCE and topic.get("synopsis", "").strip() == new_syn:
            continue
        topic["synopsis"] = new_syn
        changed += 1
    with open(PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"rewrote {changed} synopses (total topics {len(data)})")


if __name__ == "__main__":
    main()