#!/usr/bin/env python3
"""Generate the drawer banner sky (moon + stars) as an editable SVG.

Reproduces EXACTLY what `DrawerCelestialSky` draws in
app/src/main/java/com/curio/app/features/home/HomeScreen.kt — same seeded
star scatter (kotlin.random.Random wraps java.util.Random on JVM, so the
LCG below matches the app's `Random(seed)` output), same grain, sparkles,
constellation lines and crescent moon.

Usage:
    python3 tools/gen_drawer_banner_svg.py

Writes design/drawer-banner/drawer-banner-sky-light.svg (the default
light-mode look) and drawer-banner-sky-dark.svg (dark mode). Edit the
PALETTES dict at the bottom (or the SVGs themselves) to restyle.

The banner is 320dp wide x 186dp tall (the drawer's fixed width and
HomeDrawerHeroHeight), so the SVG viewBox is 0 0 320 186 — 1 unit = 1dp.
"""

import math
import os

# ── java.util.Random LCG (matches kotlin.random.Random(seed) on JVM) ────
MULTIPLIER = 0x5DEECE66D  # java.util.Random's LCG multiplier
ADDEND = 0xB
MASK = (1 << 48) - 1


class JRandom:
    def __init__(self, seed: int):
        self.state = (seed ^ MULTIPLIER) & MASK

    def _next(self, bits: int) -> int:
        self.state = (self.state * MULTIPLIER + ADDEND) & MASK
        return self.state >> (48 - bits)

    def next_float(self) -> float:
        """java.util.Random.nextFloat() == next(24) / 2^24."""
        return self._next(24) / float(1 << 24)


# ── The app's scene constants ────────────────────────────────────────────
HOME_DRAWER_TEAR_SEED = 0xD2A7E
W, H = 320.0, 186.0  # drawer hero size in dp


def stars_and_grain():
    rnd = JRandom(HOME_DRAWER_TEAR_SEED)
    stars = [
        {
            "x": 0.04 + rnd.next_float() * 0.92,
            "y": 0.06 + rnd.next_float() * 0.84,
            "r": 0.7 + rnd.next_float() * 1.1,
            "a": 0.28 + rnd.next_float() * 0.45,
        }
        for _ in range(30)
    ]
    rnd = JRandom(HOME_DRAWER_TEAR_SEED + 17)
    grain = [
        {
            "x": rnd.next_float(),
            "y": rnd.next_float(),
            "r": 0.35 + rnd.next_float() * 0.45,
            "a": 0.05 + rnd.next_float() * 0.08,
        }
        for _ in range(52)
    ]
    return stars, grain


# Fixed scene elements from DrawerCelestialSky (fractional x/y + dp size).
LINKS = [
    (0.16, 0.30, 0.24, 0.22),
    (0.24, 0.22, 0.34, 0.26),
    (0.34, 0.26, 0.38, 0.36),
    (0.38, 0.36, 0.30, 0.44),
    (0.30, 0.44, 0.16, 0.30),
    (0.16, 0.30, 0.10, 0.38),
]
SPARKLES = [(0.78, 0.28, 7.0), (0.55, 0.15, 5.0), (0.90, 0.56, 4.0)]
MOON = {"fx": 0.84, "fy": 0.28, "r": 13.0}


def sparkle_path(cx: float, cy: float, size: float) -> str:
    """8-point concave star (alternating spike / valley), matching the
    app's drawSparkle()."""
    spike, valley = size, size * 0.30
    pts = []
    for i in range(8):
        angle = i * (math.pi / 4.0)
        r = spike if i % 2 == 0 else valley
        pts.append(f"{cx + math.cos(angle) * r:.2f},{cy + math.sin(angle) * r:.2f}")
    return " ".join(pts)


def hex_color(rgb: tuple) -> str:
    r, g, b = rgb
    return f"#{int(round(r)):02X}{int(round(g)):02X}{int(round(b)):02X}"


def lerp(a: tuple, b: tuple, t: float) -> tuple:
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def build_svg(palette: dict, light: dict, dark: dict) -> str:
    sky_top, sky_bottom = palette["skyTop"], palette["skyBottom"]
    star = palette["starTint"]
    punch = lerp(sky_top, sky_bottom, 0.28)  # the app's localSky at 0.28
    stars, grain = stars_and_grain()

    def fill(circle, ink):
        x, y, r, a = circle["x"] * W, circle["y"] * H, circle["r"], circle["a"]
        return f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{r:.2f}" opacity="{a:.2f}"/>'

    parts = []
    parts.append(f"""<svg xmlns="http://www.w3.org/2000/svg" width="{int(W)}" height="{int(H)}" viewBox="0 0 {int(W)} {int(H)}">
  <!-- Curio drawer banner sky — generated by tools/gen_drawer_banner_svg.py
       (mirrors DrawerCelestialSky in HomeScreen.kt exactly: same seed
       {f"0x{HOME_DRAWER_TEAR_SEED:X}"}, same layout). 1 unit = 1dp (banner
       is 320x186). To restyle: change the palette in the <style> block.
       Light: skyTop {hex_color(light['skyTop'])} / skyBottom {hex_color(light['skyBottom'])} / ink {hex_color(light['starTint'])}.
       Dark : skyTop {hex_color(dark['skyTop'])} / skyBottom {hex_color(dark['skyBottom'])} / ink {hex_color(dark['starTint'])}. -->
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="{hex_color(sky_top)}"/>
      <stop offset="1" stop-color="{hex_color(sky_bottom)}"/>
    </linearGradient>
    <style>
      .link    {{ stroke: {hex_color(star)}; stroke-width: 1; stroke-opacity: 0.14; fill: none; }}
      .grain   {{ fill: {hex_color(star)}; }}
      .star    {{ fill: {hex_color(star)}; }}
      .sparkle {{ fill: {hex_color(star)}; }}
      .moon    {{ fill: {hex_color(star)}; fill-opacity: 0.85; }}
    </style>
  </defs>
  <rect width="{int(W)}" height="{int(H)}" fill="url(#sky)"/>
  <!-- Constellation (drawn first, under everything) -->
  <g id="links" class="link">""")
    for x1, y1, x2, y2 in LINKS:
        parts.append(
            f'    <line x1="{x1 * W:.2f}" y1="{y1 * H:.2f}" x2="{x2 * W:.2f}" y2="{y2 * H:.2f}"/>'
        )
    parts.append("  </g>")
    parts.append('  <!-- Ultra-faint paper grain -->\n  <g id="grain" class="grain">')
    for c in grain:
        parts.append(f"    {fill(c, star)}")
    parts.append("  </g>")
    parts.append('  <!-- Stars -->\n  <g id="stars" class="star">')
    for c in stars:
        parts.append(f"    {fill(c, star)}")
    parts.append("  </g>")
    parts.append('  <!-- Four-point sparkles -->\n  <g id="sparkles" class="sparkle" opacity="0.75">')
    for fx, fy, s in SPARKLES:
        cx, cy = fx * W, fy * H
        parts.append(f'    <path d="M{sparkle_path(cx, cy, s)} Z"/>')
    parts.append("  </g>")
    # Crescent moon: full ink disc punched by a circle of the LOCAL sky
    # colour at the moon's height (the app punches with lerp(skyTop,
    # skyBottom, 0.28), so the punch is invisible against the gradient).
    mc_x, mc_y = MOON["fx"] * W, MOON["fy"] * H
    mr = MOON["r"]
    parts.append(f"""  <!-- Crescent moon (carved with the local sky colour) -->
  <g id="moon">
    <circle class="moon" cx="{mc_x:.2f}" cy="{mc_y:.2f}" r="{mr}"/>
    <circle fill="{hex_color(punch)}" cx="{mc_x + mr * 0.55:.2f}" cy="{mc_y - mr * 0.38:.2f}" r="{mr}"/>
  </g>
</svg>""")
    return "\n".join(parts)


PALETTES = {
    "light": {
        "skyTop": (194, 232, 222),   # 0xFFC2E8DE
        "skyBottom": (233, 246, 240),  # 0xFFE9F6F0
        "starTint": (44, 90, 83),    # 0xFF2C5A53
        "dark_skyTop": (18, 49, 58),   # 0xFF12313A
        "dark_skyBottom": (29, 71, 80),  # 0xFF1D4750
        "dark_starTint": (255, 253, 244),  # 0xFFFFFDF4
        "file": "design/drawer-banner/drawer-banner-sky-light.svg",
    },
    "dark": {
        "skyTop": (18, 49, 58),      # 0xFF12313A
        "skyBottom": (29, 71, 80),   # 0xFF1D4750
        "starTint": (255, 253, 244),  # 0xFFFFFDF4
        "dark_skyTop": (18, 49, 58),
        "dark_skyBottom": (29, 71, 80),
        "dark_starTint": (255, 253, 244),
        "file": "design/drawer-banner/drawer-banner-sky-dark.svg",
    },
}


def main():
    root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
    for key, pal in PALETTES.items():
        path = os.path.join(root, pal["file"])
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(build_svg(pal, PALETTES["light"], PALETTES["dark"]))
        print(f"wrote {os.path.relpath(path, root)}")


if __name__ == "__main__":
    main()
